export type CatalogSleeve = {
  id: string;
  name: string;
  description?: string;
  image?: string;
  defaultPriceCents: number;
  defaultStock: number;
  active?: boolean;
};

export const catalogSleeves: CatalogSleeve[] = [
  {id: "pikachu-celebration", name: " Pikachu Célébration", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "pikachu-flagadoss", name: " Pikachu Flagadoss", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 200, defaultStock: 3, active: true,},
  {id: "pikachu-1", name: "Pikachu 1", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "pikachu-2", name: "Pikachu 2", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "pikachu-or", name: "Pikachu Or", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "pikachu-zekrom", name: "Pikachu Zekrom", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "pikachu-pohm", name: "Pikachu Pohm", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 1, active: true,},
  {id: "pikachu-cerise", name: "Pikachu Cerise", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "zoroark", name: "Zoroark", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "reshiram", name: "Reshiram", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "zekrom", name: "Zekrom", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "dracaufeu-1", name: "Dracaufeu 1", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "dracaufeu-2", name: "Dracaufeu 2", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "dracaufeu-3", name: "Dracaufeu 3", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "dracaufeu-4", name: "Dracaufeu 4", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "dracaufeu-5", name: "Dracaufeu 5", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "dracaufeu-6", name: "Dracaufeu 6", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "dracaufeu-7", name: "Dracaufeu 7", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "herbizarre", name: "Herbizarre", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "florizarre", name: "Florizarre", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "starter-ev02", name: "Starter EV02", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "oiseaux-leg", name: "Oiseaux Légendaire", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "goupix", name: "Goupix", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "tortank-1", name: "Tortank 1", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "tortank-2", name: "Tortank 2", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "deoxys", name: "Deoxys", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "darkrai", name: "Drakrai", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "ho-oh", name: "HO-OH", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "rayquaza", name: "Rayquaza", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 1, active: true,},
  {id: "palkia-dialga-arceus", name: "Palkia Dialga Arceus", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "mewtow-1", name: "Mewtow 1", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "mewtow-2", name: "Mewtwo 2", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "mew-1", name: "Mew 1", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "mew-2", name: "Mew 2", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "mew-3", name: "Mew 3", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "flingouste", name: "Flingouste", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 1, active: true,},
  {id: "dracolosse", name: "Dracolosse", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 1, active: true,},
  {id: "lucario", name: "Lucario", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "mimiqui", name: "Mimiqui", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "zacian", name: "Zacian", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "zamazenta", name: "Zamazenta", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "solgaleo", name: "Solgaleo", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "lunala", name: "Lunala", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "ethernatos", name: "Ethernatos", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "mandrillon", name: "Mandrillon", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "giratina", name: "Giratina", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "koraidon", name: "Koraidon", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "miraidon", name: "Miraidon", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "shifours-1", name: "Shifours 1", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "Shifours-2", name: "Shifours 2", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "sleeve-1", name: "Sleeve 1", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "sleeve-2", name: "Sleeve 2", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "arceus", name: "Arceus", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 4, active: true,},
  {id: "serpente-eau", name: "Serpente-Eau", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "ogerpon-1", name: "Ogerpon 1", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "ogerpon-2", name: "Ogerpon 2", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "sleeve-3", name: "Sleeve 3", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "viridium", name: "Viridium", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "gardevoir-1", name: "Gardevoir 1", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "gardevoir-2", name: "Gardevoir 2", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 1, active: true,},
  {id: "sylveroie-1", name: "Sylveroie 1", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "sylveroie-2", name: "Sylveroie 2", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "malvalame", name: "Malvalame", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "zeraora", name: "Zeraora", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "carnarticho", name: "Canarticho", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "garde-de-fer", name: "Garde De Fer", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "sleeve-4", name: "Sleeve 4", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "leviator-1", name: "Léviator 1", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "morpeko", name: "Morpeko", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "roigada", name: "Roigada", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "feunec", name: "Feunec", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "leviator-2", name: "Léviator 2", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "leviator-2", name: "Léviator 3", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "salameche-1", name: "Salameche 1", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "salameche-2", name: "Salameche 2", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "evoli-giravili", name: "Evolie Givrali", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 200, defaultStock: 2, active: true,},
  {id: "evoli-pyroli", name: "Evoli Pyroli", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 200, defaultStock: 2, active: true,},
  {id: "evoli-mentali", name: "Evoli Mentali", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 200, defaultStock: 2, active: true,},
  {id: "evolition-1", name: "Evolition 1", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 1, active: true,},
  {id: "evolition-2", name: "Evolition 2", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "evoli", name: "Evoli", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "evoli-prismatique", name: "Evoli Prismatique", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "evolition-3", name: "Evolition 3", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "evolition-4", name: "Evolition 4", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "evolition-5", name: "Evolition 5", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "evolition-6", name: "Evolition 6", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "evolition-7", name: "Evolition 7", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 3, active: true,},
  {id: "noctali", name: "Noctali", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 1, active: true,},
  {id: "sleeve-5", name: "Sleeve 5", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "sleeve-6", name: "Sleeve 6", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 1, active: true,},
  {id: "sleeve-7", name: "Sleeve 7", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 2, active: true,},
  {id: "sleeve-8", name: "Sleeve 8", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "sleeve-9", name: "Sleeve 9", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 5, active: true,},
  {id: "sleeve-10", name: "Sleeve 10", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "sleeve-11", name: "Sleeve 11", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "sleeve-12", name: "Sleeve 12", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 2, active: true,},
  {id: "sleeve-13", name: "Sleeve 13", description: "Lot de sleeves pour protéger les cartes Pokémon.", image: "/sleeves/sleeve-pokemon-transparent.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  
  
  
];

export function getCatalogSleeves() {
  return catalogSleeves;
}

export function getCatalogSleeve(id: string) {
  return catalogSleeves.find((sleeve) => sleeve.id === id);
}
