export type CatalogSleeve = {
  id: string;
  name: string;
  description?: string;
  image?: string;
  defaultPriceCents: number;
  defaultStock: number;
  active?: boolean;
};

export const catalogSleeves: CatalogSleeve[] = [
  {id: "pikachu-celebration", name: " Pikachu Célébration", description: "1 sleeve.", image: "/sleeves/pikaceleb.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "pikachu-flagadoss", name: " Pikachu Flagadoss", description: "1 sleeve.", image: "/sleeves/pikafla.webp", defaultPriceCents: 200, defaultStock: 3, active: true,},
  {id: "pikachu-1", name: "Pikachu 1", description: "1 sleeve.", image: "/sleeves/pika1.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "pikachu-2", name: "Pikachu 2", description: "1 sleeve.", image: "/sleeves/pika2.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "pikachu-or", name: "Pikachu Or", description: "1 sleeve.", image: "/sleeves/pikaor.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "pikachu-zekrom", name: "Pikachu Zekrom", description: "1 sleeve.", image: "/sleeves/pikaz.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "pikachu-pohm", name: "Pikachu Pohm", description: "1 sleeve.", image: "/sleeves/7.webp", defaultPriceCents: 100, defaultStock: 1, active: true,},
  {id: "pikachu-cerise", name: "Pikachu Cerise", description: "1 sleeve.", image: "/sleeves/pikaC.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "zoroark", name: "Zoroark", description: "1 sleeve.", image: "/sleeves/9.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "reshiram", name: "Reshiram", description: "1 sleeve.", image: "/sleeves/reshiram.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "zekrom", name: "Zekrom", description: "1 sleeve.", image: "/sleeves/11.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "dracaufeu-1", name: "Dracaufeu 1", description: "1 sleeve.", image: "/sleeves/drac1.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "dracaufeu-2", name: "Dracaufeu 2", description: "1 sleeve.", image: "/sleeves/drac2.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "dracaufeu-3", name: "Dracaufeu 3", description: "1 sleeve.", image: "/sleeves/drac3.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "dracaufeu-4", name: "Dracaufeu 4", description: "1 sleeve.", image: "/sleeves/drac4.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "dracaufeu-5", name: "Dracaufeu 5", description: "1 sleeve.", image: "/sleeves/drac5.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "dracaufeu-6", name: "Dracaufeu 6", description: "1 sleeve.", image: "/sleeves/drac6.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "dracaufeu-7", name: "Dracaufeu 7", description: "1 sleeve.", image: "/sleeves/drac7.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "herbizarre", name: "Herbizarre", description: "1 sleeve.", image: "/sleeves/herbi.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "florizarre", name: "Florizarre", description: "1 sleeve.", image: "/sleeves/florizarre.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "starter-ev02", name: "Starter EV02", description: "1 sleeve.", image: "/sleeves/ev2.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "oiseaux-leg", name: "Oiseaux Légendaire", description: "1 sleeve.", image: "/sleeves/oiseauxleg.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "goupix", name: "Goupix", description: "1 sleeve.", image: "/sleeves/goupix.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "tortank-1", name: "Tortank 1", description: "1 sleeve.", image: "/sleeves/tortank1.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "tortank-2", name: "Tortank 2", description: "1 sleeve.", image: "/sleeves/tortank2.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "deoxys", name: "Deoxys", description: "1 sleeve.", image: "/sleeves/deoxys.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "darkrai", name: "Drakrai", description: "1 sleeve.", image: "/sleeves/darkrai.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "ho-oh", name: "HO-OH", description: "1 sleeve.", image: "/sleeves/hooh.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "rayquaza", name: "Rayquaza", description: "1 sleeve.", image: "/sleeves/rayquaza.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "palkia-dialga-arceus", name: "Palkia Dialga Arceus", description: "1 sleeve.", image: "/sleeves/PDA.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "mewtow-1", name: "Mewtow 1", description: "1 sleeve.", image: "/sleeves/mewtwo1.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "mewtow-2", name: "Mewtwo 2", description: "1 sleeve.", image: "/sleeves/mewtwo2.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "mew-1", name: "Mew 1", description: "1 sleeve.", image: "/sleeves/mew.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "mew-2", name: "Mew 2", description: "1 sleeve.", image: "/sleeves/mew1.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "mew-3", name: "Mew 3", description: "1 sleeve.", image: "/sleeves/mew2.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "flingouste", name: "Flingouste", description: "1 sleeve.", image: "/sleeves/flingouste.webp", defaultPriceCents: 100, defaultStock: 1, active: true,},
  {id: "dracolosse", name: "Dracolosse", description: "1 sleeve.", image: "/sleeves/dracolosse.webp", defaultPriceCents: 100, defaultStock: 1, active: true,},
  {id: "lucario", name: "Lucario", description: "1 sleeve.", image: "/sleeves/lucario.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "mimiqui", name: "Mimiqui", description: "1 sleeve.", image: "/sleeves/mimiqui.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "zacian", name: "Zacian", description: "1 sleeve.", image: "/sleeves/zacian.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "zamazenta", name: "Zamazenta", description: "1 sleeve.", image: "/sleeves/zamazenta.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "solgaleo", name: "Solgaleo", description: "1 sleeve.", image: "/sleeves/solgaleo.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "lunala", name: "Lunala", description: "1 sleeve.", image: "/sleeves/lunala.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "ethernatos", name: "Ethernatos", description: "1 sleeve.", image: "/sleeves/ethernatos.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "mandrillon", name: "Mandrillon", description: "1 sleeve.", image: "/sleeves/mandrillon.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "giratina", name: "Giratina", description: "1 sleeve.", image: "/sleeves/gira.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "koraidon", name: "Koraidon", description: "1 sleeve.", image: "/sleeves/koraidon.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "miraidon", name: "Miraidon", description: "1 sleeve.", image: "/sleeves/miraidon.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "shifours-1", name: "Shifours 1", description: "1 sleeve.", image: "/sleeves/shifours1.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "shifours-2", name: "Shifours 2", description: "1 sleeve.", image: "/sleeves/shifours2.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  //{id: "sleeve-1", name: "Sleeve 1", description: "1 sleeve.", image: "/sleeves/51.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  //{id: "sleeve-2", name: "Sleeve 2", description: "1 sleeve.", image: "/sleeves/52.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "arceus", name: "Arceus", description: "1 sleeve.", image: "/sleeves/arc.webp", defaultPriceCents: 100, defaultStock: 4, active: true,},
  {id: "serpente-eau", name: "Serpente-Eau", description: "1 sleeve.", image: "/sleeves/54.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "ogerpon-1", name: "Ogerpon 1", description: "1 sleeve.", image: "/sleeves/ogerpon.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "ogerpon-2", name: "Ogerpon 2", description: "1 sleeve.", image: "/sleeves/56.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  //{id: "sleeve-3", name: "Sleeve 3", description: "1 sleeve.", image: "/sleeves/57.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "viridium", name: "Viridium", description: "1 sleeve.", image: "/sleeves/viridium.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "gardevoir-1", name: "Gardevoir 1", description: "1 sleeve.", image: "/sleeves/gardevir.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "gardevoir-2", name: "Gardevoir 2", description: "1 sleeve.", image: "/sleeves/60.webp", defaultPriceCents: 100, defaultStock: 1, active: true,},
  {id: "sylveroie-1", name: "Sylveroie 1", description: "1 sleeve.", image: "/sleeves/61.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "sylveroie-2", name: "Sylveroie 2", description: "1 sleeve.", image: "/sleeves/62.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "malvalame", name: "Malvalame", description: "1 sleeve.", image: "/sleeves/63.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "zeraora", name: "Zeraora", description: "1 sleeve.", image: "/sleeves/64.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "palarticho", name: "Palarticho", description: "1 sleeve.", image: "/sleeves/palarticho.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "garde-de-fer", name: "Garde De Fer", description: "1 sleeve.", image: "/sleeves/gardefer.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  //{id: "sleeve-4", name: "Sleeve 4", description: "1 sleeve.", image: "/sleeves/67.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "leviator-1", name: "Léviator 1", description: "1 sleeve.", image: "/sleeves/leviator1.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "morpeko", name: "Morpeko", description: "1 sleeve.", image: "/sleeves/morpe.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "roigada", name: "Roigada", description: "1 sleeve.", image: "/sleeves/roigada.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "feunec", name: "Feunec", description: "1 sleeve.", image: "/sleeves/71.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "leviator-2", name: "Léviator 2", description: "1 sleeve.", image: "/sleeves/leviator2.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "leviator-3", name: "Léviator 3", description: "1 sleeve.", image: "/sleeves/leviacornebre.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "salameche-1", name: "Salameche 1", description: "1 sleeve.", image: "/sleeves/salameche1.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "salameche-2", name: "Salameche 2", description: "1 sleeve.", image: "/sleeves/salameche2.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "evoli-giravili", name: "Evolie Givrali", description: "1 sleeve.", image: "/sleeves/evogivra.webp", defaultPriceCents: 200, defaultStock: 2, active: true,},
  {id: "evoli-pyroli", name: "Evoli Pyroli", description: "1 sleeve.", image: "/sleeves/evopyro.webp", defaultPriceCents: 200, defaultStock: 2, active: true,},
  {id: "evoli-mentali", name: "Evoli Mentali", description: "1 sleeve.", image: "/sleeves/evomenta.webp", defaultPriceCents: 200, defaultStock: 2, active: true,},
  {id: "evolition-1", name: "Evolition 1", description: "1 sleeve.", image: "/sleeves/evolition1.webp", defaultPriceCents: 100, defaultStock: 1, active: true,},
  {id: "evolition-2", name: "Evolition 2", description: "1 sleeve.", image: "/sleeves/evolition2.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "evoli", name: "Evoli", description: "1 sleeve.", image: "/sleeves/evo.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "evoli-prismatique", name: "Evoli Prismatique", description: "1 sleeve.", image: "/sleeves/evoprima.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  {id: "evolition-3", name: "Evolition 3", description: "1 sleeve.", image: "/sleeves/evolition3.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "evolition-4", name: "Evolition 4", description: "1 sleeve.", image: "/sleeves/evolition4.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "evolition-5", name: "Evolition 5", description: "1 sleeve.", image: "/sleeves/evolition5.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "evolition-6", name: "Evolition 6", description: "1 sleeve.", image: "/sleeves/evolition6.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  {id: "evolition-7", name: "Evolition 7", description: "1 sleeve.", image: "/sleeves/evolition.webp", defaultPriceCents: 100, defaultStock: 3, active: true,},
  {id: "noctali", name: "Noctali", description: "1 sleeve.", image: "/sleeves/noc.webp", defaultPriceCents: 100, defaultStock: 1, active: true,},
  //{id: "sleeve-5", name: "Sleeve 5", description: "1 sleeve.", image: "/sleeves/89.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
//{id: "sleeve-6", name: "Sleeve 6", description: "1 sleeve.", image: "/sleeves/90.webp", defaultPriceCents: 100, defaultStock: 1, active: true,},
  //{id: "sleeve-7", name: "Sleeve 7", description: "1 sleeve.", image: "/sleeves/91.webp", defaultPriceCents: 100, defaultStock: 2, active: true,},
  //{id: "sleeve-8", name: "Sleeve 8", description: "1 sleeve.", image: "/sleeves/92.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  //{id: "sleeve-9", name: "Sleeve 9", description: "1 sleeve.", image: "/sleeves/93.webp", defaultPriceCents: 100, defaultStock: 5, active: true,},
  //{id: "sleeve-10", name: "Sleeve 10", description: "1 sleeve.", image: "/sleeves/94.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  //{id: "sleeve-11", name: "Sleeve 11", description: "1 sleeve.", image: "/sleeves/95.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  //{id: "sleeve-12", name: "Sleeve 12", description: "1 sleeve.", image: "/sleeves/96.webp", defaultPriceCents: 100, defaultStock: 2, active: true,},
  //{id: "sleeve-13", name: "Sleeve 13", description: "1 sleeve.", image: "/sleeves/97.webp", defaultPriceCents: 100, defaultStock: 10, active: true,},
  //{id: "mewtow-3", name: "Mewtwo 3", description: "1 sleeve.", image: "/sleeves/98.webp", defaultPriceCents: 50, defaultStock: 10, active: true,},
  
  
  
];

export function getCatalogSleeves() {
  return catalogSleeves;
}

export function getCatalogSleeve(id: string) {
  return catalogSleeves.find((sleeve) => sleeve.id === id);
}
