// Promos XY
  { id: "promos-xy-xy01", serieId: "prxy", name: "Marisson", number: "XY01", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/1.webp", },
  { id: "promos-xy-xy02", serieId: "prxy", name: "Feunnec", number: "XY02", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/2.webp", },
  { id: "promos-xy-xy03", serieId: "prxy", name: "Grenousse", number: "XY03", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/3.webp", },
  { id: "promos-xy-xy04", serieId: "prxy", name: "Nymphali", number: "XY04", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/4.webp", },
  { id: "promos-xy-xy05", serieId: "prxy", name: "Xerneas", number: "XY05", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXYy5.webp", },
  { id: "promos-xy-xy06", serieId: "prxy", name: "Yveltal", number: "XY06", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/6.webp", },
  { id: "promos-xy-xy07", serieId: "prxy", name: "Xerneas-EX", number: "XY07", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy7.webp", },
  { id: "promos-xy-xy08", serieId: "prxy", name: "Yveltal-EX", number: "XY08", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy8.webp", },
  { id: "promos-xy-xy09", serieId: "prxy", name: "Carchacrok-EX", number: "XY09", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy9.webp", },
  { id: "promos-xy-xy10", serieId: "prxy", name: "Kravarech", number: "XY10", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy10.webp", },
  { id: "promos-xy-xy11", serieId: "prxy", name: "Cabriolaine", number: "XY11", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy11.webp", },
  { id: "promos-xy-xy12", serieId: "prxy", name: "Monorpale", number: "XY12", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy12.webp", },
  { id: "promos-xy-xy13", serieId: "prxy", name: "Mackogneur", number: "XY13", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy13.webp", },
  { id: "promos-xy-xy14", serieId: "prxy", name: "Desséliande", number: "XY14", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy14.webp", },
  { id: "promos-xy-xy15", serieId: "prxy", name: "Cupcanaille", number: "XY15", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy15.webp", },
  { id: "promos-xy-xy16", serieId: "prxy", name: "Chevroum", number: "XY16", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy16.webp", },
  { id: "promos-xy-xy17", serieId: "prxy", name: "Dracaufeu-EX", number: "XY17", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy17.webp", },
  { id: "promos-xy-xy18", serieId: "prxy", name: "Blindépique-EX", number: "XY18", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy18.webp", },
  { id: "promos-xy-xy19", serieId: "prxy", name: "Goupelin-EX", number: "XY19", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy19.webp", },
  { id: "promos-xy-xy20", serieId: "prxy", name: "Amphinobi-EX", number: "XY20", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy20.webp", },
  { id: "promos-xy-xy21", serieId: "prxy", name: "Archéodong", number: "XY21", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy21.webp", },
  { id: "promos-xy-xy22", serieId: "prxy", name: "Darkrai", number: "XY22", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy22.webp", },
  { id: "promos-xy-xy23", serieId: "prxy", name: "Tengalice", number: "XY23", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy23.webp", },
  { id: "promos-xy-xy24", serieId: "prxy", name: "Amphinobi", number: "XY24", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy24.webp", },
  { id: "promos-xy-xy25", serieId: "prxy", name: "Crocorible-EX", number: "XY25", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy25.webp", },
  { id: "promos-xy-xy26", serieId: "prxy", name: "Némélios", number: "XY26", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy26.webp", },
  { id: "promos-xy-xy27", serieId: "prxy", name: "Festival des Champions", number: "XY27", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy27.webp", },
  { id: "promos-xy-xy28", serieId: "prxy", name: "Florizarre-EX", number: "XY28", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy28.webp", },
  { id: "promos-xy-xy29", serieId: "prxy", name: "Dracaufeu-EX", number: "XY29", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy29.webp", },
  { id: "promos-xy-xy30", serieId: "prxy", name: "Tortank-EX", number: "XY30", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy30.webp", },
  { id: "promos-xy-xy31", serieId: "prxy", name: "Xerneas", number: "XY31", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy31.webp", },
  { id: "promos-xy-xy32", serieId: "prxy", name: "Yveltal", number: "XY32", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy32.webp", },
  { id: "promos-xy-xy33", serieId: "prxy", name: "Trovato", number: "XY33", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy33.webp", },
  { id: "promos-xy-xy34", serieId: "prxy", name: "Métalosse-EX", number: "XY34", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy34.webp", },
  { id: "promos-xy-xy35", serieId: "prxy", name: "M-Métalosse-EX", number: "XY35", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy35.webp", },
  { id: "promos-xy-xy36", serieId: "prxy", name: "Arcko", number: "XY36", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy36.webp", },
  { id: "promos-xy-xy37", serieId: "prxy", name: "Poussifeu", number: "XY37", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy37.webp", },
  { id: "promos-xy-xy38", serieId: "prxy", name: "Gobou", number: "XY38", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy38.webp", },
  { id: "promos-xy-xy39", serieId: "prxy", name: "Hyporoi", number: "XY39", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy39.webp", },
  { id: "promos-xy-xy40", serieId: "prxy", name: "Métamorph", number: "XY40", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy40.webp", },
  { id: "promos-xy-xy41", serieId: "prxy", name: "Kyogre-EX", number: "XY41", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy41.webp", },
  { id: "promos-xy-xy42", serieId: "prxy", name: "Groudon-EX", number: "XY42", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy42.webp", },
  { id: "promos-xy-xy43", serieId: "prxy", name: "Diancie-EX", number: "XY43", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy43.webp", },
  { id: "promos-xy-xy44", serieId: "prxy", name: "M-Diancie-EX", number: "XY44", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy44.webp", },
  { id: "promos-xy-xy45", serieId: "prxy", name: "Gallame-EX", number: "XY45", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy45.webp", },
  { id: "promos-xy-xy46", serieId: "prxy", name: "Altaria", number: "XY46", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy46.webp", },
  { id: "promos-xy-xy47", serieId: "prxy", name: "Iguolta", number: "XY47", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy47.webp", },
  { id: "promos-xy-xy48", serieId: "prxy", name: "Mistigrix", number: "XY48", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy48.webp", },
  { id: "promos-xy-xy49", serieId: "prxy", name: "Regirock", number: "XY49", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy49.webp", },
  { id: "promos-xy-xy50", serieId: "prxy", name: "Pandarbare", number: "XY50", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy50.webp", },
  { id: "promos-xy-xy51", serieId: "prxy", name: "Kyogre", number: "XY51", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy51.webp", },
  { id: "promos-xy-xy52", serieId: "prxy", name: "Groudon", number: "XY52", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy52.webp", },
  { id: "promos-xy-xy53", serieId: "prxy", name: "Jungko-EX", number: "XY53", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy53.webp", },
  { id: "promos-xy-xy54", serieId: "prxy", name: "Braségali-EX", number: "XY54", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy54.webp", },
  { id: "promos-xy-xy55", serieId: "prxy", name: "Laggron-EX", number: "XY55", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy55.webp", },
  { id: "promos-xy-xy56", serieId: "prxy", name: "Leuphorie", number: "XY56", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy56.webp", },
  { id: "promos-xy-xy57", serieId: "prxy", name: "Rapasdepic", number: "XY57", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy57.webp", },
  { id: "promos-xy-xy58", serieId: "prxy", name: "Sepiatroce", number: "XY58", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy58.webp", },
  { id: "promos-xy-xy59", serieId: "prxy", name: "Drattak", number: "XY59", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy59.webp", },
  { id: "promos-xy-xy60", serieId: "prxy", name: "Léviator", number: "XY60", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy60.webp", },
  { id: "promos-xy-xy61", serieId: "prxy", name: "Libégon-EX", number: "XY61", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy61.webp", },
  { id: "promos-xy-xy62", serieId: "prxy", name: "Absol-EX", number: "XY62", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy62.webp", },
  { id: "promos-xy-xy63", serieId: "prxy", name: "M-Absol-EX", number: "XY63", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy63.webp", },
  { id: "promos-xy-xy64", serieId: "prxy", name: "Rayquaza", number: "XY64", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy64.webp", },
  { id: "promos-xy-xy65", serieId: "prxy", name: "Latios", number: "XY65", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy65.webp", },
  { id: "promos-xy-xy66", serieId: "prxy", name: "Rayquaza-EX", number: "XY66", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy66.webp", },
  { id: "promos-xy-xy67", serieId: "prxy", name: "Jirachi", number: "XY67", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy67.webp", },
  { id: "promos-xy-xy68", serieId: "prxy", name: "Blindépique", number: "XY68", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy68.webp", },
  { id: "promos-xy-xy69", serieId: "prxy", name: "Rayquaza-EX", number: "XY69", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy69.webp", },
  { id: "promos-xy-xy70", serieId: "prxy", name: "Rexillius-EX", number: "XY70", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy70.webp", },
  { id: "promos-xy-xy71", serieId: "prxy", name: "Hoopa-EX", number: "XY71", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy71.webp", },
  { id: "promos-xy-xy72", serieId: "prxy", name: "Latios-EX", number: "XY72", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy72.webp", },
  { id: "promos-xy-xy73", serieId: "prxy", name: "Rayquaza-EX", number: "XY73", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy73.webp", },
  { id: "promos-xy-xy74", serieId: "prxy", name: "Reshiram", number: "XY74", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy74.webp", },
  { id: "promos-xy-xy75", serieId: "prxy", name: "Palkia", number: "XY75", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy75.webp", },
  { id: "promos-xy-xy76", serieId: "prxy", name: "Zekrom", number: "XY76", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy76.webp", },
  { id: "promos-xy-xy77", serieId: "prxy", name: "Dialga", number: "XY77", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy77.webp", },
  { id: "promos-xy-xy78", serieId: "prxy", name: "Latias", number: "XY78", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy78.webp", },
  { id: "promos-xy-xy79", serieId: "prxy", name: "Latios", number: "XY79", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy79.webp", },
  { id: "promos-xy-xy80", serieId: "prxy", name: "Kyurem Noir", number: "XY80", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy80.webp", },
  { id: "promos-xy-xy81", serieId: "prxy", name: "Kyurem Blanc", number: "XY81", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy81.webp", },
  { id: "promos-xy-xy82", serieId: "prxy", name: "Regigigas", number: "XY82", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy82.webp", },
  { id: "promos-xy-xy83", serieId: "prxy", name: "Arceus", number: "XY83", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy83.webp", },
  { id: "promos-xy-xy84", serieId: "prxy", name: "Pikachu-EX", number: "XY84", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy84.webp", },
  { id: "promos-xy-xy85", serieId: "prxy", name: "Hoopa-EX", number: "XY85", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy85.webp", },
  { id: "promos-xy-xy86", serieId: "prxy", name: "M-Braségali-EX", number: "XY86", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy86.webp", },
  { id: "promos-xy-xy87", serieId: "prxy", name: "M-Laggron-EX", number: "XY87", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy87.webp", },
  { id: "promos-xy-xy88", serieId: "prxy", name: "Marisson", number: "XY88", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy88.webp", },
  { id: "promos-xy-xy89", serieId: "prxy", name: "Pikachu", number: "XY89", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy89.webp", },
  { id: "promos-xy-xy90", serieId: "prxy", name: "Hoopa", number: "XY90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy90.webp", },
  { id: "promos-xy-xy91", serieId: "prxy", name: "Festival des Champions", number: "XY91", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy91.webp", },
  { id: "promos-xy-xy92", serieId: "prxy", name: "Ténéfix", number: "XY92", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy92.webp", },
  { id: "promos-xy-xy93", serieId: "prxy", name: "Celebi", number: "XY93", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy93.webp", },
  { id: "promos-xy-xy94", serieId: "prxy", name: "Desséliande", number: "XY94", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy94.webp", },
  { id: "promos-xy-xy95", serieId: "prxy", name: "Pikachu", number: "XY95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy95.webp", },
  { id: "promos-xy-xy96", serieId: "prxy", name: "Noctali", number: "XY96", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy96.webp", },
  { id: "promos-xy-xy97", serieId: "prxy", name: "Ptéra-EX", number: "XY97", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy97.webp", },
  { id: "promos-xy-xy98", serieId: "prxy", name: "M-Ptéra-EX", number: "XY98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy98.webp", },
  { id: "promos-xy-xy99", serieId: "prxy", name: "Lien Spirituel Ptéra", number: "XY99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy99.webp", },
  { id: "promos-xy-xy100", serieId: "prxy", name: "Mewtwo", number: "XY100", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy100.webp", },
  { id: "promos-xy-xy101", serieId: "prxy", name: "Mewtwo", number: "XY101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy101.webp", },
  { id: "promos-xy-xy102", serieId: "prxy", name: "Dragmara-EX", number: "XY102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy102.webp", },
  { id: "promos-xy-xy103", serieId: "prxy", name: "Mysdibule-EX", number: "XY103", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy103.webp", },
  { id: "promos-xy-xy104", serieId: "prxy", name: "M-Mysdibule-EX", number: "XY104", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy104.webp", },
  { id: "promos-xy-xy105", serieId: "prxy", name: "Lien Spirituel Mysdibule", number: "XY105", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy105.webp", },
  { id: "promos-xy-xy106", serieId: "prxy", name: "Léviator-EX", number: "XY106", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy106.webp", },
  { id: "promos-xy-xy107", serieId: "prxy", name: "Mewtwo-EX", number: "XY107", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy107.webp", },
  { id: "promos-xy-xy108", serieId: "prxy", name: "Mackogneur-EX", number: "XY108", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy108.webp", },
  { id: "promos-xy-xy109", serieId: "prxy", name: "Léviator", number: "XY109", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy109.webp", },
  { id: "promos-xy-xy110", serieId: "prxy", name: "Mew", number: "XY110", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy110.webp", },
  { id: "promos-xy-xy111", serieId: "prxy", name: "Celebi", number: "XY111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy111.webp", },
  { id: "promos-xy-xy112", serieId: "prxy", name: "Jirachi", number: "XY112", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy112.webp", },
  { id: "promos-xy-xy113", serieId: "prxy", name: "Manaphy", number: "XY113", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy113.webp", },
  { id: "promos-xy-xy114", serieId: "prxy", name: "Darkrai", number: "XY114", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy114.webp", },
  { id: "promos-xy-xy115", serieId: "prxy", name: "Shaymin", number: "XY115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy115.webp", },
  { id: "promos-xy-xy116", serieId: "prxy", name: "Arceus", number: "XY116", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy116.webp", },
  { id: "promos-xy-xy117", serieId: "prxy", name: "Victini", number: "XY117", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy117.webp", },
  { id: "promos-xy-xy118", serieId: "prxy", name: "Keldeo", number: "XY118", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy118.webp", },
  { id: "promos-xy-xy119", serieId: "prxy", name: "Genesect", number: "XY119", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy119.webp", },
  { id: "promos-xy-xy120", serieId: "prxy", name: "Meloetta", number: "XY120", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy120.webp", },
  { id: "promos-xy-xy121", serieId: "prxy", name: "Dracaufeu-EX", number: "XY121", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy121.webp", },
  { id: "promos-xy-xy122", serieId: "prxy", name: "Tortank-EX", number: "XY122", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy122.webp", },
  { id: "promos-xy-xy123", serieId: "prxy", name: "Florizarre-EX", number: "XY123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy123.webp", },
  { id: "promos-xy-xy124", serieId: "prxy", name: "Pikachu-EX", number: "XY124", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy124.webp", },
  { id: "promos-xy-xy125", serieId: "prxy", name: "Mewtwo-EX", number: "XY125", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy125.webp", },
  { id: "promos-xy-xy126", serieId: "prxy", name: "Mew-EX", number: "XY126", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy126.webp", },
  { id: "promos-xy-xy127", serieId: "prxy", name: "Sulfura", number: "XY127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy127.webp", },
  { id: "promos-xy-xy128", serieId: "prxy", name: "Kyurem Blanc", number: "XY128", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy128.webp", },
  { id: "promos-xy-xy129", serieId: "prxy", name: "Zygarde", number: "XY129", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy129.webp", },
  { id: "promos-xy-xy130", serieId: "prxy", name: "Tyranocif", number: "XY130", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy130.webp", },
  { id: "promos-xy-xy131", serieId: "prxy", name: "Flamajou", number: "XY131", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy131.webp", },
  { id: "promos-xy-xy132", serieId: "prxy", name: "Fantominus", number: "XY132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy132.webp", },
  { id: "promos-xy-xy133", serieId: "prxy", name: "Sachanobi-EX", number: "XY133", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy133.webp", },
  { id: "promos-xy-xy134", serieId: "prxy", name: "Pingoléon TURBO", number: "XY134", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy134.webp", },
  { id: "promos-xy-xy135", serieId: "prxy", name: "Neitram TURBO", number: "XY135", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy135.webp", },
  { id: "promos-xy-xy136", serieId: "prxy", name: "Noarfang TURBO", number: "XY136", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy136.webp", },
  { id: "promos-xy-xy137", serieId: "prxy", name: "Prismillon", number: "XY137", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy137.webp", },
  { id: "promos-xy-xy138", serieId: "prxy", name: "Grenousse", number: "XY138", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy138.webp", },
  { id: "promos-xy-xy139", serieId: "prxy", name: "Floette", number: "XY139", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy139.webp", },
  { id: "promos-xy-xy140", serieId: "prxy", name: "Lucario", number: "XY140", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy140.webp", },
  { id: "promos-xy-xy141", serieId: "prxy", name: "Rayquaza", number: "XY141", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy141.webp", },
  { id: "promos-xy-xy142", serieId: "prxy", name: "Créfadet", number: "XY142", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy142.webp", },
  { id: "promos-xy-xy143", serieId: "prxy", name: "Magicarpe", number: "XY143", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy143.webp", },
  { id: "promos-xy-xy144", serieId: "prxy", name: "Yanmega", number: "XY144", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy144.webp", },
  { id: "promos-xy-xy145", serieId: "prxy", name: "Volcanion", number: "XY145", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy145.webp", },
  { id: "promos-xy-xy146", serieId: "prxy", name: "Gamblast", number: "XY146", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy146.webp", },
  { id: "promos-xy-xy147", serieId: "prxy", name: "Hoopa", number: "XY147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy147.webp", },
  { id: "promos-xy-xy148", serieId: "prxy", name: "Shaymin-EX", number: "XY148", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy148.webp", },
  { id: "promos-xy-xy149", serieId: "prxy", name: "Xerneas-EX", number: "XY149", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy149.webp", },
  { id: "promos-xy-xy150", serieId: "prxy", name: "Yveltal-EX", number: "XY150", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy150.webp", },
  { id: "promos-xy-xy151", serieId: "prxy", name: "Zygarde-EX", number: "XY151", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy151.webp", },
  { id: "promos-xy-xy152", serieId: "prxy", name: "Zygarde", number: "XY152", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy152.webp", },
  { id: "promos-xy-xy153", serieId: "prxy", name: "Ho-Oh", number: "XY153", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy153.webp", },
  { id: "promos-xy-xy154", serieId: "prxy", name: "Ho-Oh TURBO", number: "XY154", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy154.webp", },
  { id: "promos-xy-xy155", serieId: "prxy", name: "Qulbutoké TURBO", number: "XY155", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy155.webp", },
  { id: "promos-xy-xy156", serieId: "prxy", name: "Lugia", number: "XY156", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy156.webp", },
  { id: "promos-xy-xy157", serieId: "prxy", name: "Dardargnan-EX", number: "XY157", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy157.webp", },
  { id: "promos-xy-xy158", serieId: "prxy", name: "M-Dardargnan-EX", number: "XY158", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy158.webp", },
  { id: "promos-xy-xy159", serieId: "prxy", name: "Lien Spirituel Dardargnan", number: "XY159", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy159.webp", },
  { id: "promos-xy-xy160", serieId: "prxy", name: "Kyurem Noir", number: "XY160", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy160.webp", },
  { id: "promos-xy-xy161", serieId: "prxy", name: "Roussil", number: "XY161", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy161.webp", },
  { id: "promos-xy-xy162", serieId: "prxy", name: "Amphinobi", number: "XY162", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy162.webp", },
  { id: "promos-xy-xy163", serieId: "prxy", name: "Smogogo", number: "XY163", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy163.webp", },
  { id: "promos-xy-xy164", serieId: "prxy", name: "Volcanion", number: "XY164", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy164.webp", },
  { id: "promos-xy-xy165", serieId: "prxy", name: "Magearna", number: "XY165", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy165.webp", },
  { id: "promos-xy-xy166", serieId: "prxy", name: "M-Ectoplasma-EX", number: "XY166", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy166.webp", },
  { id: "promos-xy-xy167", serieId: "prxy", name: "Carchacrok-EX", number: "XY167", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy167.webp", },
  { id: "promos-xy-xy168", serieId: "prxy", name: "M-Carchacrok-EX", number: "XY168", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy168.webp", },
  { id: "promos-xy-xy169", serieId: "prxy", name: "Lien Spirituel Carchacrok", number: "XY169", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy169.webp", },
  { id: "promos-xy-xy170", serieId: "prxy", name: "Drattak-EX", number: "XY170", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy170.webp", },
  { id: "promos-xy-xy171", serieId: "prxy", name: "M-Drattak-EX", number: "XY171", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy171.webp", },
  { id: "promos-xy-xy172", serieId: "prxy", name: "Lien Spirituel Drattak", number: "XY172", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy172.webp", },
  { id: "promos-xy-xy173", serieId: "prxy", name: "Volcanion-EX", number: "XY173", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy173.webp", },
  { id: "promos-xy-xy174", serieId: "prxy", name: "Pikachu-EX", number: "XY174", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy174.webp", },
  { id: "promos-xy-xy175", serieId: "prxy", name: "Magearna-EX", number: "XY175", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy175.webp", },
  { id: "promos-xy-xy176", serieId: "prxy", name: "Festival des Champions", number: "XY176", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy176.webp", },
  { id: "promos-xy-xy177", serieId: "prxy", name: "Karen", number: "XY177", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy177.webp", },
  { id: "promos-xy-xy178", serieId: "prxy", name: "Absol", number: "XY178", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy178.webp", },
  { id: "promos-xy-xy179", serieId: "prxy", name: "Ronflex", number: "XY179", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy179.webp", },
  { id: "promos-xy-xy180", serieId: "prxy", name: "Arcanin TURBO", number: "XY180", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy180.webp", },
  { id: "promos-xy-xy181", serieId: "prxy", name: "Nostenfer TURBO", number: "XY181", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy181.webp", },
  { id: "promos-xy-xy182", serieId: "prxy", name: "Vaututrice TURBO", number: "XY182", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy182.webp", },
  { id: "promos-xy-xy183", serieId: "prxy", name: "Mewtwo-EX", number: "XY183", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy183.webp", },
  { id: "promos-xy-xy184", serieId: "prxy", name: "Giratina", number: "XY184", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy184.webp", },
  { id: "promos-xy-xy185", serieId: "prxy", name: "Volcanion", number: "XY185", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy185.webp", },
  { id: "promos-xy-xy186", serieId: "prxy", name: "Magearna", number: "XY186", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy186.webp", },
  { id: "promos-xy-xy187", serieId: "prxy", name: "Celebi", number: "XY187", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy187.webp", },
  { id: "promos-xy-xy188", serieId: "prxy", name: "Shaymin", number: "XY188", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy188.webp", },
  { id: "promos-xy-xy189", serieId: "prxy", name: "Victini", number: "XY189", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy189.webp", },
  { id: "promos-xy-xy190", serieId: "prxy", name: "Manaphy", number: "XY190", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy190.webp", },
  { id: "promos-xy-xy191", serieId: "prxy", name: "Keldeo", number: "XY191", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy191.webp", },
  { id: "promos-xy-xy192", serieId: "prxy", name: "Mew", number: "XY192", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy192.webp", },
  { id: "promos-xy-xy193", serieId: "prxy", name: "Meloetta", number: "XY193", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy193.webp", },
  { id: "promos-xy-xy194", serieId: "prxy", name: "Darkrai", number: "XY194", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy194.webp", },
  { id: "promos-xy-xy195", serieId: "prxy", name: "Jirachi", number: "XY195", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy195.webp", },
  { id: "promos-xy-xy196", serieId: "prxy", name: "Genesect", number: "XY196", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy196.webp", },
  { id: "promos-xy-xy197", serieId: "prxy", name: "Arceus", number: "XY197", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy197.webp", },
  { id: "promos-xy-xy198", serieId: "prxy", name: "M-Camérupt-EX", number: "XY198", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy198.webp", },
  { id: "promos-xy-xy199", serieId: "prxy", name: "Lien Spirituel Camérupt", number: "XY199", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy199.webp", },
  { id: "promos-xy-xy200", serieId: "prxy", name: "M-Sharpedo-EX", number: "XY200", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy200.webp", },
  { id: "promos-xy-xy201", serieId: "prxy", name: "Lien Spirituel Sharpedo", number: "XY201", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy201.webp", },
  { id: "promos-xy-xy202", serieId: "prxy", name: "Pikachu", number: "XY202", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy202.webp", },
  { id: "promos-xy-xy203", serieId: "prxy", name: "Badge d'Arène", number: "XY203", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy203.webp", },
  { id: "promos-xy-xy204", serieId: "prxy", name: "Badge d'Arène", number: "XY204", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy204.webp", },
  { id: "promos-xy-xy205", serieId: "prxy", name: "Badge d'Arène", number: "XY205", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy205.webp", },
  { id: "promos-xy-xy206", serieId: "prxy", name: "Badge d'Arène", number: "XY206", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy206.webp", },
  { id: "promos-xy-xy207", serieId: "prxy", name: "Badge d'Arène", number: "XY207", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy207.webp", },
  { id: "promos-xy-xy208", serieId: "prxy", name: "Badge d'Arène", number: "XY208", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy208.webp", },
  { id: "promos-xy-xy209", serieId: "prxy", name: "Badge d'Arène", number: "XY209", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy209.webp", },
  { id: "promos-xy-xy210", serieId: "prxy", name: "Badge d'Arène", number: "XY210", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy210.webp", },
{ id: "promos-xy-xy211", serieId: "prxy", name: "Lien Spirituel Lucario", number: "XY211", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/PRXY/xy211.webp", },
}
