import type { Card } from "../../catalog";

const reverseVariant = { rarity: "Reverse", price: 1, stock: 0 } as const;
const rareReverseVariant = { rarity: "Rare Reverse", price: 1, stock: 0 } as const;

export const ADL_CARDS = [
  { id: "adl-001", serieId: "adl", name: "Melodelfe", number: "001/095", rarity: "Rare Holo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/1.webp", altVariant: rareReverseVariant },
  { id: "adl-002", serieId: "adl", name: "Deoxys", number: "002/095", rarity: "Rare Holo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/2.webp", altVariant: rareReverseVariant },
  { id: "adl-003", serieId: "adl", name: "Dialga", number: "003/095", rarity: "Rare Holo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/3.webp", altVariant: rareReverseVariant },
  { id: "adl-004", serieId: "adl", name: "Mentali", number: "004/095", rarity: "Rare Holo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/4.webp", altVariant: rareReverseVariant },
  { id: "adl-005", serieId: "adl", name: "Foretress", number: "005/095", rarity: "Rare Holo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/5.webp", altVariant: rareReverseVariant },
  { id: "adl-006", serieId: "adl", name: "Groudon", number: "006/095", rarity: "Rare Holo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/6.webp", altVariant: rareReverseVariant },
  { id: "adl-007", serieId: "adl", name: "Leviator", number: "007/095", rarity: "Rare Holo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/7.webp", altVariant: rareReverseVariant },
  { id: "adl-008", serieId: "adl", name: "Kapoera", number: "008/095", rarity: "Rare Holo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/8.webp", altVariant: rareReverseVariant },
  { id: "adl-009", serieId: "adl", name: "Ho-Oh", number: "009/095", rarity: "Rare Holo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/9.webp", altVariant: rareReverseVariant },
  { id: "adl-010", serieId: "adl", name: "Demolosse", number: "010/095", rarity: "Rare Holo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/10.webp", altVariant: rareReverseVariant },
  { id: "adl-011", serieId: "adl", name: "Jirachi", number: "011/095", rarity: "Rare Holo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/11.webp", altVariant: rareReverseVariant },
  { id: "adl-012", serieId: "adl", name: "Kyogre", number: "012/095", rarity: "Rare Holo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/12.webp", altVariant: rareReverseVariant },
  { id: "adl-013", serieId: "adl", name: "Phyllali", number: "013/095", rarity: "Rare Holo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/13.webp", altVariant: rareReverseVariant },
  { id: "adl-014", serieId: "adl", name: "Lucario", number: "014/095", rarity: "Rare Holo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/14.webp", altVariant: rareReverseVariant },
  { id: "adl-015", serieId: "adl", name: "Lugia", number: "015/095", rarity: "Rare Holo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/15.webp", altVariant: rareReverseVariant },
  { id: "adl-016", serieId: "adl", name: "Maganon", number: "016/095", rarity: "Rare Holo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/16.webp", altVariant: rareReverseVariant },
  { id: "adl-017", serieId: "adl", name: "Feunard", number: "017/095", rarity: "Rare Holo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/17.webp", altVariant: rareReverseVariant },
  { id: "adl-018", serieId: "adl", name: "Pachirisu", number: "018/095", rarity: "Rare Holo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/18.webp", altVariant: rareReverseVariant },
  { id: "adl-019", serieId: "adl", name: "Palkia", number: "019/095", rarity: "Rare Holo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/19.webp", altVariant: rareReverseVariant },
  { id: "adl-020", serieId: "adl", name: "Rayquaza", number: "020/095", rarity: "Rare Holo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/20.webp", altVariant: rareReverseVariant },
  { id: "adl-021", serieId: "adl", name: "Queulorior", number: "021/095", rarity: "Rare Holo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/21.webp", altVariant: rareReverseVariant },
  { id: "adl-022", serieId: "adl", name: "Noctali", number: "022/095", rarity: "Rare Holo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/22.webp", altVariant: rareReverseVariant },
  { id: "adl-023", serieId: "adl", name: "Pharamp", number: "023/095", rarity: "Rare Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/23.webp" },
  { id: "adl-024", serieId: "adl", name: "Melo", number: "024/095", rarity: "Rare Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/24.webp" },
  { id: "adl-025", serieId: "adl", name: "Aligatueur", number: "025/095", rarity: "Rare Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/25.webp" },
  { id: "adl-026", serieId: "adl", name: "Granbull", number: "026/095", rarity: "Rare Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/26.webp" },
  { id: "adl-027", serieId: "adl", name: "Meganium", number: "027/095", rarity: "Rare Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/27.webp" },
  { id: "adl-028", serieId: "adl", name: "Magireve", number: "028/095", rarity: "Rare Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/28.webp" },
  { id: "adl-029", serieId: "adl", name: "M. Mime", number: "029/095", rarity: "Rare Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/29.webp" },
  { id: "adl-030", serieId: "adl", name: "Roucarnage", number: "030/095", rarity: "Rare Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/30.webp" },
  { id: "adl-031", serieId: "adl", name: "Airmure", number: "031/095", rarity: "Rare Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/31.webp" },
  { id: "adl-032", serieId: "adl", name: "Roigada", number: "032/095", rarity: "Rare Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/32.webp" },
  { id: "adl-033", serieId: "adl", name: "Ronflex", number: "033/095", rarity: "Rare Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/33.webp" },
  { id: "adl-034", serieId: "adl", name: "Bouldeneu", number: "034/095", rarity: "Rare Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/34.webp" },
  { id: "adl-035", serieId: "adl", name: "Typhlosion", number: "035/095", rarity: "Rare Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/35.webp" },
  { id: "adl-036", serieId: "adl", name: "Debugant", number: "036/095", rarity: "Rare Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/36.webp" },
  { id: "adl-037", serieId: "adl", name: "Ursaring", number: "037/095", rarity: "Rare Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/37.webp" },
  { id: "adl-038", serieId: "adl", name: "Smogogo", number: "038/095", rarity: "Rare Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/38.webp" },
  { id: "adl-039", serieId: "adl", name: "Mangriff", number: "039/095", rarity: "Rare Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/39.webp" },
  { id: "adl-040", serieId: "adl", name: "Macronium", number: "040/095", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/40.webp" },
  { id: "adl-041", serieId: "adl", name: "Crocrodil", number: "041/095", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/41.webp" },
  { id: "adl-042", serieId: "adl", name: "Donphan", number: "042/095", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/42.webp" },
  { id: "adl-043", serieId: "adl", name: "Lainergie", number: "043/095", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/43.webp" },
  { id: "adl-044", serieId: "adl", name: "Pyroli", number: "044/095", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/44.webp" },
  { id: "adl-045", serieId: "adl", name: "Voltali", number: "045/095", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/45.webp" },
  { id: "adl-046", serieId: "adl", name: "Magby", number: "046/095", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/46.webp" },
  { id: "adl-047", serieId: "adl", name: "Mime Jr.", number: "047/095", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/47.webp" },
  { id: "adl-048", serieId: "adl", name: "Roucoups", number: "048/095", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/48.webp" },
  { id: "adl-049", serieId: "adl", name: "Feurisson", number: "049/095", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/49.webp" },
  { id: "adl-050", serieId: "adl", name: "Riolu", number: "050/095", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/50.webp" },
  { id: "adl-051", serieId: "adl", name: "Seviper", number: "051/095", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/51.webp" },
  { id: "adl-052", serieId: "adl", name: "Aquali", number: "052/095", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/52.webp" },
  { id: "adl-053", serieId: "adl", name: "Germignon", number: "053/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/53.webp", altVariant: reverseVariant },
  { id: "adl-054", serieId: "adl", name: "Melofee", number: "054/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/54.webp", altVariant: reverseVariant },
  { id: "adl-055", serieId: "adl", name: "Hericendre", number: "055/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/55.webp", altVariant: reverseVariant },
  { id: "adl-056", serieId: "adl", name: "Evoli", number: "056/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/56.webp", altVariant: reverseVariant },
  { id: "adl-057", serieId: "adl", name: "Tygnon", number: "057/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/57.webp", altVariant: reverseVariant },
  { id: "adl-058", serieId: "adl", name: "Kicklee", number: "058/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/58.webp", altVariant: reverseVariant },
  { id: "adl-059", serieId: "adl", name: "Malosse", number: "059/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/59.webp", altVariant: reverseVariant },
  { id: "adl-060", serieId: "adl", name: "Smogo", number: "060/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/60.webp", altVariant: reverseVariant },
  { id: "adl-061", serieId: "adl", name: "Magicarpe", number: "061/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/61.webp", altVariant: reverseVariant },
  { id: "adl-062", serieId: "adl", name: "Magmar", number: "062/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/62.webp", altVariant: reverseVariant },
  { id: "adl-063", serieId: "adl", name: "Wattouat", number: "063/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/63.webp", altVariant: reverseVariant },
  { id: "adl-064", serieId: "adl", name: "Mysdibule", number: "064/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/64.webp", altVariant: reverseVariant },
  { id: "adl-065", serieId: "adl", name: "Feuforeve", number: "065/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/65.webp", altVariant: reverseVariant },
  { id: "adl-066", serieId: "adl", name: "Phanpy", number: "066/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/66.webp", altVariant: reverseVariant },
  { id: "adl-067", serieId: "adl", name: "Roucool", number: "067/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/67.webp", altVariant: reverseVariant },
  { id: "adl-068", serieId: "adl", name: "Pomdepik", number: "068/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/68.webp", altVariant: reverseVariant },
  { id: "adl-069", serieId: "adl", name: "Relicanth", number: "069/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/69.webp", altVariant: reverseVariant },
  { id: "adl-070", serieId: "adl", name: "Ramoloss", number: "070/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/70.webp", altVariant: reverseVariant },
  { id: "adl-071", serieId: "adl", name: "Snubbull", number: "071/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/71.webp", altVariant: reverseVariant },
  { id: "adl-072", serieId: "adl", name: "Saquedeneu", number: "072/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/72.webp", altVariant: reverseVariant },
  { id: "adl-073", serieId: "adl", name: "Teddiursa", number: "073/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/73.webp", altVariant: reverseVariant },
  { id: "adl-074", serieId: "adl", name: "Kaiminus", number: "074/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/74.webp", altVariant: reverseVariant },
  { id: "adl-075", serieId: "adl", name: "Goupix", number: "075/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/75.webp", altVariant: reverseVariant },
  { id: "adl-076", serieId: "adl", name: "Encouragements hysteriques", number: "076/095", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/76.webp" },
  { id: "adl-077", serieId: "adl", name: "Copieuse", number: "077/095", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/77.webp" },
  { id: "adl-078", serieId: "adl", name: "Double boule", number: "078/095", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/78.webp" },
  { id: "adl-079", serieId: "adl", name: "Questionnaire d'interview", number: "079/095", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/79.webp" },
  { id: "adl-080", serieId: "adl", name: "Nettoyeur perdu", number: "080/095", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/80.webp" },
  { id: "adl-081", serieId: "adl", name: "Monde perdu", number: "081/095", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/81.webp" },
  { id: "adl-082", serieId: "adl", name: "Methode d'entrainement du Prof. Orme", number: "082/095", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/82.webp" },
  { id: "adl-083", serieId: "adl", name: "Nouvelle theorie du Prof. Chen", number: "083/095", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/83.webp" },
  { id: "adl-084", serieId: "adl", name: "Archive des recherches", number: "084/095", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/84.webp" },
  { id: "adl-085", serieId: "adl", name: "Entrainement de Sage", number: "085/095", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/85.webp" },
  { id: "adl-086", serieId: "adl", name: "Energie Obscurite", number: "086/095", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/86.webp" },
  { id: "adl-087", serieId: "adl", name: "Energie Metal", number: "087/095", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/87.webp" },
  { id: "adl-088", serieId: "adl", name: "Energie Plante", number: "088/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/88.webp", altVariant: reverseVariant },
  { id: "adl-089", serieId: "adl", name: "Energie Feu", number: "089/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/89.webp", altVariant: reverseVariant },
  { id: "adl-090", serieId: "adl", name: "Energie Eau", number: "090/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/90.webp", altVariant: reverseVariant },
  { id: "adl-091", serieId: "adl", name: "Energie Electrique", number: "091/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/91.webp", altVariant: reverseVariant },
  { id: "adl-092", serieId: "adl", name: "Energie Psy", number: "092/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/92.webp", altVariant: reverseVariant },
  { id: "adl-093", serieId: "adl", name: "Energie Combat", number: "093/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/93.webp", altVariant: reverseVariant },
  { id: "adl-094", serieId: "adl", name: "Energie Obscurite", number: "094/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/94.webp", altVariant: reverseVariant },
  { id: "adl-095", serieId: "adl", name: "Energie Metal", number: "095/095", rarity: "Commune", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/95.webp", altVariant: reverseVariant },
  { id: "adl-sl1", serieId: "adl", name: "Deoxys", number: "SL1", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/96.webp" },
  { id: "adl-sl2", serieId: "adl", name: "Dialga", number: "SL2", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/97.webp" },
  { id: "adl-sl3", serieId: "adl", name: "Entei", number: "SL3", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/98.webp" },
  { id: "adl-sl4", serieId: "adl", name: "Groudon", number: "SL4", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/99.webp" },
  { id: "adl-sl5", serieId: "adl", name: "Ho-Oh", number: "SL5", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/100.webp" },
  { id: "adl-sl6", serieId: "adl", name: "Kyogre", number: "SL6", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/101.webp" },
  { id: "adl-sl7", serieId: "adl", name: "Lugia", number: "SL7", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/102.webp" },
  { id: "adl-sl8", serieId: "adl", name: "Palkia", number: "SL8", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/103.webp" },
  { id: "adl-sl9", serieId: "adl", name: "Raikou", number: "SL9", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/104.webp" },
  { id: "adl-sl10", serieId: "adl", name: "Rayquaza", number: "SL10", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/105.webp" },
  { id: "adl-sl11", serieId: "adl", name: "Suicune", number: "SL11", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/adl/106.webp" },
] satisfies Card[];
