import type { Card } from "../../catalog";

export const HEARTGOLD_SOULSILVER_CARDS = [
{ id: "prhgss-001", serieId: "prhgss", name: "Ho-Oh", number: "HGSS01", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prhgss/1.webp", },
{ id: "prhgss-002", serieId: "prhgss", name: "Lugia", number: "HGSS02", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prhgss/2.webp", },
{ id: "prhgss-003", serieId: "prhgss", name: "Pikachu", number: "HGSS03", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prhgss/3.webp", },
{ id: "prhgss-004", serieId: "prhgss", name: "Qulbutoke", number: "HGSS04", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prhgss/4.webp", },
{ id: "prhgss-005", serieId: "prhgss", name: "Hoothoot", number: "HGSS05", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prhgss/5.webp", },
{ id: "prhgss-006", serieId: "prhgss", name: "Noarfang", number: "HGSS06", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prhgss/6.webp", },
{ id: "prhgss-007", serieId: "prhgss", name: "Aligatueur", number: "HGSS07", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prhgss/7.webp", },
{ id: "prhgss-008", serieId: "prhgss", name: "Meganium", number: "HGSS08", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prhgss/8.webp", },
{ id: "prhgss-009", serieId: "prhgss", name: "Typhlosion", number: "HGSS09", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prhgss/9.webp", },
{ id: "prhgss-010", serieId: "prhgss", name: "Latias", number: "HGSS10", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prhgss/10.webp", },
{ id: "prhgss-011", serieId: "prhgss", name: "Latios", number: "HGSS11", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prhgss/11.webp", },
{ id: "prhgss-012", serieId: "prhgss", name: "Melo", number: "HGSS12", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prhgss/12.webp", },
{ id: "prhgss-013", serieId: "prhgss", name: "Lippouti", number: "HGSS13", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prhgss/13.webp", },
{ id: "prhgss-014", serieId: "prhgss", name: "Lokhlass", number: "HGSS14", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prhgss/14.webp", },
{ id: "prhgss-015", serieId: "prhgss", name: "Caratroc", number: "HGSS15", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prhgss/15.webp", },
{ id: "prhgss-016", serieId: "prhgss", name: "Posipi", number: "HGSS16", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prhgss/16.webp", },
{ id: "prhgss-017", serieId: "prhgss", name: "Negapi", number: "HGSS17", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prhgss/17.webp", },
{ id: "prhgss-018", serieId: "prhgss", name: "Raz-de-marée tropical", number: "HGSS18", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prhgss/18.webp", },
{ id: "prhgss-019", serieId: "prhgss", name: "Raikou", number: "HGSS19", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prhgss/19.webp", },
{ id: "prhgss-020", serieId: "prhgss", name: "Entei", number: "HGSS20", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prhgss/20.webp", },
{ id: "prhgss-021", serieId: "prhgss", name: "Suicune", number: "HGSS21", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prhgss/21.webp", },
{ id: "prhgss-022", serieId: "prhgss", name: "Porygon", number: "HGSS22", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prhgss/22.webp", },
{ id: "prhgss-023", serieId: "prhgss", name: "Porygon2", number: "HGSS23", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prhgss/23.webp", },
{ id: "prhgss-024", serieId: "prhgss", name: "Tygnon", number: "HGSS24", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prhgss/24.webp", },
{ id: "prhgss-025", serieId: "prhgss", name: "Kicklee", number: "HGSS25", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prhgss/25.webp", },

//HGSS01
{ id: "hgss01-001", serieId: "HGSS01", name: "Arcanin", number: "001/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/1.webp", },
{ id: "hgss01-002", serieId: "HGSS01", name: "Azumarill", number: "002/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/2.webp", },
{ id: "hgss01-003", serieId: "HGSS01", name: "Mélodelfe", number: "003/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/3.webp", },
{ id: "hgss01-004", serieId: "HGSS01", name: "Léviator", number: "004/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/4.webp", },
{ id: "hgss01-005", serieId: "HGSS01", name: "Kapoera", number: "005/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/5.webp", },
{ id: "hgss01-006", serieId: "HGSS01", name: "Cotovol", number: "006/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/6.webp", },
{ id: "hgss01-007", serieId: "HGSS01", name: "Feunard", number: "007/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/7.webp", },
{ id: "hgss01-008", serieId: "HGSS01", name: "Noarfang", number: "008/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/8.webp", },
{ id: "hgss01-009", serieId: "HGSS01", name: "Maraiste", number: "009/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/9.webp", },
{ id: "hgss01-010", serieId: "HGSS01", name: "Raichu", number: "010/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/10.webp", },
{ id: "hgss01-011", serieId: "HGSS01", name: "Caratroc", number: "011/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/11.webp", },
{ id: "hgss01-012", serieId: "HGSS01", name: "Roigada", number: "012/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/12.webp", },
{ id: "hgss01-013", serieId: "HGSS01", name: "Qulbutoke", number: "013/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/13.webp", },
{ id: "hgss01-014", serieId: "HGSS01", name: "Pharamp", number: "014/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/14.webp", },
{ id: "hgss01-015", serieId: "HGSS01", name: "Migalos", number: "015/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/15.webp", },
{ id: "hgss01-016", serieId: "HGSS01", name: "Papilusion", number: "016/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/16.webp", },
{ id: "hgss01-017", serieId: "HGSS01", name: "Mélo", number: "017/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/17.webp", },
{ id: "hgss01-018", serieId: "HGSS01", name: "Noadkoko", number: "018/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/18.webp", },
{ id: "hgss01-019", serieId: "HGSS01", name: "Canarticho", number: "019/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/19.webp", },
{ id: "hgss01-020", serieId: "HGSS01", name: "Aligatueur", number: "020/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/20.webp", },
{ id: "hgss01-021", serieId: "HGSS01", name: "Fouinar", number: "021/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/21.webp", },
{ id: "hgss01-022", serieId: "HGSS01", name: "Granbull", number: "022/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/22.webp", },
{ id: "hgss01-023", serieId: "HGSS01", name: "Hypnomade", number: "023/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/23.webp", },
{ id: "hgss01-024", serieId: "HGSS01", name: "Lokhlass", number: "024/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/24.webp", },
{ id: "hgss01-025", serieId: "HGSS01", name: "Coxyclaque", number: "025/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/25.webp", },
{ id: "hgss01-026", serieId: "HGSS01", name: "Meganium", number: "026/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/26.webp", },
{ id: "hgss01-027", serieId: "HGSS01", name: "Persian", number: "027/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/27.webp", },
{ id: "hgss01-028", serieId: "HGSS01", name: "Pichu", number: "028/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/28.webp", },
{ id: "hgss01-029", serieId: "HGSS01", name: "Sablaireau", number: "029/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/29.webp", },
{ id: "hgss01-030", serieId: "HGSS01", name: "Lippouti", number: "030/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/30.webp", },
{ id: "hgss01-031", serieId: "HGSS01", name: "Heliatronc", number: "031/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/31.webp", },
{ id: "hgss01-032", serieId: "HGSS01", name: "Typhlosion", number: "032/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/32.webp", },
{ id: "hgss01-033", serieId: "HGSS01", name: "Debugant", number: "033/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/33.webp", },
{ id: "hgss01-034", serieId: "HGSS01", name: "Smogogo", number: "034/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/34.webp", },
{ id: "hgss01-035", serieId: "HGSS01", name: "Macronium", number: "035/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/35.webp", },
{ id: "hgss01-036", serieId: "HGSS01", name: "Leuphorie", number: "036/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/36.webp", },
{ id: "hgss01-037", serieId: "HGSS01", name: "Corayon", number: "037/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/37.webp", },
{ id: "hgss01-038", serieId: "HGSS01", name: "Crocodil", number: "038/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/38.webp", },
{ id: "hgss01-039", serieId: "HGSS01", name: "Cadoizo", number: "039/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/39.webp", },
{ id: "hgss01-040", serieId: "HGSS01", name: "Donphan", number: "040/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/40.webp", },
{ id: "hgss01-041", serieId: "HGSS01", name: "Insolourdo", number: "041/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/41.webp", },
{ id: "hgss01-042", serieId: "HGSS01", name: "Lainergie", number: "042/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/42.webp", },
{ id: "hgss01-043", serieId: "HGSS01", name: "Scarhino", number: "043/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/43.webp", },
{ id: "hgss01-044", serieId: "HGSS01", name: "Toudoudou", number: "044/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/44.webp", },
{ id: "hgss01-045", serieId: "HGSS01", name: "Demanta", number: "045/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/45.webp", },
{ id: "hgss01-046", serieId: "HGSS01", name: "Chrysacier", number: "046/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/46.webp", },
{ id: "hgss01-047", serieId: "HGSS01", name: "Écrémeuh", number: "047/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/47.webp", },
{ id: "hgss01-048", serieId: "HGSS01", name: "Parasect", number: "048/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/48.webp", },
{ id: "hgss01-049", serieId: "HGSS01", name: "Feurisson", number: "049/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/49.webp", },
{ id: "hgss01-050", serieId: "HGSS01", name: "Qwilfish", number: "050/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/50.webp", },
{ id: "hgss01-051", serieId: "HGSS01", name: "Floravol", number: "051/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/51.webp", },
{ id: "hgss01-052", serieId: "HGSS01", name: "Flagadoss", number: "052/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/52.webp", },
{ id: "hgss01-053", serieId: "HGSS01", name: "Staross", number: "053/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/53.webp", },
{ id: "hgss01-054", serieId: "HGSS01", name: "Zarbi", number: "054/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/54.webp", },
{ id: "hgss01-055", serieId: "HGSS01", name: "Zarbi", number: "055/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/55.webp", },
{ id: "hgss01-056", serieId: "HGSS01", name: "Grodoudou", number: "056/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/56.webp", },
{ id: "hgss01-057", serieId: "HGSS01", name: "Chenipan", number: "057/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/57.webp", },
{ id: "hgss01-058", serieId: "HGSS01", name: "Leveinard", number: "058/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/58.webp", },
{ id: "hgss01-059", serieId: "HGSS01", name: "Germignon", number: "059/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/59.webp", },
{ id: "hgss01-060", serieId: "HGSS01", name: "Mélofée", number: "060/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/60.webp", },
{ id: "hgss01-061", serieId: "HGSS01", name: "Héricendre", number: "061/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/61.webp", },
{ id: "hgss01-062", serieId: "HGSS01", name: "Soporifik", number: "062/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/62.webp", },
{ id: "hgss01-063", serieId: "HGSS01", name: "Noeunoeuf", number: "063/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/63.webp", },
{ id: "hgss01-064", serieId: "HGSS01", name: "Girafarig", number: "064/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/64.webp", },
{ id: "hgss01-065", serieId: "HGSS01", name: "Caninos", number: "065/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/65.webp", },
{ id: "hgss01-066", serieId: "HGSS01", name: "Hoothoot", number: "066/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/66.webp", },
{ id: "hgss01-067", serieId: "HGSS01", name: "Granivol", number: "067/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/67.webp", },
{ id: "hgss01-068", serieId: "HGSS01", name: "Rondoudou", number: "068/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/68.webp", },
{ id: "hgss01-069", serieId: "HGSS01", name: "Lippoutou", number: "069/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/69.webp", },
{ id: "hgss01-070", serieId: "HGSS01", name: "Smogo", number: "070/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/70.webp", },
{ id: "hgss01-071", serieId: "HGSS01", name: "Coxy", number: "071/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/71.webp", },
{ id: "hgss01-072", serieId: "HGSS01", name: "Magicarpe", number: "072/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/72.webp", },
{ id: "hgss01-073", serieId: "HGSS01", name: "Wattouat", number: "073/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/73.webp", },
{ id: "hgss01-074", serieId: "HGSS01", name: "Marill", number: "074/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/74.webp", },
{ id: "hgss01-075", serieId: "HGSS01", name: "Miaouss", number: "075/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/75.webp", },
{ id: "hgss01-076", serieId: "HGSS01", name: "Paras", number: "076/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/76.webp", },
{ id: "hgss01-077", serieId: "HGSS01", name: "Phanpy", number: "077/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/77.webp", },
{ id: "hgss01-078", serieId: "HGSS01", name: "Pikachu", number: "078/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/78.webp", },
{ id: "hgss01-079", serieId: "HGSS01", name: "Sabelette", number: "079/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/79.webp", },
{ id: "hgss01-080", serieId: "HGSS01", name: "Fouinette", number: "080/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/80.webp", },
{ id: "hgss01-081", serieId: "HGSS01", name: "Ramoloss", number: "081/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/81.webp", },
{ id: "hgss01-082", serieId: "HGSS01", name: "Snubbull", number: "082/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/82.webp", },
{ id: "hgss01-083", serieId: "HGSS01", name: "Mimigal", number: "083/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/83.webp", },
{ id: "hgss01-084", serieId: "HGSS01", name: "Stari", number: "084/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/84.webp", },
{ id: "hgss01-085", serieId: "HGSS01", name: "Tournegrin", number: "085/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/85.webp", },
{ id: "hgss01-086", serieId: "HGSS01", name: "Kaiminus", number: "086/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/86.webp", },
{ id: "hgss01-087", serieId: "HGSS01", name: "Goupix", number: "087/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/87.webp", },
{ id: "hgss01-088", serieId: "HGSS01", name: "Axoloto", number: "088/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/88.webp", },
{ id: "hgss01-089", serieId: "HGSS01", name: "Leo", number: "089/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/89.webp", },
{ id: "hgss01-090", serieId: "HGSS01", name: "Copieuse", number: "090/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/90.webp", },
{ id: "hgss01-091", serieId: "HGSS01", name: "Échange d'Énergie", number: "091/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/91.webp", },
{ id: "hgss01-092", serieId: "HGSS01", name: "Pêcheur", number: "092/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/92.webp", },
{ id: "hgss01-093", serieId: "HGSS01", name: "Énergie guérisseuse", number: "093/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/93.webp", },
{ id: "hgss01-094", serieId: "HGSS01", name: "Lait Meumeu", number: "094/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/94.webp", },
{ id: "hgss01-095", serieId: "HGSS01", name: "Poké Ball", number: "095/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/95.webp", },
{ id: "hgss01-096", serieId: "HGSS01", name: "Pokématos 3.0", number: "096/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/96.webp", },
{ id: "hgss01-097", serieId: "HGSS01", name: "Collectionneur de Pokémon", number: "097/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/97.webp", },
{ id: "hgss01-098", serieId: "HGSS01", name: "Communication Pokémon", number: "098/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/98.webp", },
{ id: "hgss01-099", serieId: "HGSS01", name: "Inversion de Pokémon", number: "099/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/99.webp", },
{ id: "hgss01-100", serieId: "HGSS01", name: "Méthode d'entraînement du Prof. Orme", number: "100/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/100.webp", },
{ id: "hgss01-101", serieId: "HGSS01", name: "Nouvelle théorie du Prof. Chen", number: "101/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/101.webp", },
{ id: "hgss01-102", serieId: "HGSS01", name: "Échange", number: "102/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/102.webp", },
{ id: "hgss01-103", serieId: "HGSS01", name: "Énergie doublement incolore", number: "103/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/103.webp", },
{ id: "hgss01-104", serieId: "HGSS01", name: "Énergie multicolore", number: "104/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/104.webp", },
{ id: "hgss01-105", serieId: "HGSS01", name: "Pharamp", number: "105/123", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/105.webp", },
{ id: "hgss01-106", serieId: "HGSS01", name: "Leuphorie", number: "106/123", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/106.webp", },
{ id: "hgss01-107", serieId: "HGSS01", name: "Donphan", number: "107/123", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/107.webp", },
{ id: "hgss01-108", serieId: "HGSS01", name: "Aligatueur", number: "108/123", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/108.webp", },
{ id: "hgss01-109", serieId: "HGSS01", name: "Meganium", number: "109/123", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/109.webp", },
{ id: "hgss01-110", serieId: "HGSS01", name: "Typhlosion", number: "110/123", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/110.webp", },
{ id: "hgss01-111", serieId: "HGSS01", name: "Ho-Oh", number: "111/123", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/111.webp", },
{ id: "hgss01-112", serieId: "HGSS01", name: "Ho-Oh", number: "112/123", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/112.webp", },
{ id: "hgss01-113", serieId: "HGSS01", name: "Lugia", number: "113/123", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/113.webp", },
{ id: "hgss01-114", serieId: "HGSS01", name: "Lugia", number: "114/123", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/114.webp", },
{ id: "hgss01-115", serieId: "HGSS01", name: "Énergie Plante", number: "115/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/115.webp", },
{ id: "hgss01-116", serieId: "HGSS01", name: "Énergie Feu", number: "116/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/116.webp", },
{ id: "hgss01-117", serieId: "HGSS01", name: "Énergie Eau", number: "117/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/117.webp", },
{ id: "hgss01-118", serieId: "HGSS01", name: "Énergie Électrique", number: "118/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/118.webp", },
{ id: "hgss01-119", serieId: "HGSS01", name: "Énergie Psy", number: "119/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/119.webp", },
{ id: "hgss01-120", serieId: "HGSS01", name: "Énergie Combat", number: "120/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/120.webp", },
{ id: "hgss01-121", serieId: "HGSS01", name: "Énergie Obscurité", number: "121/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/121.webp", },
{ id: "hgss01-122", serieId: "HGSS01", name: "Énergie Métal", number: "122/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/122.webp", },
{ id: "hgss01-123", serieId: "HGSS01", name: "Léviator", number: "123/123", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/123.webp", },
{ id: "hgss01-un", serieId: "HGSS01", name: "Lithographie d'Alpha", number: "UN", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS01/un.webp", },

//HGSS02
{ id: "hgss02-001", serieId: "HGSS02", name: "Jirachi", number: "001/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/1.webp", },
{ id: "hgss02-002", serieId: "HGSS02", name: "Maganon", number: "002/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/2.webp", },
{ id: "hgss02-003", serieId: "HGSS02", name: "Manaphy", number: "003/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/3.webp", },
{ id: "hgss02-004", serieId: "HGSS02", name: "Metalosse", number: "004/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/4.webp", },
{ id: "hgss02-005", serieId: "HGSS02", name: "Magirêve", number: "005/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/5.webp", },
{ id: "hgss02-006", serieId: "HGSS02", name: "Octillery", number: "006/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/6.webp", },
{ id: "hgss02-007", serieId: "HGSS02", name: "Tarpaud", number: "007/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/7.webp", },
{ id: "hgss02-008", serieId: "HGSS02", name: "Shaymin", number: "008/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/8.webp", },
{ id: "hgss02-009", serieId: "HGSS02", name: "Simularbre", number: "009/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/9.webp", },
{ id: "hgss02-010", serieId: "HGSS02", name: "Torterra", number: "010/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/10.webp", },
{ id: "hgss02-011", serieId: "HGSS02", name: "Xatu", number: "011/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/11.webp", },
{ id: "hgss02-012", serieId: "HGSS02", name: "Dardargnan", number: "012/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/12.webp", },
{ id: "hgss02-013", serieId: "HGSS02", name: "Tortank", number: "013/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/13.webp", },
{ id: "hgss02-014", serieId: "HGSS02", name: "Nostenfer", number: "014/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/14.webp", },
{ id: "hgss02-015", serieId: "HGSS02", name: "Rapasdepic", number: "015/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/15.webp", },
{ id: "hgss02-016", serieId: "HGSS02", name: "Mustéflott", number: "016/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/16.webp", },
{ id: "hgss02-017", serieId: "HGSS02", name: "Hyporoi", number: "017/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/17.webp", },
{ id: "hgss02-018", serieId: "HGSS02", name: "Lanturn", number: "018/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/18.webp", },
{ id: "hgss02-019", serieId: "HGSS02", name: "Lucario", number: "019/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/19.webp", },
{ id: "hgss02-020", serieId: "HGSS02", name: "Feunard", number: "020/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/20.webp", },
{ id: "hgss02-021", serieId: "HGSS02", name: "Tartard", number: "021/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/21.webp", },
{ id: "hgss02-022", serieId: "HGSS02", name: "Colossinge", number: "022/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/22.webp", },
{ id: "hgss02-023", serieId: "HGSS02", name: "Roserade", number: "023/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/23.webp", },
{ id: "hgss02-024", serieId: "HGSS02", name: "Steelix", number: "024/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/24.webp", },
{ id: "hgss02-025", serieId: "HGSS02", name: "Chartor", number: "025/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/25.webp", },
{ id: "hgss02-026", serieId: "HGSS02", name: "Tyranocif", number: "026/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/26.webp", },
{ id: "hgss02-027", serieId: "HGSS02", name: "Ursaring", number: "027/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/27.webp", },
{ id: "hgss02-028", serieId: "HGSS02", name: "Ceriflor", number: "028/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/28.webp", },
{ id: "hgss02-029", serieId: "HGSS02", name: "Insolourdo", number: "029/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/29.webp", },
{ id: "hgss02-030", serieId: "HGSS02", name: "Nosferalto", number: "030/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/30.webp", },
{ id: "hgss02-031", serieId: "HGSS02", name: "Boskara", number: "031/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/31.webp", },
{ id: "hgss02-032", serieId: "HGSS02", name: "Coconfort", number: "032/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/32.webp", },
{ id: "hgss02-033", serieId: "HGSS02", name: "Metang", number: "033/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/33.webp", },
{ id: "hgss02-034", serieId: "HGSS02", name: "Negapi", number: "034/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/34.webp", },
{ id: "hgss02-035", serieId: "HGSS02", name: "Chamallot", number: "035/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/35.webp", },
{ id: "hgss02-036", serieId: "HGSS02", name: "Posipi", number: "036/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/36.webp", },
{ id: "hgss02-037", serieId: "HGSS02", name: "Tetarte", number: "037/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/37.webp", },
{ id: "hgss02-038", serieId: "HGSS02", name: "Ymphect", number: "038/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/38.webp", },
{ id: "hgss02-039", serieId: "HGSS02", name: "Ymphect", number: "039/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/39.webp", },
{ id: "hgss02-040", serieId: "HGSS02", name: "Hypocean", number: "040/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/40.webp", },
{ id: "hgss02-041", serieId: "HGSS02", name: "Tauros", number: "041/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/41.webp", },
{ id: "hgss02-042", serieId: "HGSS02", name: "Carabaffe", number: "042/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/42.webp", },
{ id: "hgss02-043", serieId: "HGSS02", name: "Capumain", number: "043/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/43.webp", },
{ id: "hgss02-044", serieId: "HGSS02", name: "Terhal", number: "044/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/44.webp", },
{ id: "hgss02-045", serieId: "HGSS02", name: "Mustébouée", number: "045/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/45.webp", },
{ id: "hgss02-046", serieId: "HGSS02", name: "Vortente", number: "046/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/46.webp", },
{ id: "hgss02-047", serieId: "HGSS02", name: "Ceribou", number: "047/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/47.webp", },
{ id: "hgss02-048", serieId: "HGSS02", name: "Loupio", number: "048/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/48.webp", },
{ id: "hgss02-049", serieId: "HGSS02", name: "Hypotrempe", number: "049/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/49.webp", },
{ id: "hgss02-050", serieId: "HGSS02", name: "Embrylex", number: "050/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/50.webp", },
{ id: "hgss02-051", serieId: "HGSS02", name: "Embrylex", number: "051/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/51.webp", },
{ id: "hgss02-052", serieId: "HGSS02", name: "Magmar", number: "052/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/52.webp", },
{ id: "hgss02-053", serieId: "HGSS02", name: "Férosinge", number: "053/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/53.webp", },
{ id: "hgss02-054", serieId: "HGSS02", name: "Feuforêve", number: "054/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/54.webp", },
{ id: "hgss02-055", serieId: "HGSS02", name: "Natu", number: "055/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/55.webp", },
{ id: "hgss02-056", serieId: "HGSS02", name: "Onix", number: "056/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/56.webp", },
{ id: "hgss02-057", serieId: "HGSS02", name: "Onix", number: "057/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/57.webp", },
{ id: "hgss02-058", serieId: "HGSS02", name: "Ptitard", number: "058/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/58.webp", },
{ id: "hgss02-059", serieId: "HGSS02", name: "Remoraid", number: "059/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/59.webp", },
{ id: "hgss02-060", serieId: "HGSS02", name: "Riolu", number: "060/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/60.webp", },
{ id: "hgss02-061", serieId: "HGSS02", name: "Roselia", number: "061/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/61.webp", },
{ id: "hgss02-062", serieId: "HGSS02", name: "Piafabec", number: "062/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/62.webp", },
{ id: "hgss02-063", serieId: "HGSS02", name: "Carapuce", number: "063/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/63.webp", },
{ id: "hgss02-064", serieId: "HGSS02", name: "Cerfrousse", number: "064/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/64.webp", },
{ id: "hgss02-065", serieId: "HGSS02", name: "Teddiursa", number: "065/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/65.webp", },
{ id: "hgss02-066", serieId: "HGSS02", name: "Tropius", number: "066/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/66.webp", },
{ id: "hgss02-067", serieId: "HGSS02", name: "Tortipouss", number: "067/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/67.webp", },
{ id: "hgss02-068", serieId: "HGSS02", name: "Goupix", number: "068/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/68.webp", },
{ id: "hgss02-069", serieId: "HGSS02", name: "Aspicot", number: "069/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/69.webp", },
{ id: "hgss02-070", serieId: "HGSS02", name: "Nosferapti", number: "070/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/70.webp", },
{ id: "hgss02-071", serieId: "HGSS02", name: "Encouragements hystériques", number: "071/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/71.webp", },
{ id: "hgss02-072", serieId: "HGSS02", name: "Double boule", number: "072/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/72.webp", },
{ id: "hgss02-073", serieId: "HGSS02", name: "Bavardage du maître", number: "073/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/73.webp", },
{ id: "hgss02-074", serieId: "HGSS02", name: "Récupérateur d'énergie", number: "074/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/74.webp", },
{ id: "hgss02-075", serieId: "HGSS02", name: "Réglages techniques", number: "075/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/75.webp", },
{ id: "hgss02-076", serieId: "HGSS02", name: "Bonne canne", number: "076/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/76.webp", },
{ id: "hgss02-077", serieId: "HGSS02", name: "Questionnaire d'interview", number: "077/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/77.webp", },
{ id: "hgss02-078", serieId: "HGSS02", name: "Juge", number: "078/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/78.webp", },
{ id: "hgss02-079", serieId: "HGSS02", name: "Herbe sauveuse", number: "079/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/79.webp", },
{ id: "hgss02-080", serieId: "HGSS02", name: "PlusPower", number: "080/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/80.webp", },
{ id: "hgss02-081", serieId: "HGSS02", name: "Circulateur de Pokémon", number: "081/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/81.webp", },
{ id: "hgss02-082", serieId: "HGSS02", name: "Super bonbon", number: "082/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/82.webp", },
{ id: "hgss02-083", serieId: "HGSS02", name: "Super rappel", number: "083/95", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/83.webp", },
{ id: "hgss02-084", serieId: "HGSS02", name: "Nostenfer", number: "084/95", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/84.webp", },
{ id: "hgss02-085", serieId: "HGSS02", name: "Hyporoi", number: "085/95", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/85.webp", },
{ id: "hgss02-086", serieId: "HGSS02", name: "Lanturn", number: "086/95", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/86.webp", },
{ id: "hgss02-087", serieId: "HGSS02", name: "Steelix", number: "087/95", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/87.webp", },
{ id: "hgss02-088", serieId: "HGSS02", name: "Tyranocif", number: "088/95", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/88.webp", },
{ id: "hgss02-089", serieId: "HGSS02", name: "Ursaring", number: "089/95", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/89.webp", },
{ id: "hgss02-090", serieId: "HGSS02", name: "Entei & Raikou", number: "090/95", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/90.webp", },
{ id: "hgss02-091", serieId: "HGSS02", name: "Entei & Raikou", number: "091/95", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/91.webp", },
{ id: "hgss02-092", serieId: "HGSS02", name: "Raikou & Suicune", number: "092/95", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/92.webp", },
{ id: "hgss02-093", serieId: "HGSS02", name: "Raikou & Suicune", number: "093/95", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/93.webp", },
{ id: "hgss02-094", serieId: "HGSS02", name: "Suicune & Entei", number: "094/95", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/94.webp", },
{ id: "hgss02-095", serieId: "HGSS02", name: "Suicune & Entei", number: "095/95", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/95.webp", },
{ id: "hgss02-deux", serieId: "HGSS02", name: "Lithographie d'Alpha", number: "DEUX", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS02/deux.webp", },


// HGSS03 - Indomptable
{ id: "hgss03-001", serieId: "HGSS03", name: "Joliflor", number: "001/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/1.webp", },
{ id: "hgss03-002", serieId: "HGSS03", name: "Mentali", number: "002/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/2.webp", },
{ id: "hgss03-003", serieId: "HGSS03", name: "Foretress", number: "003/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/3.webp", },
{ id: "hgss03-004", serieId: "HGSS03", name: "Scorvol", number: "004/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/4.webp", },
{ id: "hgss03-005", serieId: "HGSS03", name: "Démolosse", number: "005/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/5.webp", },
{ id: "hgss03-006", serieId: "HGSS03", name: "Volcaropod", number: "006/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/6.webp", },
{ id: "hgss03-007", serieId: "HGSS03", name: "Cizayox", number: "007/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/7.webp", },
{ id: "hgss03-008", serieId: "HGSS03", name: "Queulorior", number: "008/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/8.webp", },
{ id: "hgss03-009", serieId: "HGSS03", name: "Togekiss", number: "009/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/9.webp", },
{ id: "hgss03-010", serieId: "HGSS03", name: "Noctali", number: "010/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/10.webp", },
{ id: "hgss03-011", serieId: "HGSS03", name: "Dodrio", number: "011/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/11.webp", },
{ id: "hgss03-012", serieId: "HGSS03", name: "Grodrive", number: "012/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/12.webp", },
{ id: "hgss03-013", serieId: "HGSS03", name: "Foretress", number: "013/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/13.webp", },
{ id: "hgss03-014", serieId: "HGSS03", name: "Hariyama", number: "014/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/14.webp", },
{ id: "hgss03-015", serieId: "HGSS03", name: "Corboss", number: "015/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/15.webp", },
{ id: "hgss03-016", serieId: "HGSS03", name: "Corboss", number: "016/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/16.webp", },
{ id: "hgss03-017", serieId: "HGSS03", name: "Phyllali", number: "017/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/17.webp", },
{ id: "hgss03-018", serieId: "HGSS03", name: "Metalosse", number: "018/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/18.webp", },
{ id: "hgss03-019", serieId: "HGSS03", name: "Magirêve", number: "019/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/19.webp", },
{ id: "hgss03-020", serieId: "HGSS03", name: "Motisma", number: "020/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/20.webp", },
{ id: "hgss03-021", serieId: "HGSS03", name: "Airmure", number: "021/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/21.webp", },
{ id: "hgss03-022", serieId: "HGSS03", name: "Tropius", number: "022/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/22.webp", },
{ id: "hgss03-023", serieId: "HGSS03", name: "Apireine", number: "023/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/23.webp", },
{ id: "hgss03-024", serieId: "HGSS03", name: "Rafflesia", number: "024/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/24.webp", },
{ id: "hgss03-025", serieId: "HGSS03", name: "Dimoret", number: "025/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/25.webp", },
{ id: "hgss03-026", serieId: "HGSS03", name: "Pyroli", number: "026/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/26.webp", },
{ id: "hgss03-027", serieId: "HGSS03", name: "Ortide", number: "027/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/27.webp", },
{ id: "hgss03-028", serieId: "HGSS03", name: "Voltali", number: "028/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/28.webp", },
{ id: "hgss03-029", serieId: "HGSS03", name: "Galegon", number: "029/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/29.webp", },
{ id: "hgss03-030", serieId: "HGSS03", name: "Metang", number: "030/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/30.webp", },
{ id: "hgss03-031", serieId: "HGSS03", name: "Grotadmorv", number: "031/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/31.webp", },
{ id: "hgss03-032", serieId: "HGSS03", name: "Scarabrute", number: "032/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/32.webp", },
{ id: "hgss03-033", serieId: "HGSS03", name: "Raichu", number: "033/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/33.webp", },
{ id: "hgss03-034", serieId: "HGSS03", name: "Rattatac", number: "034/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/34.webp", },
{ id: "hgss03-035", serieId: "HGSS03", name: "Tenefix", number: "035/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/35.webp", },
{ id: "hgss03-036", serieId: "HGSS03", name: "Insécateur", number: "036/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/36.webp", },
{ id: "hgss03-037", serieId: "HGSS03", name: "Moufflair", number: "037/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/37.webp", },
{ id: "hgss03-038", serieId: "HGSS03", name: "Flagadoss", number: "038/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/38.webp", },
{ id: "hgss03-039", serieId: "HGSS03", name: "Togetic", number: "039/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/39.webp", },
{ id: "hgss03-040", serieId: "HGSS03", name: "Zarbi", number: "040/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/40.webp", },
{ id: "hgss03-041", serieId: "HGSS03", name: "Aquali", number: "041/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/41.webp", },
{ id: "hgss03-042", serieId: "HGSS03", name: "Galekid", number: "042/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/42.webp", },
{ id: "hgss03-043", serieId: "HGSS03", name: "Terhal", number: "043/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/43.webp", },
{ id: "hgss03-044", serieId: "HGSS03", name: "Apitrini", number: "044/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/44.webp", },
{ id: "hgss03-045", serieId: "HGSS03", name: "Doduo", number: "045/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/45.webp", },
{ id: "hgss03-046", serieId: "HGSS03", name: "Baudrive", number: "046/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/46.webp", },
{ id: "hgss03-047", serieId: "HGSS03", name: "Evoli", number: "047/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/47.webp", },
{ id: "hgss03-048", serieId: "HGSS03", name: "Evoli", number: "048/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/48.webp", },
{ id: "hgss03-049", serieId: "HGSS03", name: "Scorplane", number: "049/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/49.webp", },
{ id: "hgss03-050", serieId: "HGSS03", name: "Tadmorv", number: "050/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/50.webp", },
{ id: "hgss03-051", serieId: "HGSS03", name: "Tygnon", number: "051/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/51.webp", },
{ id: "hgss03-052", serieId: "HGSS03", name: "Kicklee", number: "052/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/52.webp", },
{ id: "hgss03-053", serieId: "HGSS03", name: "Malosse", number: "053/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/53.webp", },
{ id: "hgss03-054", serieId: "HGSS03", name: "Malosse", number: "054/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/54.webp", },
{ id: "hgss03-055", serieId: "HGSS03", name: "Makuhita", number: "055/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/55.webp", },
{ id: "hgss03-056", serieId: "HGSS03", name: "Mysdibule", number: "056/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/56.webp", },
{ id: "hgss03-057", serieId: "HGSS03", name: "Feuforêve", number: "057/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/57.webp", },
{ id: "hgss03-058", serieId: "HGSS03", name: "Cornèbre", number: "058/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/58.webp", },
{ id: "hgss03-059", serieId: "HGSS03", name: "Cornèbre", number: "059/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/59.webp", },
{ id: "hgss03-060", serieId: "HGSS03", name: "Mystherbe", number: "060/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/60.webp", },
{ id: "hgss03-061", serieId: "HGSS03", name: "Pikachu", number: "061/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/61.webp", },
{ id: "hgss03-062", serieId: "HGSS03", name: "Pomdepik", number: "062/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/62.webp", },
{ id: "hgss03-063", serieId: "HGSS03", name: "Pomdepik", number: "063/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/63.webp", },
{ id: "hgss03-064", serieId: "HGSS03", name: "Rattata", number: "064/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/64.webp", },
{ id: "hgss03-065", serieId: "HGSS03", name: "Insécateur", number: "065/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/65.webp", },
{ id: "hgss03-066", serieId: "HGSS03", name: "Ramoloss", number: "066/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/66.webp", },
{ id: "hgss03-067", serieId: "HGSS03", name: "Limagma", number: "067/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/67.webp", },
{ id: "hgss03-068", serieId: "HGSS03", name: "Farfuret", number: "068/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/68.webp", },
{ id: "hgss03-069", serieId: "HGSS03", name: "Moufouette", number: "069/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/69.webp", },
{ id: "hgss03-070", serieId: "HGSS03", name: "Togepi", number: "070/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/70.webp", },
{ id: "hgss03-071", serieId: "HGSS03", name: "Tour Cendrée", number: "071/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/71.webp", },
{ id: "hgss03-072", serieId: "HGSS03", name: "Défenseur", number: "072/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/72.webp", },
{ id: "hgss03-073", serieId: "HGSS03", name: "Chang'Énergie", number: "073/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/73.webp", },
{ id: "hgss03-074", serieId: "HGSS03", name: "Fleuriste", number: "074/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/74.webp", },
{ id: "hgss03-075", serieId: "HGSS03", name: "Boîte légendaire", number: "075/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/75.webp", },
{ id: "hgss03-076", serieId: "HGSS03", name: "Ruines d'Alpha", number: "076/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/76.webp", },
{ id: "hgss03-077", serieId: "HGSS03", name: "Entraînement de Sage", number: "077/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/77.webp", },
{ id: "hgss03-078", serieId: "HGSS03", name: "Fourberie de la Team Rocket", number: "078/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/78.webp", },
{ id: "hgss03-079", serieId: "HGSS03", name: "Énergie Obscurité", number: "079/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/79.webp", },
{ id: "hgss03-080", serieId: "HGSS03", name: "Énergie Métal", number: "080/90", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/80.webp", },
{ id: "hgss03-081", serieId: "HGSS03", name: "Mentali", number: "081/90", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/81.webp", },
{ id: "hgss03-082", serieId: "HGSS03", name: "Démolosse", number: "082/90", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/82.webp", },
{ id: "hgss03-083", serieId: "HGSS03", name: "Raichu", number: "083/90", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/83.webp", },
{ id: "hgss03-084", serieId: "HGSS03", name: "Cizayox", number: "084/90", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/84.webp", },
{ id: "hgss03-085", serieId: "HGSS03", name: "Roigada", number: "085/90", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/85.webp", },
{ id: "hgss03-086", serieId: "HGSS03", name: "Noctali", number: "086/90", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/86.webp", },
{ id: "hgss03-087", serieId: "HGSS03", name: "Kyogre & Groudon", number: "087/90", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/87.webp", },
{ id: "hgss03-088", serieId: "HGSS03", name: "Kyogre & Groudon", number: "088/90", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/88.webp", },
{ id: "hgss03-089", serieId: "HGSS03", name: "Rayquaza & Deoxys", number: "089/90", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/89.webp", },
{ id: "hgss03-090", serieId: "HGSS03", name: "Rayquaza & Deoxys", number: "090/90", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/90.webp", },
{ id: "hgss03-trois", serieId: "HGSS03", name: "Lithographie d'Alpha", number: "TROIS", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS03/trois.webp", },

// HGSS04 - Triomphe
{ id: "hgss04-001", serieId: "HGSS04", name: "Galeking", number: "001/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/1.webp", },
{ id: "hgss04-002", serieId: "HGSS04", name: "Altaria", number: "002/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/2.webp", },
{ id: "hgss04-003", serieId: "HGSS04", name: "Celebi", number: "003/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/3.webp", },
{ id: "hgss04-004", serieId: "HGSS04", name: "Drascore", number: "004/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/4.webp", },
{ id: "hgss04-005", serieId: "HGSS04", name: "Mammochon", number: "005/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/5.webp", },
{ id: "hgss04-006", serieId: "HGSS04", name: "Nidoking", number: "006/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/6.webp", },
{ id: "hgss04-007", serieId: "HGSS04", name: "Porygon-Z", number: "007/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/7.webp", },
{ id: "hgss04-008", serieId: "HGSS04", name: "Galopa", number: "008/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/8.webp", },
{ id: "hgss04-009", serieId: "HGSS04", name: "Solaroc", number: "009/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/9.webp", },
{ id: "hgss04-010", serieId: "HGSS04", name: "Spiritomb", number: "010/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/10.webp", },
{ id: "hgss04-011", serieId: "HGSS04", name: "Aéromite", number: "011/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/11.webp", },
{ id: "hgss04-012", serieId: "HGSS04", name: "Empiflor", number: "012/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/12.webp", },
{ id: "hgss04-013", serieId: "HGSS04", name: "Capidextre", number: "013/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/13.webp", },
{ id: "hgss04-014", serieId: "HGSS04", name: "Branette", number: "014/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/14.webp", },
{ id: "hgss04-015", serieId: "HGSS04", name: "Archéodong", number: "015/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/15.webp", },
{ id: "hgss04-016", serieId: "HGSS04", name: "Vortente", number: "016/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/16.webp", },
{ id: "hgss04-017", serieId: "HGSS04", name: "Metamorph", number: "017/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/17.webp", },
{ id: "hgss04-018", serieId: "HGSS04", name: "Dracolosse", number: "018/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/18.webp", },
{ id: "hgss04-019", serieId: "HGSS04", name: "Triopikeur", number: "019/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/19.webp", },
{ id: "hgss04-020", serieId: "HGSS04", name: "Elekable", number: "020/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/20.webp", },
{ id: "hgss04-021", serieId: "HGSS04", name: "Elekid", number: "021/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/21.webp", },
{ id: "hgss04-022", serieId: "HGSS04", name: "Akwakwak", number: "022/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/22.webp", },
{ id: "hgss04-023", serieId: "HGSS04", name: "Groret", number: "023/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/23.webp", },
{ id: "hgss04-024", serieId: "HGSS04", name: "Mélokrik", number: "024/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/24.webp", },
{ id: "hgss04-025", serieId: "HGSS04", name: "Seleroc", number: "025/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/25.webp", },
{ id: "hgss04-026", serieId: "HGSS04", name: "Mackogneur", number: "026/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/26.webp", },
{ id: "hgss04-027", serieId: "HGSS04", name: "Maganon", number: "027/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/27.webp", },
{ id: "hgss04-028", serieId: "HGSS04", name: "Nidoqueen", number: "028/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/28.webp", },
{ id: "hgss04-029", serieId: "HGSS04", name: "Roucarnage", number: "029/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/29.webp", },
{ id: "hgss04-030", serieId: "HGSS04", name: "Sharpedo", number: "030/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/30.webp", },
{ id: "hgss04-031", serieId: "HGSS04", name: "Wailord", number: "031/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/31.webp", },
{ id: "hgss04-032", serieId: "HGSS04", name: "Draco", number: "032/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/32.webp", },
{ id: "hgss04-033", serieId: "HGSS04", name: "Elektek", number: "033/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/33.webp", },
{ id: "hgss04-034", serieId: "HGSS04", name: "Electrode", number: "034/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/34.webp", },
{ id: "hgss04-035", serieId: "HGSS04", name: "Spectrum", number: "035/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/35.webp", },
{ id: "hgss04-036", serieId: "HGSS04", name: "Kangourex", number: "036/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/36.webp", },
{ id: "hgss04-037", serieId: "HGSS04", name: "Galegon", number: "037/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/37.webp", },
{ id: "hgss04-038", serieId: "HGSS04", name: "Coudlangue", number: "038/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/38.webp", },
{ id: "hgss04-039", serieId: "HGSS04", name: "Lovdisc", number: "039/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/39.webp", },
{ id: "hgss04-040", serieId: "HGSS04", name: "Machopeur", number: "040/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/40.webp", },
{ id: "hgss04-041", serieId: "HGSS04", name: "Magby", number: "041/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/41.webp", },
{ id: "hgss04-042", serieId: "HGSS04", name: "Magmar", number: "042/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/42.webp", },
{ id: "hgss04-043", serieId: "HGSS04", name: "Magneton", number: "043/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/43.webp", },
{ id: "hgss04-044", serieId: "HGSS04", name: "Ossatueur", number: "044/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/44.webp", },
{ id: "hgss04-045", serieId: "HGSS04", name: "Nidorina", number: "045/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/45.webp", },
{ id: "hgss04-046", serieId: "HGSS04", name: "Nidorino", number: "046/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/46.webp", },
{ id: "hgss04-047", serieId: "HGSS04", name: "Roucoups", number: "047/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/47.webp", },
{ id: "hgss04-048", serieId: "HGSS04", name: "Cochignon", number: "048/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/48.webp", },
{ id: "hgss04-049", serieId: "HGSS04", name: "Porygon2", number: "049/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/49.webp", },
{ id: "hgss04-050", serieId: "HGSS04", name: "Tentacruel", number: "050/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/50.webp", },
{ id: "hgss04-051", serieId: "HGSS04", name: "Zarbi", number: "051/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/51.webp", },
{ id: "hgss04-052", serieId: "HGSS04", name: "Wailmer", number: "052/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/52.webp", },
{ id: "hgss04-053", serieId: "HGSS04", name: "Boustiflor", number: "053/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/53.webp", },
{ id: "hgss04-054", serieId: "HGSS04", name: "Yanmega", number: "054/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/54.webp", },
{ id: "hgss04-055", serieId: "HGSS04", name: "Capumain", number: "055/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/55.webp", },
{ id: "hgss04-056", serieId: "HGSS04", name: "Galekid", number: "056/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/56.webp", },
{ id: "hgss04-057", serieId: "HGSS04", name: "Chétiflor", number: "057/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/57.webp", },
{ id: "hgss04-058", serieId: "HGSS04", name: "Archéomire", number: "058/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/58.webp", },
{ id: "hgss04-059", serieId: "HGSS04", name: "Carvanha", number: "059/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/59.webp", },
{ id: "hgss04-060", serieId: "HGSS04", name: "Osselait", number: "060/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/60.webp", },
{ id: "hgss04-061", serieId: "HGSS04", name: "Taupiqueur", number: "061/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/61.webp", },
{ id: "hgss04-062", serieId: "HGSS04", name: "Minidraco", number: "062/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/62.webp", },
{ id: "hgss04-063", serieId: "HGSS04", name: "Fantominus", number: "063/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/63.webp", },
{ id: "hgss04-064", serieId: "HGSS04", name: "Lumivole", number: "064/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/64.webp", },
{ id: "hgss04-065", serieId: "HGSS04", name: "Crikzik", number: "065/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/65.webp", },
{ id: "hgss04-066", serieId: "HGSS04", name: "Excelangue", number: "066/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/66.webp", },
{ id: "hgss04-067", serieId: "HGSS04", name: "Machoc", number: "067/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/67.webp", },
{ id: "hgss04-068", serieId: "HGSS04", name: "Magneti", number: "068/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/68.webp", },
{ id: "hgss04-069", serieId: "HGSS04", name: "Nidoran♀", number: "069/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/69.webp", },
{ id: "hgss04-070", serieId: "HGSS04", name: "Nidoran♂", number: "070/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/70.webp", },
{ id: "hgss04-071", serieId: "HGSS04", name: "Roucool", number: "071/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/71.webp", },
{ id: "hgss04-072", serieId: "HGSS04", name: "Ponyta", number: "072/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/72.webp", },
{ id: "hgss04-073", serieId: "HGSS04", name: "Porygon", number: "073/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/73.webp", },
{ id: "hgss04-074", serieId: "HGSS04", name: "Psykokwak", number: "074/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/74.webp", },
{ id: "hgss04-075", serieId: "HGSS04", name: "Polichombr", number: "075/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/75.webp", },
{ id: "hgss04-076", serieId: "HGSS04", name: "Rapion", number: "076/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/76.webp", },
{ id: "hgss04-077", serieId: "HGSS04", name: "Spoink", number: "077/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/77.webp", },
{ id: "hgss04-078", serieId: "HGSS04", name: "Tylton", number: "078/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/78.webp", },
{ id: "hgss04-079", serieId: "HGSS04", name: "Marcacrin", number: "079/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/79.webp", },
{ id: "hgss04-080", serieId: "HGSS04", name: "Tentacool", number: "080/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/80.webp", },
{ id: "hgss04-081", serieId: "HGSS04", name: "Mimitoss", number: "081/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/81.webp", },
{ id: "hgss04-082", serieId: "HGSS04", name: "Muciole", number: "082/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/82.webp", },
{ id: "hgss04-083", serieId: "HGSS04", name: "Voltorbe", number: "083/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/83.webp", },
{ id: "hgss04-084", serieId: "HGSS04", name: "Yanma", number: "084/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/84.webp", },
{ id: "hgss04-085", serieId: "HGSS04", name: "Karatéka", number: "085/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/85.webp", },
{ id: "hgss04-086", serieId: "HGSS04", name: "Plateau Indigo", number: "086/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/86.webp", },
{ id: "hgss04-087", serieId: "HGSS04", name: "Bras indésirable", number: "087/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/87.webp", },
{ id: "hgss04-088", serieId: "HGSS04", name: "Détecteur", number: "088/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/88.webp", },
{ id: "hgss04-089", serieId: "HGSS04", name: "Jumelles", number: "089/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/89.webp", },
{ id: "hgss04-090", serieId: "HGSS04", name: "Énergie Rescousse", number: "090/102", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/90.webp", },
{ id: "hgss04-091", serieId: "HGSS04", name: "Absol", number: "091/102", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/91.webp", },
{ id: "hgss04-092", serieId: "HGSS04", name: "Celebi", number: "092/102", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/92.webp", },
{ id: "hgss04-093", serieId: "HGSS04", name: "Electrode", number: "093/102", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/93.webp", },
{ id: "hgss04-094", serieId: "HGSS04", name: "Ectoplasma", number: "094/102", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/94.webp", },
{ id: "hgss04-095", serieId: "HGSS04", name: "Mackogneur", number: "095/102", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/95.webp", },
{ id: "hgss04-096", serieId: "HGSS04", name: "Magnézone", number: "096/102", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/96.webp", },
{ id: "hgss04-097", serieId: "HGSS04", name: "Mew", number: "097/102", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/97.webp", },
{ id: "hgss04-098", serieId: "HGSS04", name: "Yanmega", number: "098/102", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/98.webp", },
{ id: "hgss04-099", serieId: "HGSS04", name: "Darkrai & Cresselia", number: "099/102", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/99.webp", },
{ id: "hgss04-100", serieId: "HGSS04", name: "Darkrai & Cresselia", number: "100/102", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/100.webp", },
{ id: "hgss04-101", serieId: "HGSS04", name: "Palkia & Dialga", number: "101/102", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/101.webp", },
{ id: "hgss04-102", serieId: "HGSS04", name: "Palkia & Dialga", number: "102/102", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/102.webp", },
{ id: "hgss04-quatre", serieId: "HGSS04", name: "Lithographie d'Alpha", number: "QUATRE", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/HGSS04/quatre.webp", },
] as unknown as Card[];
