import type { Card, Serie } from "../../catalog";

export const MCDO_SERIES = [
  {
    "id": "2011bw",
    "blocId": "mcdo",
    "code": "2011BW",
    "name": "Collection McDonald's 2011",
    "releaseYear": 2011
  },
  {
    "id": "2012bw",
    "blocId": "mcdo",
    "code": "2012BW",
    "name": "Collection McDonald's 2012",
    "releaseYear": 2012
  },
  {
    "id": "2013bw",
    "blocId": "mcdo",
    "code": "2013BW",
    "name": "Collection McDonald's 2013",
    "releaseYear": 2013
  },
  {
    "id": "2014xy",
    "blocId": "mcdo",
    "code": "2014XY",
    "name": "Collection McDonald's 2014",
    "releaseYear": 2014
  },
  {
    "id": "2015xy",
    "blocId": "mcdo",
    "code": "2015XY",
    "name": "Collection McDonald's 2015",
    "releaseYear": 2015
  },
  {
    "id": "2016xy",
    "blocId": "mcdo",
    "code": "2016XY",
    "name": "Collection McDonald's 2016",
    "releaseYear": 2016
  },
  {
    "id": "2017sm",
    "blocId": "mcdo",
    "code": "2017SM",
    "name": "Collection McDonald's 2017",
    "releaseYear": 2017
  },
  {
    "id": "2018sm-fr",
    "blocId": "mcdo",
    "code": "2018SM-FR",
    "name": "Collection McDonald's 2018",
    "releaseYear": 2018
  },
  {
    "id": "2019sm-fr",
    "blocId": "mcdo",
    "code": "2019SM-FR",
    "name": "Collection McDonald's 2019",
    "releaseYear": 2019
  },
  {
    "id": "2021swsh",
    "blocId": "mcdo",
    "code": "2021SWSH",
    "name": "Collection McDonald's 2021",
    "releaseYear": 2021
  },
  {
    "id": "2022swsh",
    "blocId": "mcdo",
    "code": "2022SWSH",
    "name": "Collection McDonald's 2022",
    "releaseYear": 2022
  },
  {
    "id": "2023sv",
    "blocId": "mcdo",
    "code": "2023SV",
    "name": "Collection McDonald's 2023",
    "releaseYear": 2023
  },
  {
    "id": "2024sv",
    "blocId": "mcdo",
    "code": "2024SV",
    "name": "Collection McDonald's 2024",
    "releaseYear": 2024
  }
] satisfies Serie[];

export const MCDO_CARDS = [
  {
    "id": "mcdo-2011bw-1",
    "serieId": "2011bw",
    "name": "Vipélierre",
    "number": "01/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2011bw/1.png"
  },
  {
    "id": "mcdo-2011bw-2",
    "serieId": "2011bw",
    "name": "Maracachi",
    "number": "02/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2011bw/2.png"
  },
  {
    "id": "mcdo-2011bw-3",
    "serieId": "2011bw",
    "name": "Gruikui",
    "number": "03/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2011bw/3.png"
  },
  {
    "id": "mcdo-2011bw-4",
    "serieId": "2011bw",
    "name": "Moustillon",
    "number": "04/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2011bw/4.png"
  },
  {
    "id": "mcdo-2011bw-5",
    "serieId": "2011bw",
    "name": "Mamanbo",
    "number": "05/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2011bw/5.png"
  },
  {
    "id": "mcdo-2011bw-6",
    "serieId": "2011bw",
    "name": "Zébibron",
    "number": "06/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2011bw/6.png"
  },
  {
    "id": "mcdo-2011bw-7",
    "serieId": "2011bw",
    "name": "Munna",
    "number": "07/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2011bw/7.png"
  },
  {
    "id": "mcdo-2011bw-8",
    "serieId": "2011bw",
    "name": "Mascaïman",
    "number": "08/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2011bw/8.png"
  },
  {
    "id": "mcdo-2011bw-9",
    "serieId": "2011bw",
    "name": "Zorua",
    "number": "09/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2011bw/9.png"
  },
  {
    "id": "mcdo-2011bw-10",
    "serieId": "2011bw",
    "name": "Tic",
    "number": "10/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2011bw/10.png"
  },
  {
    "id": "mcdo-2011bw-11",
    "serieId": "2011bw",
    "name": "Poichigeon",
    "number": "11/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2011bw/11.png"
  },
  {
    "id": "mcdo-2011bw-12",
    "serieId": "2011bw",
    "name": "Nanméouïe",
    "number": "12/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2011bw/12.png"
  },
  {
    "id": "mcdo-2012bw-1",
    "serieId": "2012bw",
    "name": "Lianaja",
    "number": "01/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2012bw/1.png"
  },
  {
    "id": "mcdo-2012bw-2",
    "serieId": "2012bw",
    "name": "Feuillajou",
    "number": "02/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2012bw/2.png"
  },
  {
    "id": "mcdo-2012bw-3",
    "serieId": "2012bw",
    "name": "Crabicoque",
    "number": "03/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2012bw/3.png"
  },
  {
    "id": "mcdo-2012bw-4",
    "serieId": "2012bw",
    "name": "Grotichon",
    "number": "04/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2012bw/4.png"
  },
  {
    "id": "mcdo-2012bw-5",
    "serieId": "2012bw",
    "name": "Mateloutre",
    "number": "05/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2012bw/5.png"
  },
  {
    "id": "mcdo-2012bw-6",
    "serieId": "2012bw",
    "name": "Emolga",
    "number": "06/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2012bw/6.png"
  },
  {
    "id": "mcdo-2012bw-7",
    "serieId": "2012bw",
    "name": "Chovsourir",
    "number": "07/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2012bw/7.png"
  },
  {
    "id": "mcdo-2012bw-8",
    "serieId": "2012bw",
    "name": "Rototaupe",
    "number": "08/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2012bw/8.png"
  },
  {
    "id": "mcdo-2012bw-9",
    "serieId": "2012bw",
    "name": "Chacripan",
    "number": "09/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2012bw/9.png"
  },
  {
    "id": "mcdo-2012bw-10",
    "serieId": "2012bw",
    "name": "Baggiguane",
    "number": "10/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2012bw/10.png"
  },
  {
    "id": "mcdo-2012bw-11",
    "serieId": "2012bw",
    "name": "Clic",
    "number": "11/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2012bw/11.png"
  },
  {
    "id": "mcdo-2012bw-12",
    "serieId": "2012bw",
    "name": "Coupenotte",
    "number": "12/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2012bw/12.png"
  },
  {
    "id": "mcdo-2013bw-1",
    "serieId": "2013bw",
    "name": "Phyllali",
    "number": "01/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2013bw/1.png"
  },
  {
    "id": "mcdo-2013bw-2",
    "serieId": "2013bw",
    "name": "Pyroli",
    "number": "02/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2013bw/2.png"
  },
  {
    "id": "mcdo-2013bw-3",
    "serieId": "2013bw",
    "name": "Aquali",
    "number": "03/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2013bw/3.png"
  },
  {
    "id": "mcdo-2013bw-4",
    "serieId": "2013bw",
    "name": "Givrali",
    "number": "04/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2013bw/4.png"
  },
  {
    "id": "mcdo-2013bw-5",
    "serieId": "2013bw",
    "name": "Pikachu",
    "number": "05/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2013bw/5.png"
  },
  {
    "id": "mcdo-2013bw-6",
    "serieId": "2013bw",
    "name": "Voltali",
    "number": "06/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2013bw/6.png"
  },
  {
    "id": "mcdo-2013bw-7",
    "serieId": "2013bw",
    "name": "Mentali",
    "number": "07/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2013bw/7.png"
  },
  {
    "id": "mcdo-2013bw-8",
    "serieId": "2013bw",
    "name": "Charpenti",
    "number": "08/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2013bw/8.png"
  },
  {
    "id": "mcdo-2013bw-9",
    "serieId": "2013bw",
    "name": "Noctali",
    "number": "09/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2013bw/9.png"
  },
  {
    "id": "mcdo-2013bw-10",
    "serieId": "2013bw",
    "name": "Baggiguane",
    "number": "10/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2013bw/10.png"
  },
  {
    "id": "mcdo-2013bw-11",
    "serieId": "2013bw",
    "name": "Zorua",
    "number": "11/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2013bw/11.png"
  },
  {
    "id": "mcdo-2013bw-12",
    "serieId": "2013bw",
    "name": "Évoli",
    "number": "12/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2013bw/12.png"
  },
  {
    "id": "mcdo-2014xy-1",
    "serieId": "2014xy",
    "name": "Aspicot",
    "number": "01/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2014xy/1.png"
  },
  {
    "id": "mcdo-2014xy-2",
    "serieId": "2014xy",
    "name": "Marisson",
    "number": "02/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2014xy/2.png"
  },
  {
    "id": "mcdo-2014xy-3",
    "serieId": "2014xy",
    "name": "Feunnec",
    "number": "03/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2014xy/3.png"
  },
  {
    "id": "mcdo-2014xy-4",
    "serieId": "2014xy",
    "name": "Grenousse",
    "number": "04/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2014xy/4.png"
  },
  {
    "id": "mcdo-2014xy-5",
    "serieId": "2014xy",
    "name": "Pikachu",
    "number": "05/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2014xy/5.png"
  },
  {
    "id": "mcdo-2014xy-6",
    "serieId": "2014xy",
    "name": "Sepiatop",
    "number": "06/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2014xy/6.png"
  },
  {
    "id": "mcdo-2014xy-7",
    "serieId": "2014xy",
    "name": "Monorpale",
    "number": "07/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2014xy/7.png"
  },
  {
    "id": "mcdo-2014xy-8",
    "serieId": "2014xy",
    "name": "Snubbull",
    "number": "08/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2014xy/8.png"
  },
  {
    "id": "mcdo-2014xy-9",
    "serieId": "2014xy",
    "name": "Sucroquin",
    "number": "09/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2014xy/9.png"
  },
  {
    "id": "mcdo-2014xy-10",
    "serieId": "2014xy",
    "name": "Sapereau",
    "number": "10/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2014xy/10.png"
  },
  {
    "id": "mcdo-2014xy-11",
    "serieId": "2014xy",
    "name": "Passerouge",
    "number": "11/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2014xy/11.png"
  },
  {
    "id": "mcdo-2014xy-12",
    "serieId": "2014xy",
    "name": "Couafarel",
    "number": "12/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2014xy/12.png"
  },
  {
    "id": "mcdo-2015xy-1",
    "serieId": "2015xy",
    "name": "Arcko",
    "number": "01/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2015xy/1.png"
  },
  {
    "id": "mcdo-2015xy-2",
    "serieId": "2015xy",
    "name": "Nénupiot",
    "number": "02/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2015xy/2.png"
  },
  {
    "id": "mcdo-2015xy-3",
    "serieId": "2015xy",
    "name": "Poussifeu",
    "number": "03/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2015xy/3.png"
  },
  {
    "id": "mcdo-2015xy-4",
    "serieId": "2015xy",
    "name": "Stari",
    "number": "04/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2015xy/4.png"
  },
  {
    "id": "mcdo-2015xy-5",
    "serieId": "2015xy",
    "name": "Gobou",
    "number": "05/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2015xy/5.png"
  },
  {
    "id": "mcdo-2015xy-6",
    "serieId": "2015xy",
    "name": "Pikachu",
    "number": "06/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2015xy/6.png"
  },
  {
    "id": "mcdo-2015xy-7",
    "serieId": "2015xy",
    "name": "Dynavolt",
    "number": "07/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2015xy/7.png"
  },
  {
    "id": "mcdo-2015xy-8",
    "serieId": "2015xy",
    "name": "Rhinocorne",
    "number": "08/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2015xy/8.png"
  },
  {
    "id": "mcdo-2015xy-9",
    "serieId": "2015xy",
    "name": "Méditikka",
    "number": "09/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2015xy/9.png"
  },
  {
    "id": "mcdo-2015xy-10",
    "serieId": "2015xy",
    "name": "Marill",
    "number": "10/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2015xy/10.png"
  },
  {
    "id": "mcdo-2015xy-11",
    "serieId": "2015xy",
    "name": "Zigzaton",
    "number": "11/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2015xy/11.png"
  },
  {
    "id": "mcdo-2015xy-12",
    "serieId": "2015xy",
    "name": "Skitty",
    "number": "12/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2015xy/12.png"
  },
  {
    "id": "mcdo-2016xy-1",
    "serieId": "2016xy",
    "name": "Goupix",
    "number": "01/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2016xy/1.png"
  },
  {
    "id": "mcdo-2016xy-2",
    "serieId": "2016xy",
    "name": "Poussifeu",
    "number": "02/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2016xy/2.png"
  },
  {
    "id": "mcdo-2016xy-3",
    "serieId": "2016xy",
    "name": "Feunnec",
    "number": "03/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2016xy/3.png"
  },
  {
    "id": "mcdo-2016xy-4",
    "serieId": "2016xy",
    "name": "Magicarpe",
    "number": "04/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2016xy/4.png"
  },
  {
    "id": "mcdo-2016xy-5",
    "serieId": "2016xy",
    "name": "Kaiminus",
    "number": "05/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2016xy/5.png"
  },
  {
    "id": "mcdo-2016xy-6",
    "serieId": "2016xy",
    "name": "Pikachu",
    "number": "06/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2016xy/6.png"
  },
  {
    "id": "mcdo-2016xy-7",
    "serieId": "2016xy",
    "name": "Baggiguane",
    "number": "07/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2016xy/7.png"
  },
  {
    "id": "mcdo-2016xy-8",
    "serieId": "2016xy",
    "name": "Rondoudou",
    "number": "08/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2016xy/8.png"
  },
  {
    "id": "mcdo-2016xy-9",
    "serieId": "2016xy",
    "name": "Togepi",
    "number": "09/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2016xy/9.png"
  },
  {
    "id": "mcdo-2016xy-10",
    "serieId": "2016xy",
    "name": "Dedenne",
    "number": "10/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2016xy/10.png"
  },
  {
    "id": "mcdo-2016xy-11",
    "serieId": "2016xy",
    "name": "Miaouss",
    "number": "11/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2016xy/11.png"
  },
  {
    "id": "mcdo-2016xy-12",
    "serieId": "2016xy",
    "name": "Évoli",
    "number": "12/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2016xy/12.png"
  },
  {
    "id": "mcdo-2017sm-1",
    "serieId": "2017sm",
    "name": "Brindibou",
    "number": "01/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2017sm/1.png"
  },
  {
    "id": "mcdo-2017sm-2",
    "serieId": "2017sm",
    "name": "Larvibule",
    "number": "02/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2017sm/2.png"
  },
  {
    "id": "mcdo-2017sm-3",
    "serieId": "2017sm",
    "name": "Flamiaou",
    "number": "03/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2017sm/3.png"
  },
  {
    "id": "mcdo-2017sm-4",
    "serieId": "2017sm",
    "name": "Otaquin",
    "number": "04/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2017sm/4.png"
  },
  {
    "id": "mcdo-2017sm-5",
    "serieId": "2017sm",
    "name": "Pikachu",
    "number": "05/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2017sm/5.png"
  },
  {
    "id": "mcdo-2017sm-6",
    "serieId": "2017sm",
    "name": "Cosmog",
    "number": "06/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2017sm/6.png"
  },
  {
    "id": "mcdo-2017sm-7",
    "serieId": "2017sm",
    "name": "Crabagarre",
    "number": "07/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2017sm/7.png"
  },
  {
    "id": "mcdo-2017sm-8",
    "serieId": "2017sm",
    "name": "Miaouss d'Alola",
    "number": "08/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2017sm/8.png"
  },
  {
    "id": "mcdo-2017sm-9",
    "serieId": "2017sm",
    "name": "Taupiqueur d'Alola",
    "number": "09/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2017sm/9.png"
  },
  {
    "id": "mcdo-2017sm-10",
    "serieId": "2017sm",
    "name": "Bombydou",
    "number": "10/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2017sm/10.png"
  },
  {
    "id": "mcdo-2017sm-11",
    "serieId": "2017sm",
    "name": "Picassaut",
    "number": "11/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2017sm/11.png"
  },
  {
    "id": "mcdo-2017sm-12",
    "serieId": "2017sm",
    "name": "Manglouton",
    "number": "12/12",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2017sm/12.png"
  },
  {
    "id": "mcdo-2018sm-fr-1",
    "serieId": "2018sm-fr",
    "name": "Feuillajou",
    "number": "01/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/1.png"
  },
  {
    "id": "mcdo-2018sm-fr-2",
    "serieId": "2018sm-fr",
    "name": "Croquine",
    "number": "02/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/2.png"
  },
  {
    "id": "mcdo-2018sm-fr-3",
    "serieId": "2018sm-fr",
    "name": "Sovkipou",
    "number": "03/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/3.png"
  },
  {
    "id": "mcdo-2018sm-fr-4",
    "serieId": "2018sm-fr",
    "name": "Salamèche",
    "number": "04/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/4.png"
  },
  {
    "id": "mcdo-2018sm-fr-5",
    "serieId": "2018sm-fr",
    "name": "Caninos",
    "number": "05/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/5.png"
  },
  {
    "id": "mcdo-2018sm-fr-6",
    "serieId": "2018sm-fr",
    "name": "Chartor",
    "number": "06/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/6.png"
  },
  {
    "id": "mcdo-2018sm-fr-7",
    "serieId": "2018sm-fr",
    "name": "Flamajou",
    "number": "07/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/7.png"
  },
  {
    "id": "mcdo-2018sm-fr-8",
    "serieId": "2018sm-fr",
    "name": "Sabelette d'Alola",
    "number": "08/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/8.png"
  },
  {
    "id": "mcdo-2018sm-fr-9",
    "serieId": "2018sm-fr",
    "name": "Goupix d'Alola",
    "number": "09/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/9.png"
  },
  {
    "id": "mcdo-2018sm-fr-10",
    "serieId": "2018sm-fr",
    "name": "Psykokwak",
    "number": "10/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/10.png"
  },
  {
    "id": "mcdo-2018sm-fr-11",
    "serieId": "2018sm-fr",
    "name": "Ptitard",
    "number": "11/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/11.png"
  },
  {
    "id": "mcdo-2018sm-fr-12",
    "serieId": "2018sm-fr",
    "name": "Cadoizo",
    "number": "12/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/12.png"
  },
  {
    "id": "mcdo-2018sm-fr-13",
    "serieId": "2018sm-fr",
    "name": "Goélise",
    "number": "13/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/13.png"
  },
  {
    "id": "mcdo-2018sm-fr-14",
    "serieId": "2018sm-fr",
    "name": "Wailmer",
    "number": "14/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/14.png"
  },
  {
    "id": "mcdo-2018sm-fr-15",
    "serieId": "2018sm-fr",
    "name": "Flotajou",
    "number": "15/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/15.png"
  },
  {
    "id": "mcdo-2018sm-fr-16",
    "serieId": "2018sm-fr",
    "name": "Froussardine",
    "number": "16/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/16.png"
  },
  {
    "id": "mcdo-2018sm-fr-17",
    "serieId": "2018sm-fr",
    "name": "Pikachu",
    "number": "17/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/17.png"
  },
  {
    "id": "mcdo-2018sm-fr-18",
    "serieId": "2018sm-fr",
    "name": "Racaillou d'Alola",
    "number": "18/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/18.png"
  },
  {
    "id": "mcdo-2018sm-fr-19",
    "serieId": "2018sm-fr",
    "name": "Loupio",
    "number": "19/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/19.png"
  },
  {
    "id": "mcdo-2018sm-fr-20",
    "serieId": "2018sm-fr",
    "name": "Togedemaru",
    "number": "20/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/20.png"
  },
  {
    "id": "mcdo-2018sm-fr-21",
    "serieId": "2018sm-fr",
    "name": "Ramoloss",
    "number": "21/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/21.png"
  },
  {
    "id": "mcdo-2018sm-fr-22",
    "serieId": "2018sm-fr",
    "name": "Machoc",
    "number": "22/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/22.png"
  },
  {
    "id": "mcdo-2018sm-fr-23",
    "serieId": "2018sm-fr",
    "name": "Makuhita",
    "number": "23/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/23.png"
  },
  {
    "id": "mcdo-2018sm-fr-24",
    "serieId": "2018sm-fr",
    "name": "Riolu",
    "number": "24/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/24.png"
  },
  {
    "id": "mcdo-2018sm-fr-25",
    "serieId": "2018sm-fr",
    "name": "Rocabot",
    "number": "25/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/25.png"
  },
  {
    "id": "mcdo-2018sm-fr-26",
    "serieId": "2018sm-fr",
    "name": "Tiboudet",
    "number": "26/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/26.png"
  },
  {
    "id": "mcdo-2018sm-fr-27",
    "serieId": "2018sm-fr",
    "name": "Cornèbre",
    "number": "27/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/27.png"
  },
  {
    "id": "mcdo-2018sm-fr-28",
    "serieId": "2018sm-fr",
    "name": "Farfuret",
    "number": "28/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/28.png"
  },
  {
    "id": "mcdo-2018sm-fr-29",
    "serieId": "2018sm-fr",
    "name": "Airmure",
    "number": "29/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/29.png"
  },
  {
    "id": "mcdo-2018sm-fr-30",
    "serieId": "2018sm-fr",
    "name": "Mélofée",
    "number": "30/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/30.png"
  },
  {
    "id": "mcdo-2018sm-fr-31",
    "serieId": "2018sm-fr",
    "name": "Tarsal",
    "number": "31/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/31.png"
  },
  {
    "id": "mcdo-2018sm-fr-32",
    "serieId": "2018sm-fr",
    "name": "Minidraco",
    "number": "32/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/32.png"
  },
  {
    "id": "mcdo-2018sm-fr-33",
    "serieId": "2018sm-fr",
    "name": "Mucuscule",
    "number": "33/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/33.png"
  },
  {
    "id": "mcdo-2018sm-fr-34",
    "serieId": "2018sm-fr",
    "name": "Bébécaille",
    "number": "34/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/34.png"
  },
  {
    "id": "mcdo-2018sm-fr-35",
    "serieId": "2018sm-fr",
    "name": "Miaouss",
    "number": "35/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/35.png"
  },
  {
    "id": "mcdo-2018sm-fr-36",
    "serieId": "2018sm-fr",
    "name": "Leveinard",
    "number": "36/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/36.png"
  },
  {
    "id": "mcdo-2018sm-fr-37",
    "serieId": "2018sm-fr",
    "name": "Évoli",
    "number": "37/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/37.png"
  },
  {
    "id": "mcdo-2018sm-fr-38",
    "serieId": "2018sm-fr",
    "name": "Ponchiot",
    "number": "38/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/38.png"
  },
  {
    "id": "mcdo-2018sm-fr-39",
    "serieId": "2018sm-fr",
    "name": "Passerouge",
    "number": "39/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/39.png"
  },
  {
    "id": "mcdo-2018sm-fr-40",
    "serieId": "2018sm-fr",
    "name": "Nounourson",
    "number": "40/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2018sm-fr/40.png"
  },
  {
    "id": "mcdo-2019sm-fr-1",
    "serieId": "2019sm-fr",
    "name": "Bulbizarre",
    "number": "01/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/1.png"
  },
  {
    "id": "mcdo-2019sm-fr-2",
    "serieId": "2019sm-fr",
    "name": "Chenipan",
    "number": "02/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/2.png"
  },
  {
    "id": "mcdo-2019sm-fr-3",
    "serieId": "2019sm-fr",
    "name": "Paras",
    "number": "03/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/3.png"
  },
  {
    "id": "mcdo-2019sm-fr-4",
    "serieId": "2019sm-fr",
    "name": "Chétiflor",
    "number": "04/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/4.png"
  },
  {
    "id": "mcdo-2019sm-fr-5",
    "serieId": "2019sm-fr",
    "name": "Noadkoko d'Alola",
    "number": "05/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/5.png"
  },
  {
    "id": "mcdo-2019sm-fr-6",
    "serieId": "2019sm-fr",
    "name": "Saquedeneu",
    "number": "06/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/6.png"
  },
  {
    "id": "mcdo-2019sm-fr-7",
    "serieId": "2019sm-fr",
    "name": "Insécateur",
    "number": "07/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/7.png"
  },
  {
    "id": "mcdo-2019sm-fr-8",
    "serieId": "2019sm-fr",
    "name": "Scarabrute",
    "number": "08/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/8.png"
  },
  {
    "id": "mcdo-2019sm-fr-9",
    "serieId": "2019sm-fr",
    "name": "Salamèche",
    "number": "09/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/9.png"
  },
  {
    "id": "mcdo-2019sm-fr-10",
    "serieId": "2019sm-fr",
    "name": "Magmar",
    "number": "10/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/10.png"
  },
  {
    "id": "mcdo-2019sm-fr-11",
    "serieId": "2019sm-fr",
    "name": "Sulfura",
    "number": "11/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/11.png"
  },
  {
    "id": "mcdo-2019sm-fr-12",
    "serieId": "2019sm-fr",
    "name": "Sabelette d'Alola",
    "number": "12/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/12.png"
  },
  {
    "id": "mcdo-2019sm-fr-13",
    "serieId": "2019sm-fr",
    "name": "Goupix d'Alola",
    "number": "13/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/13.png"
  },
  {
    "id": "mcdo-2019sm-fr-14",
    "serieId": "2019sm-fr",
    "name": "Ramoloss",
    "number": "14/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/14.png"
  },
  {
    "id": "mcdo-2019sm-fr-15",
    "serieId": "2019sm-fr",
    "name": "Hypotrempe",
    "number": "15/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/15.png"
  },
  {
    "id": "mcdo-2019sm-fr-16",
    "serieId": "2019sm-fr",
    "name": "Stari",
    "number": "16/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/16.png"
  },
  {
    "id": "mcdo-2019sm-fr-17",
    "serieId": "2019sm-fr",
    "name": "Magicarpe",
    "number": "17/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/17.png"
  },
  {
    "id": "mcdo-2019sm-fr-18",
    "serieId": "2019sm-fr",
    "name": "Lokhlass",
    "number": "18/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/18.png"
  },
  {
    "id": "mcdo-2019sm-fr-19",
    "serieId": "2019sm-fr",
    "name": "Artikodin",
    "number": "19/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/19.png"
  },
  {
    "id": "mcdo-2019sm-fr-20",
    "serieId": "2019sm-fr",
    "name": "Pikachu",
    "number": "20/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/20.png"
  },
  {
    "id": "mcdo-2019sm-fr-21",
    "serieId": "2019sm-fr",
    "name": "Raichu d'Alola",
    "number": "21/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/21.png"
  },
  {
    "id": "mcdo-2019sm-fr-22",
    "serieId": "2019sm-fr",
    "name": "Racaillou d'Alola",
    "number": "22/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/22.png"
  },
  {
    "id": "mcdo-2019sm-fr-23",
    "serieId": "2019sm-fr",
    "name": "Magnéti",
    "number": "23/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/23.png"
  },
  {
    "id": "mcdo-2019sm-fr-24",
    "serieId": "2019sm-fr",
    "name": "Voltorbe",
    "number": "24/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/24.png"
  },
  {
    "id": "mcdo-2019sm-fr-25",
    "serieId": "2019sm-fr",
    "name": "Élektek",
    "number": "25/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/25.png"
  },
  {
    "id": "mcdo-2019sm-fr-26",
    "serieId": "2019sm-fr",
    "name": "Électhor",
    "number": "26/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/26.png"
  },
  {
    "id": "mcdo-2019sm-fr-27",
    "serieId": "2019sm-fr",
    "name": "Fantominus",
    "number": "27/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/27.png"
  },
  {
    "id": "mcdo-2019sm-fr-28",
    "serieId": "2019sm-fr",
    "name": "Férosinge",
    "number": "28/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/28.png"
  },
  {
    "id": "mcdo-2019sm-fr-29",
    "serieId": "2019sm-fr",
    "name": "Onix",
    "number": "29/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/29.png"
  },
  {
    "id": "mcdo-2019sm-fr-30",
    "serieId": "2019sm-fr",
    "name": "Osselait",
    "number": "30/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/30.png"
  },
  {
    "id": "mcdo-2019sm-fr-31",
    "serieId": "2019sm-fr",
    "name": "Rhinocorne",
    "number": "31/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/31.png"
  },
  {
    "id": "mcdo-2019sm-fr-32",
    "serieId": "2019sm-fr",
    "name": "Miaouss d'Alola",
    "number": "32/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/32.png"
  },
  {
    "id": "mcdo-2019sm-fr-33",
    "serieId": "2019sm-fr",
    "name": "Taupiqueur d'Alola",
    "number": "33/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/33.png"
  },
  {
    "id": "mcdo-2019sm-fr-34",
    "serieId": "2019sm-fr",
    "name": "Triopikeur d'Alola",
    "number": "34/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/34.png"
  },
  {
    "id": "mcdo-2019sm-fr-35",
    "serieId": "2019sm-fr",
    "name": "Rondoudou",
    "number": "35/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/35.png"
  },
  {
    "id": "mcdo-2019sm-fr-36",
    "serieId": "2019sm-fr",
    "name": "Minidraco",
    "number": "36/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/36.png"
  },
  {
    "id": "mcdo-2019sm-fr-37",
    "serieId": "2019sm-fr",
    "name": "Excelangue",
    "number": "37/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/37.png"
  },
  {
    "id": "mcdo-2019sm-fr-38",
    "serieId": "2019sm-fr",
    "name": "Leveinard",
    "number": "38/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/38.png"
  },
  {
    "id": "mcdo-2019sm-fr-39",
    "serieId": "2019sm-fr",
    "name": "Kangourex",
    "number": "39/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/39.png"
  },
  {
    "id": "mcdo-2019sm-fr-40",
    "serieId": "2019sm-fr",
    "name": "Évoli",
    "number": "40/40",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2019sm-fr/40.png"
  },
  {
    "id": "mcdo-2021swsh-1",
    "serieId": "2021swsh",
    "name": "Bulbizarre",
    "number": "01/25",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2021swsh/1.png"
  },
  {
    "id": "mcdo-2021swsh-2",
    "serieId": "2021swsh",
    "name": "Germignon",
    "number": "02/25",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2021swsh/2.png"
  },
  {
    "id": "mcdo-2021swsh-3",
    "serieId": "2021swsh",
    "name": "Arcko",
    "number": "03/25",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2021swsh/3.png"
  },
  {
    "id": "mcdo-2021swsh-4",
    "serieId": "2021swsh",
    "name": "Tortipouss",
    "number": "04/25",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2021swsh/4.png"
  },
  {
    "id": "mcdo-2021swsh-5",
    "serieId": "2021swsh",
    "name": "Vipélierre",
    "number": "05/25",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2021swsh/5.png"
  },
  {
    "id": "mcdo-2021swsh-6",
    "serieId": "2021swsh",
    "name": "Marisson",
    "number": "06/25",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2021swsh/6.png"
  },
  {
    "id": "mcdo-2021swsh-7",
    "serieId": "2021swsh",
    "name": "Brindibou",
    "number": "07/25",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2021swsh/7.png"
  },
  {
    "id": "mcdo-2021swsh-8",
    "serieId": "2021swsh",
    "name": "Ouistempo",
    "number": "08/25",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2021swsh/8.png"
  },
  {
    "id": "mcdo-2021swsh-9",
    "serieId": "2021swsh",
    "name": "Salamèche",
    "number": "09/25",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2021swsh/9.png"
  },
  {
    "id": "mcdo-2021swsh-10",
    "serieId": "2021swsh",
    "name": "Héricendre",
    "number": "10/25",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2021swsh/10.png"
  },
  {
    "id": "mcdo-2021swsh-11",
    "serieId": "2021swsh",
    "name": "Poussifeu",
    "number": "11/25",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2021swsh/11.png"
  },
  {
    "id": "mcdo-2021swsh-12",
    "serieId": "2021swsh",
    "name": "Ouisticram",
    "number": "12/25",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2021swsh/12.png"
  },
  {
    "id": "mcdo-2021swsh-13",
    "serieId": "2021swsh",
    "name": "Gruikui",
    "number": "13/25",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2021swsh/13.png"
  },
  {
    "id": "mcdo-2021swsh-14",
    "serieId": "2021swsh",
    "name": "Feunnec",
    "number": "14/25",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2021swsh/14.png"
  },
  {
    "id": "mcdo-2021swsh-15",
    "serieId": "2021swsh",
    "name": "Flamiaou",
    "number": "15/25",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2021swsh/15.png"
  },
  {
    "id": "mcdo-2021swsh-16",
    "serieId": "2021swsh",
    "name": "Flambino",
    "number": "16/25",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2021swsh/16.png"
  },
  {
    "id": "mcdo-2021swsh-17",
    "serieId": "2021swsh",
    "name": "Carapuce",
    "number": "17/25",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2021swsh/17.png"
  },
  {
    "id": "mcdo-2021swsh-18",
    "serieId": "2021swsh",
    "name": "Kaiminus",
    "number": "18/25",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2021swsh/18.png"
  },
  {
    "id": "mcdo-2021swsh-19",
    "serieId": "2021swsh",
    "name": "Gobou",
    "number": "19/25",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2021swsh/19.png"
  },
  {
    "id": "mcdo-2021swsh-20",
    "serieId": "2021swsh",
    "name": "Tiplouf",
    "number": "20/25",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2021swsh/20.png"
  },
  {
    "id": "mcdo-2021swsh-21",
    "serieId": "2021swsh",
    "name": "Moustillon",
    "number": "21/25",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2021swsh/21.png"
  },
  {
    "id": "mcdo-2021swsh-22",
    "serieId": "2021swsh",
    "name": "Grenousse",
    "number": "22/25",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2021swsh/22.png"
  },
  {
    "id": "mcdo-2021swsh-23",
    "serieId": "2021swsh",
    "name": "Otaquin",
    "number": "23/25",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2021swsh/23.png"
  },
  {
    "id": "mcdo-2021swsh-24",
    "serieId": "2021swsh",
    "name": "Larméléon",
    "number": "24/25",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2021swsh/24.png"
  },
  {
    "id": "mcdo-2021swsh-25",
    "serieId": "2021swsh",
    "name": "Pikachu",
    "number": "25/25",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2021swsh/25.png"
  },
  {
    "id": "mcdo-2022swsh-1",
    "serieId": "2022swsh",
    "name": "Coxy",
    "number": "01/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2022swsh/1.png"
  },
  {
    "id": "mcdo-2022swsh-2",
    "serieId": "2022swsh",
    "name": "Brindibou",
    "number": "02/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2022swsh/2.png"
  },
  {
    "id": "mcdo-2022swsh-3",
    "serieId": "2022swsh",
    "name": "Tournicoton",
    "number": "03/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2022swsh/3.png"
  },
  {
    "id": "mcdo-2022swsh-4",
    "serieId": "2022swsh",
    "name": "Caninos",
    "number": "04/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2022swsh/4.png"
  },
  {
    "id": "mcdo-2022swsh-5",
    "serieId": "2022swsh",
    "name": "Victini",
    "number": "05/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2022swsh/5.png"
  },
  {
    "id": "mcdo-2022swsh-6",
    "serieId": "2022swsh",
    "name": "Lokhlass",
    "number": "06/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2022swsh/6.png"
  },
  {
    "id": "mcdo-2022swsh-7",
    "serieId": "2022swsh",
    "name": "Pikachu",
    "number": "07/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2022swsh/7.png"
  },
  {
    "id": "mcdo-2022swsh-8",
    "serieId": "2022swsh",
    "name": "Loupio",
    "number": "08/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2022swsh/8.png"
  },
  {
    "id": "mcdo-2022swsh-9",
    "serieId": "2022swsh",
    "name": "Lainergie",
    "number": "09/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2022swsh/9.png"
  },
  {
    "id": "mcdo-2022swsh-10",
    "serieId": "2022swsh",
    "name": "Anchwatt",
    "number": "10/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2022swsh/10.png"
  },
  {
    "id": "mcdo-2022swsh-11",
    "serieId": "2022swsh",
    "name": "Bombydou",
    "number": "11/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2022swsh/11.png"
  },
  {
    "id": "mcdo-2022swsh-12",
    "serieId": "2022swsh",
    "name": "Chelours",
    "number": "12/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2022swsh/12.png"
  },
  {
    "id": "mcdo-2022swsh-13",
    "serieId": "2022swsh",
    "name": "Pandarbare",
    "number": "13/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2022swsh/13.png"
  },
  {
    "id": "mcdo-2022swsh-14",
    "serieId": "2022swsh",
    "name": "Draïeul",
    "number": "14/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2022swsh/14.png"
  },
  {
    "id": "mcdo-2022swsh-15",
    "serieId": "2022swsh",
    "name": "Queulorior",
    "number": "15/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2022swsh/15.png"
  },
  {
    "id": "mcdo-2023sv-1",
    "serieId": "2023sv",
    "name": "Poussacha",
    "number": "01/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2023sv/1.png"
  },
  {
    "id": "mcdo-2023sv-2",
    "serieId": "2023sv",
    "name": "Chochodile",
    "number": "02/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2023sv/2.png"
  },
  {
    "id": "mcdo-2023sv-3",
    "serieId": "2023sv",
    "name": "Coiffeton",
    "number": "03/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2023sv/3.png"
  },
  {
    "id": "mcdo-2023sv-4",
    "serieId": "2023sv",
    "name": "Piétacé",
    "number": "04/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2023sv/4.png"
  },
  {
    "id": "mcdo-2023sv-5",
    "serieId": "2023sv",
    "name": "Balbalèze",
    "number": "05/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2023sv/5.png"
  },
  {
    "id": "mcdo-2023sv-6",
    "serieId": "2023sv",
    "name": "Pikachu",
    "number": "06/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2023sv/6.png"
  },
  {
    "id": "mcdo-2023sv-7",
    "serieId": "2023sv",
    "name": "Pohm",
    "number": "07/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2023sv/7.png"
  },
  {
    "id": "mcdo-2023sv-8",
    "serieId": "2023sv",
    "name": "Fulgulairo",
    "number": "08/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2023sv/8.png"
  },
  {
    "id": "mcdo-2023sv-9",
    "serieId": "2023sv",
    "name": "Flotillon",
    "number": "09/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2023sv/9.png"
  },
  {
    "id": "mcdo-2023sv-10",
    "serieId": "2023sv",
    "name": "Dunaconda",
    "number": "10/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2023sv/10.png"
  },
  {
    "id": "mcdo-2023sv-11",
    "serieId": "2023sv",
    "name": "Craparoi",
    "number": "11/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2023sv/11.png"
  },
  {
    "id": "mcdo-2023sv-12",
    "serieId": "2023sv",
    "name": "Leuphorie",
    "number": "12/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2023sv/12.png"
  },
  {
    "id": "mcdo-2023sv-13",
    "serieId": "2023sv",
    "name": "Compagnol",
    "number": "13/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2023sv/13.png"
  },
  {
    "id": "mcdo-2023sv-14",
    "serieId": "2023sv",
    "name": "Motorizard",
    "number": "14/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2023sv/14.png"
  },
  {
    "id": "mcdo-2023sv-15",
    "serieId": "2023sv",
    "name": "Kirlia",
    "number": "15/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2023sv/15.png"
  },
  {
    "id": "mcdo-2024sv-1",
    "serieId": "2024sv",
    "name": "Dracaufeu",
    "number": "01/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2024sv/1.png"
  },
  {
    "id": "mcdo-2024sv-2",
    "serieId": "2024sv",
    "name": "Pikachu",
    "number": "02/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2024sv/2.png"
  },
  {
    "id": "mcdo-2024sv-3",
    "serieId": "2024sv",
    "name": "Miraidon",
    "number": "03/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2024sv/3.png"
  },
  {
    "id": "mcdo-2024sv-4",
    "serieId": "2024sv",
    "name": "Rondoudou",
    "number": "04/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2024sv/4.png"
  },
  {
    "id": "mcdo-2024sv-5",
    "serieId": "2024sv",
    "name": "Bibichut",
    "number": "05/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2024sv/5.png"
  },
  {
    "id": "mcdo-2024sv-6",
    "serieId": "2024sv",
    "name": "Lanssorien",
    "number": "06/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2024sv/6.png"
  },
  {
    "id": "mcdo-2024sv-7",
    "serieId": "2024sv",
    "name": "Maraiste",
    "number": "07/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2024sv/7.png"
  },
  {
    "id": "mcdo-2024sv-8",
    "serieId": "2024sv",
    "name": "Koraidon",
    "number": "08/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2024sv/8.png"
  },
  {
    "id": "mcdo-2024sv-9",
    "serieId": "2024sv",
    "name": "Noctali",
    "number": "09/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2024sv/9.png"
  },
  {
    "id": "mcdo-2024sv-10",
    "serieId": "2024sv",
    "name": "Trioxhydre",
    "number": "10/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2024sv/10.png"
  },
  {
    "id": "mcdo-2024sv-11",
    "serieId": "2024sv",
    "name": "Rugit-Lune",
    "number": "11/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2024sv/11.png"
  },
  {
    "id": "mcdo-2024sv-12",
    "serieId": "2024sv",
    "name": "Dracolosse",
    "number": "12/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2024sv/12.png"
  },
  {
    "id": "mcdo-2024sv-13",
    "serieId": "2024sv",
    "name": "Évoli",
    "number": "13/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2024sv/13.png"
  },
  {
    "id": "mcdo-2024sv-14",
    "serieId": "2024sv",
    "name": "Rayquaza",
    "number": "14/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2024sv/14.png"
  },
  {
    "id": "mcdo-2024sv-15",
    "serieId": "2024sv",
    "name": "Draïeul",
    "number": "15/15",
    "rarity": "Commune",
    "condition": "Near Mint",
    "language": "FR",
    "price": 0.5,
    "stock": 0,
    "image": "/cartes/mcdo/2024sv/15.png"
  }
] satisfies Card[];
