import type { Card } from "../../catalog";

// epee-et-bouclier - 2966 cards
export const MEGA_EVOLUTION_CARDS = ([
  { id: "mega-evolution-001", serieId: "me-promo", name: "Méganium", number: "001", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/1.webp",},
  { id: "mega-evolution-002", serieId: "me-promo", name: "Lézargus ", number: "002", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/2.webp",},
  { id: "mega-evolution-003", serieId: "me-promo", name: "Alakazam ", number: "003", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/3.webp",},
  { id: "mega-evolution-004", serieId: "me-promo", name: "Séléroc ", number: "004", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/4.webp",},
  { id: "mega-evolution-005", serieId: "me-promo", name: "Baudrive ", number: "005", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/5.webp",},
  { id: "mega-evolution-006", serieId: "me-promo", name: "Grodrive ", number: "006", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/6.webp",},
  { id: "mega-evolution-007", serieId: "me-promo", name: "Psykokwak ", number: "007", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/7.webp",},
  { id: "mega-evolution-008", serieId: "me-promo", name: "Akwakwak ", number: "008", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/8.webp",},
  { id: "mega-evolution-009", serieId: "me-promo", name: "Alakazam ", number: "009", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/9.webp",},
  { id: "mega-evolution-010", serieId: "me-promo", name: "Riolu ", number: "010", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/10.webp",},
  { id: "mega-evolution-011", serieId: "me-promo", name: "Méga-Latias ex ", number: "011", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/11.webp",},
  { id: "mega-evolution-012", serieId: "me-promo", name: "Méga-Lucario ex ", number: "012", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/12.webp",},
  { id: "mega-evolution-013", serieId: "me-promo", name: "Méga-Florizarre ex ", number: "013", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/13.webp",},
  { id: "mega-evolution-014", serieId: "me-promo", name: "Malvalame ", number: "014", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/14.webp",},
  { id: "mega-evolution-015", serieId: "me-promo", name: "Zacian ", number: "015", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/15.webp",},
  { id: "mega-evolution-016", serieId: "me-promo", name: "Libégon ", number: "016", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/16.webp",},
  { id: "mega-evolution-017", serieId: "me-promo", name: "Salarsen ", number: "017", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/17.webp",},
  { id: "mega-evolution-018", serieId: "me-promo", name: "Doudouvet ", number: "018", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/18.webp",},
  { id: "mega-evolution-019", serieId: "me-promo", name: "Farfaduvet ", number: "019", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/19.webp",},
  { id: "mega-evolution-020", serieId: "me-promo", name: "Farfuret ", number: "020", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/20.webp",},
  { id: "mega-evolution-021", serieId: "me-promo", name: "Dimoret ", number: "021", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/21.webp",},
  { id: "mega-evolution-022", serieId: "me-promo", name: "Charbambin ", number: "022", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/22.webp",},
  { id: "mega-evolution-023", serieId: "me-promo", name: "Méga-Dracaufeu X ex ", number: "023", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/23.webp",},
  { id: "mega-evolution-024", serieId: "me-promo", name: "Plumeline ex ", number: "024", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/24.webp",},
  { id: "mega-evolution-025", serieId: "me-promo", name: "Méga-Kangourex ex ", number: "025", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/25.webp",},
  { id: "mega-evolution-026", serieId: "me-promo", name: "Meloetta ", number: "026", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/26.webp",},
  { id: "mega-evolution-027", serieId: "me-promo", name: "Spectrum ", number: "027", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/27.webp",},
  { id: "mega-evolution-028", serieId: "me-promo", name: "Celebratory Fanfare ", number: "028", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/28.webp",},
  { id: "mega-evolution-029", serieId: "me-promo", name: "Méga-Dracaufeu X ex ", number: "029", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/29.webp",},
  { id: "mega-evolution-030", serieId: "me-promo", name: "Méga-Dracaufeu Y ex ", number: "030", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/30.webp",},
  { id: "mega-evolution-031", serieId: "me-promo", name: "Zekrom de N ", number: "031", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/31.webp",},
  { id: "mega-evolution-032", serieId: "me-promo", name: "Méga-Gardevoir ex ", number: "032", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/32.webp",},
  { id: "mega-evolution-033", serieId: "me-promo", name: "Méga-Lucario ex ", number: "033", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/33.webp",},
  { id: "mega-evolution-034", serieId: "me-promo", name: "Méga-Méganium ex ", number: "034", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/34.webp",},
  { id: "mega-evolution-035", serieId: "me-promo", name: "Méga-Roitiflam ex ", number: "035", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/35.webp",},
  { id: "mega-evolution-036", serieId: "me-promo", name: "Méga-Aligatueur ex ", number: "036", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/36.webp",},
  { id: "mega-evolution-037", serieId: "me-promo", name: "Bulbizarre ", number: "037", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/37.webp",},
  { id: "mega-evolution-038", serieId: "me-promo", name: "Salamèche ", number: "038", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/38.webp",},
  { id: "mega-evolution-039", serieId: "me-promo", name: "Carapuce ", number: "039", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/39.webp",},
  { id: "mega-evolution-040", serieId: "me-promo", name: "Tortipouss ", number: "040", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/40.webp",},
  { id: "mega-evolution-041", serieId: "me-promo", name: "Ouisticram ", number: "041", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/41.webp",},
  { id: "mega-evolution-042", serieId: "me-promo", name: "Tiplouf ", number: "042", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/42.webp",},
  { id: "mega-evolution-043", serieId: "me-promo", name: "Brindibou ", number: "043", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/43.webp",},
  { id: "mega-evolution-044", serieId: "me-promo", name: "Flamiaou ", number: "044", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/44.webp",},
  { id: "mega-evolution-045", serieId: "me-promo", name: "Otaquin ", number: "045", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/45.webp",},
  { id: "mega-evolution-064", serieId: "me-promo", name: "Majaspic ", number: "064", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/64.webp",},
  { id: "mega-evolution-065", serieId: "me-promo", name: "Golgopathe ", number: "065", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/65.webp",},
  { id: "mega-evolution-066", serieId: "me-promo", name: "Rexillius ", number: "066", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/66.webp",},
  { id: "mega-evolution-067", serieId: "me-promo", name: "Dimoclès ", number: "067", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/67.webp",},
  { id: "mega-evolution-068", serieId: "me-promo", name: "Makuhita ", number: "068", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/68.webp",},
  { id: "mega-evolution-069", serieId: "me-promo", name: "Germignon ", number: "069", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/69.webp",},
  { id: "mega-evolution-070", serieId: "me-promo", name: "Ptyranidur ", number: "070", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/70.webp",},
  { id: "mega-evolution-071", serieId: "me-promo", name: "Méga-Zygarde ex  ", number: "071", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/71.webp",},
  { id: "mega-evolution-074", serieId: "me-promo", name: "Goupelin  ", number: "074", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/74.webp",},
  { id: "mega-evolution-075", serieId: "me-promo", name: "Pharamp  ", number: "075", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/75.webp",},
  { id: "mega-evolution-076", serieId: "me-promo", name: "Nostenfer  ", number: "076", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/76.webp",},
  { id: "mega-evolution-077", serieId: "me-promo", name: "Muplodocus  ", number: "077", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/77.webp",},
  { id: "mega-evolution-081", serieId: "me-promo", name: "Méga-Amphinobi ex  ", number: "081", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/81.webp",},


    // Méga-Évolution ME01
  { id: "mega-evolution-me01-001", serieId: "me01", name: "Bulbizarre", number: "001/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/1.webp", },
  { id: "mega-evolution-me01-002", serieId: "me01", name: "Herbizarre", number: "002/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/2.webp", },
  { id: "mega-evolution-me01-003", serieId: "me01", name: "Méga-Florizarre-ex", number: "003/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/3.webp", },
  { id: "mega-evolution-me01-004", serieId: "me01", name: "Noeunoeuf", number: "004/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/4.webp", },
  { id: "mega-evolution-me01-005", serieId: "me01", name: "Noadkoko", number: "005/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/5.webp", },
  { id: "mega-evolution-me01-006", serieId: "me01", name: "Saquedeneu", number: "006/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/6.webp", },
  { id: "mega-evolution-me01-007", serieId: "me01", name: "Bouldeneu", number: "007/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/7.webp", },
  { id: "mega-evolution-me01-008", serieId: "me01", name: "Germignon", number: "008/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/8.webp", },
  { id: "mega-evolution-me01-009", serieId: "me01", name: "Macronium", number: "009/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/9.webp", },
  { id: "mega-evolution-me01-010", serieId: "me01", name: "Méganium", number: "010/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/10.webp", },
  { id: "mega-evolution-me01-011", serieId: "me01", name: "Caratroc", number: "011/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/11.webp", },
  { id: "mega-evolution-me01-012", serieId: "me01", name: "Celebi", number: "012/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/12.webp", },
  { id: "mega-evolution-me01-013", serieId: "me01", name: "Grainipiot", number: "013/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/13.webp", },
  { id: "mega-evolution-me01-014", serieId: "me01", name: "Pifeuil", number: "014/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/14.webp", },
  { id: "mega-evolution-me01-015", serieId: "me01", name: "Tengalice", number: "015/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/15.webp", },
  { id: "mega-evolution-me01-016", serieId: "me01", name: "Ningale", number: "016/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/16.webp", },
  { id: "mega-evolution-me01-017", serieId: "me01", name: "Ninjask", number: "017/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/17.webp", },
  { id: "mega-evolution-me01-018", serieId: "me01", name: "Sinistrail", number: "018/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/18.webp", },
  { id: "mega-evolution-me01-019", serieId: "me01", name: "Goupix", number: "019/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/19.webp", },
  { id: "mega-evolution-me01-020", serieId: "me01", name: "Feunard", number: "020/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/20.webp", },
  { id: "mega-evolution-me01-021", serieId: "me01", name: "Chamallot", number: "021/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/21.webp", },
  { id: "mega-evolution-me01-022", serieId: "me01", name: "Méga-Camérupt-ex", number: "022/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/22.webp", },
  { id: "mega-evolution-me01-023", serieId: "me01", name: "Hélionceau", number: "023/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/23.webp", },
  { id: "mega-evolution-me01-024", serieId: "me01", name: "Némélios", number: "024/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/24.webp", },
  { id: "mega-evolution-me01-025", serieId: "me01", name: "Volcanion", number: "025/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/25.webp", },
  { id: "mega-evolution-me01-026", serieId: "me01", name: "Flambino", number: "026/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/26.webp", },
  { id: "mega-evolution-me01-027", serieId: "me01", name: "Lapyro", number: "027/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/27.webp", },
  { id: "mega-evolution-me01-028", serieId: "me01", name: "Pyrobut", number: "028/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/28.webp", },
  { id: "mega-evolution-me01-029", serieId: "me01", name: "Grillepattes", number: "029/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/29.webp", },
  { id: "mega-evolution-me01-030", serieId: "me01", name: "Scolocendre", number: "030/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/30.webp", },
  { id: "mega-evolution-me01-031", serieId: "me01", name: "Yuyu", number: "031/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/31.webp", },
  { id: "mega-evolution-me01-032", serieId: "me01", name: "Démanta", number: "032/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/32.webp", },
  { id: "mega-evolution-me01-033", serieId: "me01", name: "Écrapince", number: "033/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/33.webp", },
  { id: "mega-evolution-me01-034", serieId: "me01", name: "Kyogre", number: "034/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/34.webp", },
  { id: "mega-evolution-me01-035", serieId: "me01", name: "Blizzi", number: "035/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/35.webp", },
  { id: "mega-evolution-me01-036", serieId: "me01", name: "Méga-Blizzaroi-ex", number: "036/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/36.webp", },
  { id: "mega-evolution-me01-037", serieId: "me01", name: "Flingouste", number: "037/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/37.webp", },
  { id: "mega-evolution-me01-038", serieId: "me01", name: "Gamblast", number: "038/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/38.webp", },
  { id: "mega-evolution-me01-039", serieId: "me01", name: "Larméléon", number: "039/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/39.webp", },
  { id: "mega-evolution-me01-040", serieId: "me01", name: "Arrozard", number: "040/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/40.webp", },
  { id: "mega-evolution-me01-041", serieId: "me01", name: "Lézargus", number: "041/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/41.webp", },
  { id: "mega-evolution-me01-042", serieId: "me01", name: "Frissonille", number: "042/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/42.webp", },
  { id: "mega-evolution-me01-043", serieId: "me01", name: "Beldeneige", number: "043/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/43.webp", },
  { id: "mega-evolution-me01-044", serieId: "me01", name: "Bekaglaçon", number: "044/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/44.webp", },
  { id: "mega-evolution-me01-045", serieId: "me01", name: "Magnéti", number: "045/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/45.webp", },
  { id: "mega-evolution-me01-046", serieId: "me01", name: "Magnéton", number: "046/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/46.webp", },
  { id: "mega-evolution-me01-047", serieId: "me01", name: "Magnézone", number: "047/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/47.webp", },
  { id: "mega-evolution-me01-048", serieId: "me01", name: "Raikou", number: "048/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/48.webp", },
  { id: "mega-evolution-me01-049", serieId: "me01", name: "Dynavolt", number: "049/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/49.webp", },
  { id: "mega-evolution-me01-050", serieId: "me01", name: "Méga-Élecsprint-ex", number: "050/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/50.webp", },
  { id: "mega-evolution-me01-051", serieId: "me01", name: "Pachirisu", number: "051/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/51.webp", },
  { id: "mega-evolution-me01-052", serieId: "me01", name: "Galvaran", number: "052/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/52.webp", },
  { id: "mega-evolution-me01-053", serieId: "me01", name: "Iguolta", number: "053/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/53.webp", },
  { id: "mega-evolution-me01-054", serieId: "me01", name: "Abra", number: "054/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/54.webp", },
  { id: "mega-evolution-me01-055", serieId: "me01", name: "Kadabra", number: "055/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/55.webp", },
  { id: "mega-evolution-me01-056", serieId: "me01", name: "Alakazam", number: "056/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/56.webp", },
  { id: "mega-evolution-me01-057", serieId: "me01", name: "Lippoutou", number: "057/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/57.webp", },
  { id: "mega-evolution-me01-058", serieId: "me01", name: "Tarsal", number: "058/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/58.webp", },
  { id: "mega-evolution-me01-059", serieId: "me01", name: "Kirlia", number: "059/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/59.webp", },
  { id: "mega-evolution-me01-060", serieId: "me01", name: "Méga-Gardevoir-ex", number: "060/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/60.webp", },
  { id: "mega-evolution-me01-061", serieId: "me01", name: "Munja", number: "061/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/61.webp", },
  { id: "mega-evolution-me01-062", serieId: "me01", name: "Spoink", number: "062/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/62.webp", },
  { id: "mega-evolution-me01-063", serieId: "me01", name: "Groret", number: "063/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/63.webp", },
  { id: "mega-evolution-me01-064", serieId: "me01", name: "Xerneas", number: "064/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/64.webp", },
  { id: "mega-evolution-me01-065", serieId: "me01", name: "Toutombe", number: "065/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/65.webp", },
  { id: "mega-evolution-me01-066", serieId: "me01", name: "Tomberro", number: "066/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/66.webp", },
  { id: "mega-evolution-me01-067", serieId: "me01", name: "Mordudor", number: "067/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/67.webp", },
  { id: "mega-evolution-me01-068", serieId: "me01", name: "Sabelette", number: "068/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/68.webp", },
  { id: "mega-evolution-me01-069", serieId: "me01", name: "Sablaireau", number: "069/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/69.webp", },
  { id: "mega-evolution-me01-070", serieId: "me01", name: "Onix", number: "070/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/70.webp", },
  { id: "mega-evolution-me01-071", serieId: "me01", name: "Debugant", number: "071/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/71.webp", },
  { id: "mega-evolution-me01-072", serieId: "me01", name: "Makuhita", number: "072/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/72.webp", },
  { id: "mega-evolution-me01-073", serieId: "me01", name: "Hariyama", number: "073/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/73.webp", },
  { id: "mega-evolution-me01-074", serieId: "me01", name: "Séléroc", number: "074/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/74.webp", },
  { id: "mega-evolution-me01-075", serieId: "me01", name: "Solaroc", number: "075/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/75.webp", },
  { id: "mega-evolution-me01-076", serieId: "me01", name: "Riolu", number: "076/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/76.webp", },
  { id: "mega-evolution-me01-077", serieId: "me01", name: "Méga-Lucario-ex", number: "077/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/77.webp", },
  { id: "mega-evolution-me01-078", serieId: "me01", name: "Cradopaud", number: "078/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/78.webp", },
  { id: "mega-evolution-me01-079", serieId: "me01", name: "Coatox", number: "079/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/79.webp", },
  { id: "mega-evolution-me01-080", serieId: "me01", name: "Marshadow", number: "080/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/80.webp", },
  { id: "mega-evolution-me01-081", serieId: "me01", name: "Dolman", number: "081/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/81.webp", },
  { id: "mega-evolution-me01-082", serieId: "me01", name: "Selutin", number: "082/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/82.webp", },
  { id: "mega-evolution-me01-083", serieId: "me01", name: "Amassel", number: "083/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/83.webp", },
  { id: "mega-evolution-me01-084", serieId: "me01", name: "Gigansel", number: "084/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/84.webp", },
  { id: "mega-evolution-me01-085", serieId: "me01", name: "Colhomard", number: "085/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/85.webp", },
  { id: "mega-evolution-me01-086", serieId: "me01", name: "Méga-Absol-ex", number: "086/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/86.webp", },
  { id: "mega-evolution-me01-087", serieId: "me01", name: "Spiritomb", number: "087/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/87.webp", },
  { id: "mega-evolution-me01-088", serieId: "me01", name: "Yveltal", number: "088/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/88.webp", },
  { id: "mega-evolution-me01-089", serieId: "me01", name: "Goupilou", number: "089/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/89.webp", },
  { id: "mega-evolution-me01-090", serieId: "me01", name: "Roublenard", number: "090/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/90.webp", },
  { id: "mega-evolution-me01-091", serieId: "me01", name: "Gribouraigne", number: "091/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/91.webp", },
  { id: "mega-evolution-me01-092", serieId: "me01", name: "Tag-Tag", number: "092/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/92.webp", },
  { id: "mega-evolution-me01-093", serieId: "me01", name: "Steelix", number: "093/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/93.webp", },
  { id: "mega-evolution-me01-094", serieId: "me01", name: "Méga-Mysdibule-ex", number: "094/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/94.webp", },
  { id: "mega-evolution-me01-095", serieId: "me01", name: "Dialga", number: "095/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/95.webp", },
  { id: "mega-evolution-me01-096", serieId: "me01", name: "Forgerette", number: "096/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/96.webp", },
  { id: "mega-evolution-me01-097", serieId: "me01", name: "Forgella", number: "097/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/97.webp", },
  { id: "mega-evolution-me01-098", serieId: "me01", name: "Forgelina", number: "098/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/98.webp", },
  { id: "mega-evolution-me01-099", serieId: "me01", name: "Gromago", number: "099/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/99.webp", },
  { id: "mega-evolution-me01-100", serieId: "me01", name: "Méga-Latias-ex", number: "100/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/100.webp", },
  { id: "mega-evolution-me01-101", serieId: "me01", name: "Latios", number: "101/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/101.webp", },
  { id: "mega-evolution-me01-102", serieId: "me01", name: "Piafabec", number: "102/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/102.webp", },
  { id: "mega-evolution-me01-103", serieId: "me01", name: "Rapasdepic", number: "103/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/103.webp", },
  { id: "mega-evolution-me01-104", serieId: "me01", name: "Méga-Kangourex-ex", number: "104/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/104.webp", },
  { id: "mega-evolution-me01-105", serieId: "me01", name: "Cadoizo", number: "105/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/105.webp", },
  { id: "mega-evolution-me01-106", serieId: "me01", name: "Écrémeuh", number: "106/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/106.webp", },
  { id: "mega-evolution-me01-107", serieId: "me01", name: "Laporeille", number: "107/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/107.webp", },
  { id: "mega-evolution-me01-108", serieId: "me01", name: "Lockpin", number: "108/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/108.webp", },
  { id: "mega-evolution-me01-109", serieId: "me01", name: "Manglouton", number: "109/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/109.webp", },
  { id: "mega-evolution-me01-110", serieId: "me01", name: "Argouste", number: "110/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/110.webp", },
  { id: "mega-evolution-me01-111", serieId: "me01", name: "Nounourson", number: "111/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/111.webp", },
  { id: "mega-evolution-me01-112", serieId: "me01", name: "Chelours", number: "112/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/112.webp", },
  { id: "mega-evolution-me01-113", serieId: "me01", name: "Espièglerie de Margie", number: "113/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/113.webp", },
  { id: "mega-evolution-me01-114", serieId: "me01", name: "Ordres du Boss", number: "114/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/114.webp", },
  { id: "mega-evolution-me01-115", serieId: "me01", name: "Échange d'Énergie", number: "115/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/115.webp", },
  { id: "mega-evolution-me01-116", serieId: "me01", name: "Gong de Combat", number: "116/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/116.webp", },
  { id: "mega-evolution-me01-117", serieId: "me01", name: "Forêt de Vitalité", number: "117/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/117.webp", },
  { id: "mega-evolution-me01-118", serieId: "me01", name: "Défense de Fer", number: "118/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/118.webp", },
  { id: "mega-evolution-me01-119", serieId: "me01", name: "Détermination de Lilie", number: "119/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/119.webp", },
  { id: "mega-evolution-me01-120", serieId: "me01", name: "Négociation de Major Bob", number: "120/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/120.webp", },
  { id: "mega-evolution-me01-121", serieId: "me01", name: "Méga Signal", number: "121/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/121.webp", },
  { id: "mega-evolution-me01-122", serieId: "me01", name: "Jardin Mystère", number: "122/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/122.webp", },
  { id: "mega-evolution-me01-123", serieId: "me01", name: "Dame du Centre Pokémon", number: "123/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/123.webp", },
  { id: "mega-evolution-me01-124", serieId: "me01", name: "Puissance Premium Pro", number: "124/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/124.webp", },
  { id: "mega-evolution-me01-125", serieId: "me01", name: "Super Bonbon", number: "125/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/125.webp", },
  { id: "mega-evolution-me01-126", serieId: "me01", name: "Repousse", number: "126/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/126.webp", },
  { id: "mega-evolution-me01-127", serieId: "me01", name: "Ruines Risquées", number: "127/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/127.webp", },
  { id: "mega-evolution-me01-128", serieId: "me01", name: "Compteur de Temps Étrange", number: "128/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/128.webp", },
  { id: "mega-evolution-me01-129", serieId: "me01", name: "Plage de Surf", number: "129/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/129.webp", },
  { id: "mega-evolution-me01-130", serieId: "me01", name: "Échange", number: "130/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/130.webp", },
  { id: "mega-evolution-me01-131", serieId: "me01", name: "Hyper Ball", number: "131/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/131.webp", },
  { id: "mega-evolution-me01-132", serieId: "me01", name: "Compassion de Timmy", number: "132/132", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/132.webp", },
  { id: "mega-evolution-me01-133", serieId: "me01", name: "Bulbizarre", number: "133/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/133.webp", },
  { id: "mega-evolution-me01-134", serieId: "me01", name: "Herbizarre", number: "134/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/134.webp", },
  { id: "mega-evolution-me01-135", serieId: "me01", name: "Noadkoko", number: "135/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/135.webp", },
  { id: "mega-evolution-me01-136", serieId: "me01", name: "Caratroc", number: "136/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/136.webp", },
  { id: "mega-evolution-me01-137", serieId: "me01", name: "Ninjask", number: "137/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/137.webp", },
  { id: "mega-evolution-me01-138", serieId: "me01", name: "Goupix", number: "138/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/138.webp", },
  { id: "mega-evolution-me01-139", serieId: "me01", name: "Hélionceau", number: "139/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/139.webp", },
  { id: "mega-evolution-me01-140", serieId: "me01", name: "Blizzi", number: "140/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/140.webp", },
  { id: "mega-evolution-me01-141", serieId: "me01", name: "Gamblast", number: "141/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/141.webp", },
  { id: "mega-evolution-me01-142", serieId: "me01", name: "Lézargus", number: "142/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/142.webp", },
  { id: "mega-evolution-me01-143", serieId: "me01", name: "Galvaran", number: "143/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/143.webp", },
  { id: "mega-evolution-me01-144", serieId: "me01", name: "Munja", number: "144/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/144.webp", },
  { id: "mega-evolution-me01-145", serieId: "me01", name: "Tomberro", number: "145/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/145.webp", },
  { id: "mega-evolution-me01-146", serieId: "me01", name: "Marshadow", number: "146/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/146.webp", },
  { id: "mega-evolution-me01-147", serieId: "me01", name: "Gigansel", number: "147/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/147.webp", },
  { id: "mega-evolution-me01-148", serieId: "me01", name: "Spiritomb", number: "148/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/148.webp", },
  { id: "mega-evolution-me01-149", serieId: "me01", name: "Gribouraigne", number: "149/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/149.webp", },
  { id: "mega-evolution-me01-150", serieId: "me01", name: "Steelix", number: "150/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/150.webp", },
  { id: "mega-evolution-me01-151", serieId: "me01", name: "Piafabec", number: "151/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/151.webp", },
  { id: "mega-evolution-me01-152", serieId: "me01", name: "Cadoizo", number: "152/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/152.webp", },
  { id: "mega-evolution-me01-153", serieId: "me01", name: "Argouste", number: "153/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/153.webp", },
  { id: "mega-evolution-me01-154", serieId: "me01", name: "Nounourson", number: "154/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/154.webp", },
  { id: "mega-evolution-me01-155", serieId: "me01", name: "Méga-Florizarre-ex", number: "155/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/155.webp", },
  { id: "mega-evolution-me01-156", serieId: "me01", name: "Méga-Camérupt-ex", number: "156/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/156.webp", },
  { id: "mega-evolution-me01-157", serieId: "me01", name: "Méga-Blizzaroi-ex", number: "157/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/157.webp", },
  { id: "mega-evolution-me01-158", serieId: "me01", name: "Méga-Élecsprint-ex", number: "158/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/158.webp", },
  { id: "mega-evolution-me01-159", serieId: "me01", name: "Méga-Gardevoir-ex", number: "159/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/159.webp", },
  { id: "mega-evolution-me01-160", serieId: "me01", name: "Méga-Lucario-ex", number: "160/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/160.webp", },
  { id: "mega-evolution-me01-161", serieId: "me01", name: "Méga-Absol-ex", number: "161/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/161.webp", },
  { id: "mega-evolution-me01-162", serieId: "me01", name: "Méga-Mysdibule-ex", number: "162/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/162.webp", },
  { id: "mega-evolution-me01-163", serieId: "me01", name: "Méga-Latias-ex", number: "163/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/163.webp", },
  { id: "mega-evolution-me01-164", serieId: "me01", name: "Méga-Kangourex-ex", number: "164/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/164.webp", },
  { id: "mega-evolution-me01-165", serieId: "me01", name: "Espièglerie de Margie", number: "165/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/165.webp", },
  { id: "mega-evolution-me01-166", serieId: "me01", name: "Ballon", number: "166/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/166.webp", },
  { id: "mega-evolution-me01-167", serieId: "me01", name: "Poffin Copain-Copain", number: "167/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/167.webp", },
  { id: "mega-evolution-me01-168", serieId: "me01", name: "Gong de Combat", number: "168/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/168.webp", },
  { id: "mega-evolution-me01-169", serieId: "me01", name: "Détermination de Lilie", number: "169/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/169.webp", },
  { id: "mega-evolution-me01-170", serieId: "me01", name: "Négociation de Major Bob", number: "170/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/170.webp", },
  { id: "mega-evolution-me01-171", serieId: "me01", name: "Méga Signal", number: "171/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/171.webp", },
  { id: "mega-evolution-me01-172", serieId: "me01", name: "Jardin Mystère", number: "172/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/172.webp", },
  { id: "mega-evolution-me01-173", serieId: "me01", name: "Civière Nocturne", number: "173/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/173.webp", },
  { id: "mega-evolution-me01-174", serieId: "me01", name: "Puissance Premium Pro", number: "174/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/174.webp", },
  { id: "mega-evolution-me01-175", serieId: "me01", name: "Super Bonbon", number: "175/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/175.webp", },
  { id: "mega-evolution-me01-176", serieId: "me01", name: "Compassion de Timmy", number: "176/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/176.webp", },
  { id: "mega-evolution-me01-177", serieId: "me01", name: "Méga-Florizarre-ex", number: "177/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/177.webp", },
  { id: "mega-evolution-me01-178", serieId: "me01", name: "Méga-Gardevoir-ex", number: "178/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/178.webp", },
  { id: "mega-evolution-me01-179", serieId: "me01", name: "Méga-Lucario-ex", number: "179/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/179.webp", },
  { id: "mega-evolution-me01-180", serieId: "me01", name: "Méga-Absol-ex", number: "180/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/180.webp", },
  { id: "mega-evolution-me01-181", serieId: "me01", name: "Méga-Latias-ex", number: "181/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/181.webp", },
  { id: "mega-evolution-me01-182", serieId: "me01", name: "Méga-Kangourex-ex", number: "182/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/182.webp", },
  { id: "mega-evolution-me01-183", serieId: "me01", name: "Espièglerie de Margie", number: "183/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/183.webp", },
  { id: "mega-evolution-me01-184", serieId: "me01", name: "Détermination de Lilie", number: "184/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/184.webp", },
  { id: "mega-evolution-me01-185", serieId: "me01", name: "Négociation de Major Bob", number: "185/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/185.webp", },
  { id: "mega-evolution-me01-186", serieId: "me01", name: "Compassion de Timmy", number: "186/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/186.webp", },
  { id: "mega-evolution-me01-187", serieId: "me01", name: "Méga-Gardevoir-ex", number: "187/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/187.webp", },
  { id: "mega-evolution-me01-188", serieId: "me01", name: "Méga-Lucario-ex", number: "188/132", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/me01/188.webp", },
  
] as unknown as Card[]);
