import type { Card } from "../../catalog";

// epee-et-bouclier - 2966 cards
export const MEGA_EVOLUTION_CARDS = ([
  { id: "mega-evolution-001", serieId: "me-promo", name: "Méganium", number: "001", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/1.webp",},
  { id: "mega-evolution-002", serieId: "me-promo", name: "Lézargus ", number: "002", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/2.webp",},
  { id: "mega-evolution-003", serieId: "me-promo", name: "Alakazam ", number: "003", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/3.webp",},
  { id: "mega-evolution-004", serieId: "me-promo", name: "Séléroc ", number: "004", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/4.webp",},
  { id: "mega-evolution-005", serieId: "me-promo", name: "Baudrive ", number: "005", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/5.webp",},
  { id: "mega-evolution-006", serieId: "me-promo", name: "Grodrive ", number: "006", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/6.webp",},
  { id: "mega-evolution-007", serieId: "me-promo", name: "Psykokwak ", number: "007", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/7.webp",},
  { id: "mega-evolution-008", serieId: "me-promo", name: "Akwakwak ", number: "008", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/8.webp",},
  { id: "mega-evolution-009", serieId: "me-promo", name: "Alakazam ", number: "009", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/9.webp",},
  { id: "mega-evolution-010", serieId: "me-promo", name: "Riolu ", number: "010", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/10.webp",},
  { id: "mega-evolution-011", serieId: "me-promo", name: "Méga-Latias ex ", number: "011", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/11.webp",},
  { id: "mega-evolution-012", serieId: "me-promo", name: "Méga-Lucario ex ", number: "012", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/12.webp",},
  { id: "mega-evolution-013", serieId: "me-promo", name: "Méga-Florizarre ex ", number: "013", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/13.webp",},
  { id: "mega-evolution-014", serieId: "me-promo", name: "Malvalame ", number: "014", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/14.webp",},
  { id: "mega-evolution-015", serieId: "me-promo", name: "Zacian ", number: "015", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/15.webp",},
  { id: "mega-evolution-016", serieId: "me-promo", name: "Libégon ", number: "016", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/16.webp",},
  { id: "mega-evolution-017", serieId: "me-promo", name: "Salarsen ", number: "017", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/17.webp",},
  { id: "mega-evolution-018", serieId: "me-promo", name: "Doudouvet ", number: "018", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/18.webp",},
  { id: "mega-evolution-019", serieId: "me-promo", name: "Farfaduvet ", number: "019", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/19.webp",},
  { id: "mega-evolution-020", serieId: "me-promo", name: "Farfuret ", number: "020", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/20.webp",},
  { id: "mega-evolution-021", serieId: "me-promo", name: "Dimoret ", number: "021", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/21.webp",},
  { id: "mega-evolution-022", serieId: "me-promo", name: "Charbambin ", number: "022", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/22.webp",},
  { id: "mega-evolution-023", serieId: "me-promo", name: "Méga-Dracaufeu X ex ", number: "023", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/23.webp",},
  { id: "mega-evolution-024", serieId: "me-promo", name: "Plumeline ex ", number: "024", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/24.webp",},
  { id: "mega-evolution-025", serieId: "me-promo", name: "Méga-Kangourex ex ", number: "025", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/25.webp",},
  { id: "mega-evolution-026", serieId: "me-promo", name: "Meloetta ", number: "026", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/26.webp",},
  { id: "mega-evolution-027", serieId: "me-promo", name: "Spectrum ", number: "027", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/27.webp",},
  { id: "mega-evolution-028", serieId: "me-promo", name: "Celebratory Fanfare ", number: "028", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/28.webp",},
  { id: "mega-evolution-029", serieId: "me-promo", name: "Méga-Dracaufeu X ex ", number: "029", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/29.webp",},
  { id: "mega-evolution-030", serieId: "me-promo", name: "Méga-Dracaufeu Y ex ", number: "030", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/30.webp",},
  { id: "mega-evolution-031", serieId: "me-promo", name: "Zekrom de N ", number: "031", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/31.webp",},
  { id: "mega-evolution-032", serieId: "me-promo", name: "Méga-Gardevoir ex ", number: "032", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/32.webp",},
  { id: "mega-evolution-033", serieId: "me-promo", name: "Méga-Lucario ex ", number: "033", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/33.webp",},
  { id: "mega-evolution-034", serieId: "me-promo", name: "Méga-Méganium ex ", number: "034", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/34.webp",},
  { id: "mega-evolution-035", serieId: "me-promo", name: "Méga-Roitiflam ex ", number: "035", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/35.webp",},
  { id: "mega-evolution-036", serieId: "me-promo", name: "Méga-Aligatueur ex ", number: "036", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/36.webp",},
  { id: "mega-evolution-037", serieId: "me-promo", name: "Bulbizarre ", number: "037", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/37.webp",},
  { id: "mega-evolution-038", serieId: "me-promo", name: "Salamèche ", number: "038", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/38.webp",},
  { id: "mega-evolution-039", serieId: "me-promo", name: "Carapuce ", number: "039", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/39.webp",},
  { id: "mega-evolution-040", serieId: "me-promo", name: "Tortipouss ", number: "040", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/40.webp",},
  { id: "mega-evolution-041", serieId: "me-promo", name: "Ouisticram ", number: "041", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/41.webp",},
  { id: "mega-evolution-042", serieId: "me-promo", name: "Tiplouf ", number: "042", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/42.webp",},
  { id: "mega-evolution-043", serieId: "me-promo", name: "Brindibou ", number: "043", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/43.webp",},
  { id: "mega-evolution-044", serieId: "me-promo", name: "Flamiaou ", number: "044", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/44.webp",},
  { id: "mega-evolution-045", serieId: "me-promo", name: "Otaquin ", number: "045", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/45.webp",},
  { id: "mega-evolution-064", serieId: "me-promo", name: "Majaspic ", number: "064", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/64.webp",},
  { id: "mega-evolution-065", serieId: "me-promo", name: "Golgopathe ", number: "065", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/65.webp",},
  { id: "mega-evolution-066", serieId: "me-promo", name: "Rexillius ", number: "066", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/66.webp",},
  { id: "mega-evolution-067", serieId: "me-promo", name: "Dimoclès ", number: "067", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/67.webp",},
  { id: "mega-evolution-068", serieId: "me-promo", name: "Makuhita ", number: "068", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/68.webp",},
  { id: "mega-evolution-069", serieId: "me-promo", name: "Germignon ", number: "069", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/69.webp",},
  { id: "mega-evolution-070", serieId: "me-promo", name: "Ptyranidur ", number: "070", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/70.webp",},
  { id: "mega-evolution-071", serieId: "me-promo", name: "Méga-Zygarde ex  ", number: "071", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/71.webp",},
  { id: "mega-evolution-074", serieId: "me-promo", name: "Goupelin  ", number: "074", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/74.webp",},
  { id: "mega-evolution-075", serieId: "me-promo", name: "Pharamp  ", number: "075", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/75.webp",},
  { id: "mega-evolution-076", serieId: "me-promo", name: "Nostenfer  ", number: "076", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/76.webp",},
  { id: "mega-evolution-077", serieId: "me-promo", name: "Muplodocus  ", number: "077", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/77.webp",},
  { id: "mega-evolution-081", serieId: "me-promo", name: "Méga-Amphinobi ex  ", number: "081", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/mep/81.webp",},
  
] as unknown as Card[]);
