import type { Card } from "../../catalog";

// Noir et Blanc
export const NOIR_ET_BLANC_CARDS = ([
{ id: "prbw-001", serieId: "prbw", name: "Vipélierre", number: "BW01", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/1.webp", },
{ id: "prbw-002", serieId: "prbw", name: "Gruikui", number: "BW02", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/2.webp", },
{ id: "prbw-003", serieId: "prbw", name: "Moustillon", number: "BW03", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/3.webp", },
{ id: "prbw-004", serieId: "prbw", name: "Reshiram", number: "BW004", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/4.webp", },
{ id: "prbw-005", serieId: "prbw", name: "Zekrom", number: "BW005", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/5.webp", },
{ id: "prbw-006", serieId: "prbw", name: "Vipélierre", number: "BW06", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/6.webp", },
{ id: "prbw-007", serieId: "prbw", name: "Gruikui", number: "BW07", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/7.webp", },
{ id: "prbw-008", serieId: "prbw", name: "Moustillon", number: "BW08", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/8.webp", },
{ id: "prbw-009", serieId: "prbw", name: "Zoroark", number: "BW09", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/9.webp", },
{ id: "prbw-010", serieId: "prbw", name: "Coupenotte", number: "BW10", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/10.webp", },
{ id: "prbw-011", serieId: "prbw", name: "Feuillajou", number: "BW11", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/11.webp", },
{ id: "prbw-012", serieId: "prbw", name: "Zorua", number: "BW12", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/12.webp", },
{ id: "prbw-013", serieId: "prbw", name: "Chinchidou", number: "BW13", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/13.webp", },
{ id: "prbw-014", serieId: "prbw", name: "Feuillajou", number: "BW14", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/14.webp", },
{ id: "prbw-015", serieId: "prbw", name: "Poichigeon", number: "BW15", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/15.webp", },
{ id: "prbw-016", serieId: "prbw", name: "Coupenotte", number: "BW16", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/16.webp", },
{ id: "prbw-017", serieId: "prbw", name: "Couaneton", number: "BW17", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/17.webp", },
{ id: "prbw-018", serieId: "prbw", name: "Darumarond", number: "BW18", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/18.webp", },
{ id: "prbw-019", serieId: "prbw", name: "Zoroark", number: "BW19", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/19.webp", },
{ id: "prbw-020", serieId: "prbw", name: "Majaspic", number: "BW20", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/20.webp", },
{ id: "prbw-021", serieId: "prbw", name: "Roitiflam", number: "BW21", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/21.webp", },
{ id: "prbw-022", serieId: "prbw", name: "Clamiral", number: "BW22", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/22.webp", },
{ id: "prbw-023", serieId: "prbw", name: "Reshiram", number: "BW23", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/23.webp", },
{ id: "prbw-024", serieId: "prbw", name: "Zekrom", number: "BW24", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/24.webp", },
{ id: "prbw-025", serieId: "prbw", name: "Baggiguane", number: "BW25", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/25.webp", },
{ id: "prbw-026", serieId: "prbw", name: "Coupenotte", number: "BW26", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/26.webp", },
{ id: "prbw-027", serieId: "prbw", name: "Funécire", number: "BW27", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/27.webp", },
{ id: "prbw-028", serieId: "prbw", name: "Plage Tropicale", number: "BW28", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/28.webp", },
{ id: "prbw-029", serieId: "prbw", name: "Coupe Victoire", number: "BW29", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/29.webp", },
{ id: "prbw-030", serieId: "prbw", name: "Coupe Victoire", number: "BW30", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/30.webp", },
{ id: "prbw-031", serieId: "prbw", name: "Coupe Victoire", number: "BW31", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/31.webp", },
{ id: "prbw-032", serieId: "prbw", name: "Victini", number: "BW32", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/32.webp", },
{ id: "prbw-033", serieId: "prbw", name: "Riolu", number: "BW33", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/33.webp", },
{ id: "prbw-034", serieId: "prbw", name: "Luxio", number: "BW34", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/34.webp", },
{ id: "prbw-035", serieId: "prbw", name: "Miaouss", number: "BW35", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/35.webp", },
{ id: "prbw-036", serieId: "prbw", name: "Reshiram-EX", number: "BW36", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/36.webp", },
{ id: "prbw-037", serieId: "prbw", name: "Kyurem-EX", number: "BW37", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/37.webp", },
{ id: "prbw-038", serieId: "prbw", name: "Zekrom-EX", number: "BW38", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/38.webp", },
{ id: "prbw-039", serieId: "prbw", name: "Ville Combat", number: "BW39", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/39.webp", },
{ id: "prbw-040", serieId: "prbw", name: "Pyrax", number: "BW40", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/40.webp", },
{ id: "prbw-041", serieId: "prbw", name: "Fulguris", number: "BW41", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/41.webp", },
{ id: "prbw-042", serieId: "prbw", name: "Boréas", number: "BW42", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/42.webp", },
{ id: "prbw-043", serieId: "prbw", name: "Démétéros", number: "BW43", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/43.webp", },
{ id: "prbw-044", serieId: "prbw", name: "Kyurem", number: "BW44", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/44.webp", },
{ id: "prbw-045", serieId: "prbw", name: "Mewtwo-EX", number: "BW45", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/45.webp", },
{ id: "prbw-046", serieId: "prbw", name: "Darkrai-EX", number: "BW46", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/46.webp", },
{ id: "prbw-047", serieId: "prbw", name: "Rayquaza-EX", number: "BW47", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/47.webp", },
{ id: "prbw-048", serieId: "prbw", name: "Altaria", number: "BW48", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/48.webp", },
{ id: "prbw-049", serieId: "prbw", name: "Fragilady", number: "BW49", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/49.webp", },
{ id: "prbw-050", serieId: "prbw", name: "Plage Tropicale", number: "BW50", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/50.webp", },
{ id: "prbw-051", serieId: "prbw", name: "Nostenfer", number: "BW51", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/51.webp", },
{ id: "prbw-052", serieId: "prbw", name: "Ponchiot", number: "BW52", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/52.webp", },
{ id: "prbw-053", serieId: "prbw", name: "Libégon", number: "BW53", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/53.webp", },
{ id: "prbw-054", serieId: "prbw", name: "Pikachu", number: "BW54", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/54.webp", },
{ id: "prbw-055", serieId: "prbw", name: "Lewsor", number: "BW55", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/55.webp", },
{ id: "prbw-056", serieId: "prbw", name: "Pingoléon", number: "BW56", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/56.webp", },
{ id: "prbw-057", serieId: "prbw", name: "Tranchodon", number: "BW57", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/57.webp", },
{ id: "prbw-058", serieId: "prbw", name: "Kyurem Noir", number: "BW58", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/58.webp", },
{ id: "prbw-059", serieId: "prbw", name: "Kyurem Blanc", number: "BW59", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/59.webp", },
{ id: "prbw-060", serieId: "prbw", name: "Keldeo", number: "BW60", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/60.webp", },
{ id: "prbw-061", serieId: "prbw", name: "Keldeo-EX", number: "BW61", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/61.webp", },
{ id: "prbw-062", serieId: "prbw", name: "Kyurem Noir-EX", number: "BW62", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/62.webp", },
{ id: "prbw-063", serieId: "prbw", name: "Kyurem Blanc-EX", number: "BW63", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/63.webp", },
{ id: "prbw-064", serieId: "prbw", name: "Grodrive", number: "BW64", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/64.webp", },
{ id: "prbw-065", serieId: "prbw", name: "Rondoudou", number: "BW65", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/65.webp", },
{ id: "prbw-066", serieId: "prbw", name: "Feunard", number: "BW66", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/66.webp", },
{ id: "prbw-067", serieId: "prbw", name: "Pharamp", number: "BW67", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/67.webp", },
{ id: "prbw-068", serieId: "prbw", name: "Meloetta", number: "BW68", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/68.webp", },
{ id: "prbw-069", serieId: "prbw", name: "Meloetta", number: "BW69", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/69.webp", },
{ id: "prbw-070", serieId: "prbw", name: "Viridium", number: "BW70", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/70.webp", },
{ id: "prbw-071", serieId: "prbw", name: "Terrakium", number: "BW71", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/71.webp", },
{ id: "prbw-072", serieId: "prbw", name: "Cobaltium", number: "BW72", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/72.webp", },
{ id: "prbw-073", serieId: "prbw", name: "Darkrai", number: "BW73", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/73.webp", },
{ id: "prbw-074", serieId: "prbw", name: "Giratina", number: "BW74", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/74.webp", },
{ id: "prbw-075", serieId: "prbw", name: "Métalosse", number: "BW75", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/75.webp", },
{ id: "prbw-076", serieId: "prbw", name: "Électrode", number: "BW76", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/76.webp", },
{ id: "prbw-077", serieId: "prbw", name: "Pikachu", number: "BW77", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/77.webp", },
{ id: "prbw-078", serieId: "prbw", name: "Raichu", number: "BW78", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/78.webp", },
{ id: "prbw-079", serieId: "prbw", name: "Démétéros", number: "BW79", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/79.webp", },
{ id: "prbw-080", serieId: "prbw", name: "Drakkarmin", number: "BW80", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/80.webp", },
{ id: "prbw-081", serieId: "prbw", name: "Fulguris-EX", number: "BW81", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/81.webp", },
{ id: "prbw-082", serieId: "prbw", name: "Deoxys-EX", number: "BW82", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/82.webp", },
{ id: "prbw-083", serieId: "prbw", name: "Lugia-EX", number: "BW83", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/83.webp", },
{ id: "prbw-084", serieId: "prbw", name: "Porygon-Z", number: "BW84", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/84.webp", },
{ id: "prbw-085", serieId: "prbw", name: "Lucario", number: "BW85", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/85.webp", },
{ id: "prbw-086", serieId: "prbw", name: "Genesect", number: "BW86", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/86.webp", },
{ id: "prbw-087", serieId: "prbw", name: "Phyllali", number: "BW87", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/87.webp", },
{ id: "prbw-088", serieId: "prbw", name: "Pyroli", number: "BW88", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/88.webp", },
{ id: "prbw-089", serieId: "prbw", name: "Aquali", number: "BW89", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/89.webp", },
{ id: "prbw-090", serieId: "prbw", name: "Givrali", number: "BW90", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/90.webp", },
{ id: "prbw-091", serieId: "prbw", name: "Voltali", number: "BW91", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/91.webp", },
{ id: "prbw-092", serieId: "prbw", name: "Mentali", number: "BW92", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/92.webp", },
{ id: "prbw-093", serieId: "prbw", name: "Noctali", number: "BW93", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/93.webp", },
{ id: "prbw-094", serieId: "prbw", name: "Évoli", number: "BW94", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/94.webp", },
{ id: "prbw-095", serieId: "prbw", name: "Festival des Champions", number: "BW95", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/95.webp", },
{ id: "prbw-096", serieId: "prbw", name: "Boréas-EX", number: "BW96", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/96.webp", },
{ id: "prbw-097", serieId: "prbw", name: "Évoli", number: "BW97", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/97.webp", },
{ id: "prbw-098", serieId: "prbw", name: "Mew", number: "BW98", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/98.webp", },
{ id: "prbw-099", serieId: "prbw", name: "Genesect", number: "BW99", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/99.webp", },
{ id: "prbw-100", serieId: "prbw", name: "N", number: "BW100", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/100.webp", },
{ id: "prbw-101", serieId: "prbw", name: "Genesect", number: "BW101", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/101.webp", },


// NB01
{ id: "nb01-001", serieId: "nb01", name: "Vipélierre", number: "001/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/1.webp", },
{ id: "nb01-002", serieId: "nb01", name: "Vipélierre ", number: "002/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/2.webp", },
{ id: "nb01-003", serieId: "nb01", name: "Lianaja ", number: "003/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/3.webp", },
{ id: "nb01-004", serieId: "nb01", name: "Lianaja ", number: "004/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/4.webp", },
{ id: "nb01-005", serieId: "nb01", name: "Majaspic ", number: "005/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/5.webp", },
{ id: "nb01-006", serieId: "nb01", name: "Majaspic ", number: "006/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/6.webp", },
{ id: "nb01-007", serieId: "nb01", name: "Feuillajou ", number: "007/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/7.webp", },
{ id: "nb01-008", serieId: "nb01", name: "Feuiloutan ", number: "008/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/8.webp", },
{ id: "nb01-009", serieId: "nb01", name: "Chlorobule ", number: "009/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/9.webp", },
{ id: "nb01-010", serieId: "nb01", name: "Fragilady ", number: "010/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/10.webp", },
{ id: "nb01-011", serieId: "nb01", name: "Maracachi ", number: "011/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/11.webp", },
{ id: "nb01-012", serieId: "nb01", name: "Maracachi ", number: "012/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/12.webp", },
{ id: "nb01-013", serieId: "nb01", name: "Vivaldaim ", number: "013/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/13.webp", },
{ id: "nb01-014", serieId: "nb01", name: "Haydaim ", number: "014/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/14.webp", },
{ id: "nb01-015", serieId: "nb01", name: "Gruikui ", number: "015/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/15.webp", },
{ id: "nb01-016", serieId: "nb01", name: "Gruikui ", number: "016/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/16.webp", },
{ id: "nb01-017", serieId: "nb01", name: "Grotichon ", number: "017/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/17.webp", },
{ id: "nb01-018", serieId: "nb01", name: "Grotichon ", number: "018/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/18.webp", },
{ id: "nb01-019", serieId: "nb01", name: "Roitiflam ", number: "019/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/19.webp", },
{ id: "nb01-020", serieId: "nb01", name: "Roitiflam ", number: "020/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/20.webp", },
{ id: "nb01-021", serieId: "nb01", name: "Flamajou ", number: "021/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/21.webp", },
{ id: "nb01-022", serieId: "nb01", name: "Flamoutan ", number: "022/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/22.webp", },
{ id: "nb01-023", serieId: "nb01", name: "Darumarond ", number: "023/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/23.webp", },
{ id: "nb01-024", serieId: "nb01", name: "Darumarond ", number: "024/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/24.webp", },
{ id: "nb01-025", serieId: "nb01", name: "Darumacho ", number: "025/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/25.webp", },
{ id: "nb01-026", serieId: "nb01", name: "Reshiram ", number: "026/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/26.webp", },
{ id: "nb01-027", serieId: "nb01", name: "Moustillon ", number: "027/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/27.webp", },
{ id: "nb01-028", serieId: "nb01", name: "Moustillon ", number: "028/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/28.webp", },
{ id: "nb01-029", serieId: "nb01", name: "Mateloutre ", number: "029/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/29.webp", },
{ id: "nb01-030", serieId: "nb01", name: "Mateloutre ", number: "030/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/30.webp", },
{ id: "nb01-031", serieId: "nb01", name: "Clamiral ", number: "031/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/31.webp", },
{ id: "nb01-032", serieId: "nb01", name: "Clamiral ", number: "032/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/32.webp", },
{ id: "nb01-033", serieId: "nb01", name: "Flotajou ", number: "033/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/33.webp", },
{ id: "nb01-034", serieId: "nb01", name: "Flotoutan ", number: "034/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/34.webp", },
{ id: "nb01-035", serieId: "nb01", name: "Bargantua ", number: "035/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/35.webp", },
{ id: "nb01-036", serieId: "nb01", name: "Couaneton ", number: "036/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/36.webp", },
{ id: "nb01-037", serieId: "nb01", name: "Lakmécygne ", number: "037/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/37.webp", },
{ id: "nb01-038", serieId: "nb01", name: "Mamanbo ", number: "038/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/38.webp", },
{ id: "nb01-039", serieId: "nb01", name: "Mamanbo ", number: "039/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/39.webp", },
{ id: "nb01-040", serieId: "nb01", name: "Zébibron ", number: "040/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/40.webp", },
{ id: "nb01-041", serieId: "nb01", name: "Zébibron ", number: "041/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/41.webp", },
{ id: "nb01-042", serieId: "nb01", name: "Zéblitz ", number: "042/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/42.webp", },
{ id: "nb01-043", serieId: "nb01", name: "Zéblitz ", number: "043/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/43.webp", },
{ id: "nb01-044", serieId: "nb01", name: "Statitik ", number: "044/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/44.webp", },
{ id: "nb01-045", serieId: "nb01", name: "Statitik ", number: "045/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/45.webp", },
{ id: "nb01-046", serieId: "nb01", name: "Mygavolt ", number: "046/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/46.webp", },
{ id: "nb01-047", serieId: "nb01", name: "Zekrom ", number: "047/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/47.webp", },
{ id: "nb01-048", serieId: "nb01", name: "Munna ", number: "048/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/48.webp", },
{ id: "nb01-049", serieId: "nb01", name: "Mushana ", number: "049/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/49.webp", },
{ id: "nb01-050", serieId: "nb01", name: "Chovsourir ", number: "050/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/50.webp", },
{ id: "nb01-051", serieId: "nb01", name: "Rhinolove ", number: "051/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/51.webp", },
{ id: "nb01-052", serieId: "nb01", name: "Venipatte ", number: "052/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/52.webp", },
{ id: "nb01-053", serieId: "nb01", name: "Scobolide ", number: "053/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/53.webp", },
{ id: "nb01-054", serieId: "nb01", name: "Brutapode ", number: "054/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/54.webp", },
{ id: "nb01-055", serieId: "nb01", name: "Nucléos ", number: "055/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/55.webp", },
{ id: "nb01-056", serieId: "nb01", name: "Méios ", number: "056/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/56.webp", },
{ id: "nb01-057", serieId: "nb01", name: "Symbios ", number: "057/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/57.webp", },
{ id: "nb01-058", serieId: "nb01", name: "Charpenti ", number: "058/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/58.webp", },
{ id: "nb01-059", serieId: "nb01", name: "Charpenti ", number: "059/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/59.webp", },
{ id: "nb01-060", serieId: "nb01", name: "Ouvrifier ", number: "060/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/60.webp", },
{ id: "nb01-061", serieId: "nb01", name: "Judokrak ", number: "061/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/61.webp", },
{ id: "nb01-062", serieId: "nb01", name: "Karaclée ", number: "062/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/62.webp", },
{ id: "nb01-063", serieId: "nb01", name: "Mascaïman ", number: "063/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/63.webp", },
{ id: "nb01-064", serieId: "nb01", name: "Escroco ", number: "064/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/64.webp", },
{ id: "nb01-065", serieId: "nb01", name: "Crocorible ", number: "065/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/65.webp", },
{ id: "nb01-066", serieId: "nb01", name: "Chacripan ", number: "066/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/66.webp", },
{ id: "nb01-067", serieId: "nb01", name: "Léopardus ", number: "067/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/67.webp", },
{ id: "nb01-068", serieId: "nb01", name: "Baggiguane ", number: "068/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/68.webp", },
{ id: "nb01-069", serieId: "nb01", name: "Baggaïd ", number: "069/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/69.webp", },
{ id: "nb01-070", serieId: "nb01", name: "Zorua ", number: "070/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/70.webp", },
{ id: "nb01-071", serieId: "nb01", name: "Zoroark ", number: "071/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/71.webp", },
{ id: "nb01-072", serieId: "nb01", name: "Vostourno ", number: "072/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/72.webp", },
{ id: "nb01-073", serieId: "nb01", name: "Vaututrice ", number: "073/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/73.webp", },
{ id: "nb01-074", serieId: "nb01", name: "Tic ", number: "074/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/74.webp", },
{ id: "nb01-075", serieId: "nb01", name: "Clic ", number: "075/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/75.webp", },
{ id: "nb01-076", serieId: "nb01", name: "Cliticlic ", number: "076/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/76.webp", },
{ id: "nb01-077", serieId: "nb01", name: "Ratentif ", number: "077/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/77.webp", },
{ id: "nb01-078", serieId: "nb01", name: "Ratentif ", number: "078/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/78.webp", },
{ id: "nb01-079", serieId: "nb01", name: "Miradar ", number: "079/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/79.webp", },
{ id: "nb01-080", serieId: "nb01", name: "Ponchiot ", number: "080/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/80.webp", },
{ id: "nb01-081", serieId: "nb01", name: "Ponchiot ", number: "081/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/81.webp", },
{ id: "nb01-082", serieId: "nb01", name: "Ponchien ", number: "082/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/82.webp", },
{ id: "nb01-083", serieId: "nb01", name: "Mastouffe ", number: "083/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/83.webp", },
{ id: "nb01-084", serieId: "nb01", name: "Poichigeon ", number: "084/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/84.webp", },
{ id: "nb01-085", serieId: "nb01", name: "Colombeau ", number: "085/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/85.webp", },
{ id: "nb01-086", serieId: "nb01", name: "Déflaisan ", number: "086/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/86.webp", },
{ id: "nb01-087", serieId: "nb01", name: "Nanméouïe ", number: "087/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/87.webp", },
{ id: "nb01-088", serieId: "nb01", name: "Chinchidou ", number: "088/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/88.webp", },
{ id: "nb01-089", serieId: "nb01", name: "Pashmilla ", number: "089/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/89.webp", },
{ id: "nb01-090", serieId: "nb01", name: "Frison ", number: "090/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/90.webp", },
{ id: "nb01-091", serieId: "nb01", name: "Frison ", number: "091/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/91.webp", },
{ id: "nb01-092", serieId: "nb01", name: "Récupération d'Énergie ", number: "092/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/92.webp", },
{ id: "nb01-093", serieId: "nb01", name: "Recherche d'Énergie ", number: "093/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/93.webp", },
{ id: "nb01-094", serieId: "nb01", name: "Échange d'Énergie ", number: "094/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/94.webp", },
{ id: "nb01-095", serieId: "nb01", name: "Total Soin ", number: "095/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/95.webp", },
{ id: "nb01-096", serieId: "nb01", name: "PlusPower ", number: "096/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/96.webp", },
{ id: "nb01-097", serieId: "nb01", name: "Poké Ball ", number: "097/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/97.webp", },
{ id: "nb01-098", serieId: "nb01", name: "Pokédex ", number: "098/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/98.webp", },
{ id: "nb01-099", serieId: "nb01", name: "Communication Pokémon ", number: "099/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/99.webp", },
{ id: "nb01-100", serieId: "nb01", name: "Potion ", number: "100/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/100.webp", },
{ id: "nb01-101", serieId: "nb01", name: "Professeur Keteleeria ", number: "101/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/101.webp", },
{ id: "nb01-102", serieId: "nb01", name: "Rappel ", number: "102/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/102.webp", },
{ id: "nb01-103", serieId: "nb01", name: "Super Rappel ", number: "103/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/103.webp", },
{ id: "nb01-104", serieId: "nb01", name: "Échange ", number: "104/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/104.webp", },
{ id: "nb01-113", serieId: "nb01", name: "Reshiram ", number: "113/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/113.webp", },
{ id: "nb01-114", serieId: "nb01", name: "Zekrom ", number: "114/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/114.webp", },
{ id: "nb01-115", serieId: "nb01", name: "Pikachu ", number: "115/115", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/115.webp", },




  
] as unknown as Card[]);
