import type { Card } from "../../catalog";

// Noir et Blanc
export const NOIR_ET_BLANC_CARDS = ([
{ id: "prbw-001", serieId: "prbw", name: "Vipélierre", number: "BW01", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/1.webp", },
{ id: "prbw-002", serieId: "prbw", name: "Gruikui", number: "BW02", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/2.webp", },
{ id: "prbw-003", serieId: "prbw", name: "Moustillon", number: "BW03", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/3.webp", },
{ id: "prbw-004", serieId: "prbw", name: "Reshiram", number: "BW004", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/4.webp", },
{ id: "prbw-005", serieId: "prbw", name: "Zekrom", number: "BW005", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/5.webp", },
{ id: "prbw-006", serieId: "prbw", name: "Vipélierre", number: "BW06", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/6.webp", },
{ id: "prbw-007", serieId: "prbw", name: "Gruikui", number: "BW07", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/7.webp", },
{ id: "prbw-008", serieId: "prbw", name: "Moustillon", number: "BW08", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/8.webp", },
{ id: "prbw-009", serieId: "prbw", name: "Zoroark", number: "BW09", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/9.webp", },
{ id: "prbw-010", serieId: "prbw", name: "Coupenotte", number: "BW10", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/10.webp", },
{ id: "prbw-011", serieId: "prbw", name: "Feuillajou", number: "BW11", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/11.webp", },
{ id: "prbw-012", serieId: "prbw", name: "Zorua", number: "BW12", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/12.webp", },
{ id: "prbw-013", serieId: "prbw", name: "Chinchidou", number: "BW13", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/13.webp", },
{ id: "prbw-014", serieId: "prbw", name: "Feuillajou", number: "BW14", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/14.webp", },
{ id: "prbw-015", serieId: "prbw", name: "Poichigeon", number: "BW15", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/15.webp", },
{ id: "prbw-016", serieId: "prbw", name: "Coupenotte", number: "BW16", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/16.webp", },
{ id: "prbw-017", serieId: "prbw", name: "Couaneton", number: "BW17", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/17.webp", },
{ id: "prbw-018", serieId: "prbw", name: "Darumarond", number: "BW18", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/18.webp", },
{ id: "prbw-019", serieId: "prbw", name: "Zoroark", number: "BW19", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/19.webp", },
{ id: "prbw-020", serieId: "prbw", name: "Majaspic", number: "BW20", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/20.webp", },
{ id: "prbw-021", serieId: "prbw", name: "Roitiflam", number: "BW21", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/21.webp", },
{ id: "prbw-022", serieId: "prbw", name: "Clamiral", number: "BW22", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/22.webp", },
{ id: "prbw-023", serieId: "prbw", name: "Reshiram", number: "BW23", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/23.webp", },
{ id: "prbw-024", serieId: "prbw", name: "Zekrom", number: "BW24", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/24.webp", },
{ id: "prbw-025", serieId: "prbw", name: "Baggiguane", number: "BW25", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/25.webp", },
{ id: "prbw-026", serieId: "prbw", name: "Coupenotte", number: "BW26", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/26.webp", },
{ id: "prbw-027", serieId: "prbw", name: "Funécire", number: "BW27", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/27.webp", },
{ id: "prbw-028", serieId: "prbw", name: "Plage Tropicale", number: "BW28", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/28.webp", },
{ id: "prbw-029", serieId: "prbw", name: "Coupe Victoire", number: "BW29", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/29.webp", },
{ id: "prbw-030", serieId: "prbw", name: "Coupe Victoire", number: "BW30", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/30.webp", },
{ id: "prbw-031", serieId: "prbw", name: "Coupe Victoire", number: "BW31", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/31.webp", },
{ id: "prbw-032", serieId: "prbw", name: "Victini", number: "BW32", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/32.webp", },
{ id: "prbw-033", serieId: "prbw", name: "Riolu", number: "BW33", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/33.webp", },
{ id: "prbw-034", serieId: "prbw", name: "Luxio", number: "BW34", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/34.webp", },
{ id: "prbw-035", serieId: "prbw", name: "Miaouss", number: "BW35", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/35.webp", },
{ id: "prbw-036", serieId: "prbw", name: "Reshiram-EX", number: "BW36", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/36.webp", },
{ id: "prbw-037", serieId: "prbw", name: "Kyurem-EX", number: "BW37", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/37.webp", },
{ id: "prbw-038", serieId: "prbw", name: "Zekrom-EX", number: "BW38", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/38.webp", },
{ id: "prbw-039", serieId: "prbw", name: "Ville Combat", number: "BW39", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/39.webp", },
{ id: "prbw-040", serieId: "prbw", name: "Pyrax", number: "BW40", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/40.webp", },
{ id: "prbw-041", serieId: "prbw", name: "Fulguris", number: "BW41", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/41.webp", },
{ id: "prbw-042", serieId: "prbw", name: "Boréas", number: "BW42", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/42.webp", },
{ id: "prbw-043", serieId: "prbw", name: "Démétéros", number: "BW43", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/43.webp", },
{ id: "prbw-044", serieId: "prbw", name: "Kyurem", number: "BW44", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/44.webp", },
{ id: "prbw-045", serieId: "prbw", name: "Mewtwo-EX", number: "BW45", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/45.webp", },
{ id: "prbw-046", serieId: "prbw", name: "Darkrai-EX", number: "BW46", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/46.webp", },
{ id: "prbw-047", serieId: "prbw", name: "Rayquaza-EX", number: "BW47", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/47.webp", },
{ id: "prbw-048", serieId: "prbw", name: "Altaria", number: "BW48", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/48.webp", },
{ id: "prbw-049", serieId: "prbw", name: "Fragilady", number: "BW49", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/49.webp", },
{ id: "prbw-050", serieId: "prbw", name: "Plage Tropicale", number: "BW50", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/50.webp", },
{ id: "prbw-051", serieId: "prbw", name: "Nostenfer", number: "BW51", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/51.webp", },
{ id: "prbw-052", serieId: "prbw", name: "Ponchiot", number: "BW52", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/52.webp", },
{ id: "prbw-053", serieId: "prbw", name: "Libégon", number: "BW53", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/53.webp", },
{ id: "prbw-054", serieId: "prbw", name: "Pikachu", number: "BW54", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/54.webp", },
{ id: "prbw-055", serieId: "prbw", name: "Lewsor", number: "BW55", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/55.webp", },
{ id: "prbw-056", serieId: "prbw", name: "Pingoléon", number: "BW56", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/56.webp", },
{ id: "prbw-057", serieId: "prbw", name: "Tranchodon", number: "BW57", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/57.webp", },
{ id: "prbw-058", serieId: "prbw", name: "Kyurem Noir", number: "BW58", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/58.webp", },
{ id: "prbw-059", serieId: "prbw", name: "Kyurem Blanc", number: "BW59", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/59.webp", },
{ id: "prbw-060", serieId: "prbw", name: "Keldeo", number: "BW60", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/60.webp", },
{ id: "prbw-061", serieId: "prbw", name: "Keldeo-EX", number: "BW61", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/61.webp", },
{ id: "prbw-062", serieId: "prbw", name: "Kyurem Noir-EX", number: "BW62", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/62.webp", },
{ id: "prbw-063", serieId: "prbw", name: "Kyurem Blanc-EX", number: "BW63", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/63.webp", },
{ id: "prbw-064", serieId: "prbw", name: "Grodrive", number: "BW64", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/64.webp", },
{ id: "prbw-065", serieId: "prbw", name: "Rondoudou", number: "BW65", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/65.webp", },
{ id: "prbw-066", serieId: "prbw", name: "Feunard", number: "BW66", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/66.webp", },
{ id: "prbw-067", serieId: "prbw", name: "Pharamp", number: "BW67", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/67.webp", },
{ id: "prbw-068", serieId: "prbw", name: "Meloetta", number: "BW68", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/68.webp", },
{ id: "prbw-069", serieId: "prbw", name: "Meloetta", number: "BW69", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/69.webp", },
{ id: "prbw-070", serieId: "prbw", name: "Viridium", number: "BW70", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/70.webp", },
{ id: "prbw-071", serieId: "prbw", name: "Terrakium", number: "BW71", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/71.webp", },
{ id: "prbw-072", serieId: "prbw", name: "Cobaltium", number: "BW72", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/72.webp", },
{ id: "prbw-073", serieId: "prbw", name: "Darkrai", number: "BW73", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/73.webp", },
{ id: "prbw-074", serieId: "prbw", name: "Giratina", number: "BW74", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/74.webp", },
{ id: "prbw-075", serieId: "prbw", name: "Métalosse", number: "BW75", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/75.webp", },
{ id: "prbw-076", serieId: "prbw", name: "Électrode", number: "BW76", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/76.webp", },
{ id: "prbw-077", serieId: "prbw", name: "Pikachu", number: "BW77", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/77.webp", },
{ id: "prbw-078", serieId: "prbw", name: "Raichu", number: "BW78", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/78.webp", },
{ id: "prbw-079", serieId: "prbw", name: "Démétéros", number: "BW79", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/79.webp", },
{ id: "prbw-080", serieId: "prbw", name: "Drakkarmin", number: "BW80", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/80.webp", },
{ id: "prbw-081", serieId: "prbw", name: "Fulguris-EX", number: "BW81", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/81.webp", },
{ id: "prbw-082", serieId: "prbw", name: "Deoxys-EX", number: "BW82", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/82.webp", },
{ id: "prbw-083", serieId: "prbw", name: "Lugia-EX", number: "BW83", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/83.webp", },
{ id: "prbw-084", serieId: "prbw", name: "Porygon-Z", number: "BW84", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/84.webp", },
{ id: "prbw-085", serieId: "prbw", name: "Lucario", number: "BW85", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/85.webp", },
{ id: "prbw-086", serieId: "prbw", name: "Genesect", number: "BW86", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/86.webp", },
{ id: "prbw-087", serieId: "prbw", name: "Phyllali", number: "BW87", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/87.webp", },
{ id: "prbw-088", serieId: "prbw", name: "Pyroli", number: "BW88", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/88.webp", },
{ id: "prbw-089", serieId: "prbw", name: "Aquali", number: "BW89", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/89.webp", },
{ id: "prbw-090", serieId: "prbw", name: "Givrali", number: "BW90", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/90.webp", },
{ id: "prbw-091", serieId: "prbw", name: "Voltali", number: "BW91", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/91.webp", },
{ id: "prbw-092", serieId: "prbw", name: "Mentali", number: "BW92", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/92.webp", },
{ id: "prbw-093", serieId: "prbw", name: "Noctali", number: "BW93", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/93.webp", },
{ id: "prbw-094", serieId: "prbw", name: "Évoli", number: "BW94", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/94.webp", },
{ id: "prbw-095", serieId: "prbw", name: "Festival des Champions", number: "BW95", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/95.webp", },
{ id: "prbw-096", serieId: "prbw", name: "Boréas-EX", number: "BW96", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/96.webp", },
{ id: "prbw-097", serieId: "prbw", name: "Évoli", number: "BW97", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/97.webp", },
{ id: "prbw-098", serieId: "prbw", name: "Mew", number: "BW98", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/98.webp", },
{ id: "prbw-099", serieId: "prbw", name: "Genesect", number: "BW99", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/99.webp", },
{ id: "prbw-100", serieId: "prbw", name: "N", number: "BW100", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/100.webp", },
{ id: "prbw-101", serieId: "prbw", name: "Genesect", number: "BW101", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/101.webp", },


// NB01
{ id: "nb01-001", serieId: "nb01", name: "Vipélierre", number: "001/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/1.webp", },
{ id: "nb01-002", serieId: "nb01", name: "Vipélierre ", number: "002/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/2.webp", },
{ id: "nb01-003", serieId: "nb01", name: "Lianaja ", number: "003/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/3.webp", },
{ id: "nb01-004", serieId: "nb01", name: "Lianaja ", number: "004/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/4.webp", },
{ id: "nb01-005", serieId: "nb01", name: "Majaspic ", number: "005/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/5.webp", },
{ id: "nb01-006", serieId: "nb01", name: "Majaspic ", number: "006/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/6.webp", },
{ id: "nb01-007", serieId: "nb01", name: "Feuillajou ", number: "007/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/7.webp", },
{ id: "nb01-008", serieId: "nb01", name: "Feuiloutan ", number: "008/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/8.webp", },
{ id: "nb01-009", serieId: "nb01", name: "Chlorobule ", number: "009/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/9.webp", },
{ id: "nb01-010", serieId: "nb01", name: "Fragilady ", number: "010/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/10.webp", },
{ id: "nb01-011", serieId: "nb01", name: "Maracachi ", number: "011/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/11.webp", },
{ id: "nb01-012", serieId: "nb01", name: "Maracachi ", number: "012/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/12.webp", },
{ id: "nb01-013", serieId: "nb01", name: "Vivaldaim ", number: "013/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/13.webp", },
{ id: "nb01-014", serieId: "nb01", name: "Haydaim ", number: "014/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/14.webp", },
{ id: "nb01-015", serieId: "nb01", name: "Gruikui ", number: "015/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/15.webp", },
{ id: "nb01-016", serieId: "nb01", name: "Gruikui ", number: "016/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/16.webp", },
{ id: "nb01-017", serieId: "nb01", name: "Grotichon ", number: "017/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/17.webp", },
{ id: "nb01-018", serieId: "nb01", name: "Grotichon ", number: "018/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/18.webp", },
{ id: "nb01-019", serieId: "nb01", name: "Roitiflam ", number: "019/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/19.webp", },
{ id: "nb01-020", serieId: "nb01", name: "Roitiflam ", number: "020/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/20.webp", },
{ id: "nb01-021", serieId: "nb01", name: "Flamajou ", number: "021/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/21.webp", },
{ id: "nb01-022", serieId: "nb01", name: "Flamoutan ", number: "022/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/22.webp", },
{ id: "nb01-023", serieId: "nb01", name: "Darumarond ", number: "023/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/23.webp", },
{ id: "nb01-024", serieId: "nb01", name: "Darumarond ", number: "024/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/24.webp", },
{ id: "nb01-025", serieId: "nb01", name: "Darumacho ", number: "025/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/25.webp", },
{ id: "nb01-026", serieId: "nb01", name: "Reshiram ", number: "026/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/26.webp", },
{ id: "nb01-027", serieId: "nb01", name: "Moustillon ", number: "027/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/27.webp", },
{ id: "nb01-028", serieId: "nb01", name: "Moustillon ", number: "028/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/28.webp", },
{ id: "nb01-029", serieId: "nb01", name: "Mateloutre ", number: "029/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/29.webp", },
{ id: "nb01-030", serieId: "nb01", name: "Mateloutre ", number: "030/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/30.webp", },
{ id: "nb01-031", serieId: "nb01", name: "Clamiral ", number: "031/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/31.webp", },
{ id: "nb01-032", serieId: "nb01", name: "Clamiral ", number: "032/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/32.webp", },
{ id: "nb01-033", serieId: "nb01", name: "Flotajou ", number: "033/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/33.webp", },
{ id: "nb01-034", serieId: "nb01", name: "Flotoutan ", number: "034/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/34.webp", },
{ id: "nb01-035", serieId: "nb01", name: "Bargantua ", number: "035/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/35.webp", },
{ id: "nb01-036", serieId: "nb01", name: "Couaneton ", number: "036/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/36.webp", },
{ id: "nb01-037", serieId: "nb01", name: "Lakmécygne ", number: "037/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/37.webp", },
{ id: "nb01-038", serieId: "nb01", name: "Mamanbo ", number: "038/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/38.webp", },
{ id: "nb01-039", serieId: "nb01", name: "Mamanbo ", number: "039/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/39.webp", },
{ id: "nb01-040", serieId: "nb01", name: "Zébibron ", number: "040/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/40.webp", },
{ id: "nb01-041", serieId: "nb01", name: "Zébibron ", number: "041/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/41.webp", },
{ id: "nb01-042", serieId: "nb01", name: "Zéblitz ", number: "042/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/42.webp", },
{ id: "nb01-043", serieId: "nb01", name: "Zéblitz ", number: "043/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/43.webp", },
{ id: "nb01-044", serieId: "nb01", name: "Statitik ", number: "044/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/44.webp", },
{ id: "nb01-045", serieId: "nb01", name: "Statitik ", number: "045/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/45.webp", },
{ id: "nb01-046", serieId: "nb01", name: "Mygavolt ", number: "046/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/46.webp", },
{ id: "nb01-047", serieId: "nb01", name: "Zekrom ", number: "047/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/47.webp", },
{ id: "nb01-048", serieId: "nb01", name: "Munna ", number: "048/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/48.webp", },
{ id: "nb01-049", serieId: "nb01", name: "Mushana ", number: "049/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/49.webp", },
{ id: "nb01-050", serieId: "nb01", name: "Chovsourir ", number: "050/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/50.webp", },
{ id: "nb01-051", serieId: "nb01", name: "Rhinolove ", number: "051/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/51.webp", },
{ id: "nb01-052", serieId: "nb01", name: "Venipatte ", number: "052/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/52.webp", },
{ id: "nb01-053", serieId: "nb01", name: "Scobolide ", number: "053/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/53.webp", },
{ id: "nb01-054", serieId: "nb01", name: "Brutapode ", number: "054/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/54.webp", },
{ id: "nb01-055", serieId: "nb01", name: "Nucléos ", number: "055/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/55.webp", },
{ id: "nb01-056", serieId: "nb01", name: "Méios ", number: "056/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/56.webp", },
{ id: "nb01-057", serieId: "nb01", name: "Symbios ", number: "057/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/57.webp", },
{ id: "nb01-058", serieId: "nb01", name: "Charpenti ", number: "058/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/58.webp", },
{ id: "nb01-059", serieId: "nb01", name: "Charpenti ", number: "059/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/59.webp", },
{ id: "nb01-060", serieId: "nb01", name: "Ouvrifier ", number: "060/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/60.webp", },
{ id: "nb01-061", serieId: "nb01", name: "Judokrak ", number: "061/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/61.webp", },
{ id: "nb01-062", serieId: "nb01", name: "Karaclée ", number: "062/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/62.webp", },
{ id: "nb01-063", serieId: "nb01", name: "Mascaïman ", number: "063/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/63.webp", },
{ id: "nb01-064", serieId: "nb01", name: "Escroco ", number: "064/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/64.webp", },
{ id: "nb01-065", serieId: "nb01", name: "Crocorible ", number: "065/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/65.webp", },
{ id: "nb01-066", serieId: "nb01", name: "Chacripan ", number: "066/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/66.webp", },
{ id: "nb01-067", serieId: "nb01", name: "Léopardus ", number: "067/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/67.webp", },
{ id: "nb01-068", serieId: "nb01", name: "Baggiguane ", number: "068/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/68.webp", },
{ id: "nb01-069", serieId: "nb01", name: "Baggaïd ", number: "069/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/69.webp", },
{ id: "nb01-070", serieId: "nb01", name: "Zorua ", number: "070/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/70.webp", },
{ id: "nb01-071", serieId: "nb01", name: "Zoroark ", number: "071/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/71.webp", },
{ id: "nb01-072", serieId: "nb01", name: "Vostourno ", number: "072/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/72.webp", },
{ id: "nb01-073", serieId: "nb01", name: "Vaututrice ", number: "073/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/73.webp", },
{ id: "nb01-074", serieId: "nb01", name: "Tic ", number: "074/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/74.webp", },
{ id: "nb01-075", serieId: "nb01", name: "Clic ", number: "075/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/75.webp", },
{ id: "nb01-076", serieId: "nb01", name: "Cliticlic ", number: "076/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/76.webp", },
{ id: "nb01-077", serieId: "nb01", name: "Ratentif ", number: "077/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/77.webp", },
{ id: "nb01-078", serieId: "nb01", name: "Ratentif ", number: "078/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/78.webp", },
{ id: "nb01-079", serieId: "nb01", name: "Miradar ", number: "079/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/79.webp", },
{ id: "nb01-080", serieId: "nb01", name: "Ponchiot ", number: "080/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/80.webp", },
{ id: "nb01-081", serieId: "nb01", name: "Ponchiot ", number: "081/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/81.webp", },
{ id: "nb01-082", serieId: "nb01", name: "Ponchien ", number: "082/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/82.webp", },
{ id: "nb01-083", serieId: "nb01", name: "Mastouffe ", number: "083/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/83.webp", },
{ id: "nb01-084", serieId: "nb01", name: "Poichigeon ", number: "084/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/84.webp", },
{ id: "nb01-085", serieId: "nb01", name: "Colombeau ", number: "085/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/85.webp", },
{ id: "nb01-086", serieId: "nb01", name: "Déflaisan ", number: "086/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/86.webp", },
{ id: "nb01-087", serieId: "nb01", name: "Nanméouïe ", number: "087/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/87.webp", },
{ id: "nb01-088", serieId: "nb01", name: "Chinchidou ", number: "088/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/88.webp", },
{ id: "nb01-089", serieId: "nb01", name: "Pashmilla ", number: "089/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/89.webp", },
{ id: "nb01-090", serieId: "nb01", name: "Frison ", number: "090/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/90.webp", },
{ id: "nb01-091", serieId: "nb01", name: "Frison ", number: "091/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/91.webp", },
{ id: "nb01-092", serieId: "nb01", name: "Récupération d'Énergie ", number: "092/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/92.webp", },
{ id: "nb01-093", serieId: "nb01", name: "Recherche d'Énergie ", number: "093/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/93.webp", },
{ id: "nb01-094", serieId: "nb01", name: "Échange d'Énergie ", number: "094/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/94.webp", },
{ id: "nb01-095", serieId: "nb01", name: "Total Soin ", number: "095/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/95.webp", },
{ id: "nb01-096", serieId: "nb01", name: "PlusPower ", number: "096/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/96.webp", },
{ id: "nb01-097", serieId: "nb01", name: "Poké Ball ", number: "097/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/97.webp", },
{ id: "nb01-098", serieId: "nb01", name: "Pokédex ", number: "098/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/98.webp", },
{ id: "nb01-099", serieId: "nb01", name: "Communication Pokémon ", number: "099/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/99.webp", },
{ id: "nb01-100", serieId: "nb01", name: "Potion ", number: "100/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/100.webp", },
{ id: "nb01-101", serieId: "nb01", name: "Professeur Keteleeria ", number: "101/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/101.webp", },
{ id: "nb01-102", serieId: "nb01", name: "Rappel ", number: "102/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/102.webp", },
{ id: "nb01-103", serieId: "nb01", name: "Super Rappel ", number: "103/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/103.webp", },
{ id: "nb01-104", serieId: "nb01", name: "Échange ", number: "104/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/104.webp", },
{ id: "nb01-113", serieId: "nb01", name: "Reshiram ", number: "113/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/113.webp", },
{ id: "nb01-114", serieId: "nb01", name: "Zekrom ", number: "114/115", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/114.webp", },
{ id: "nb01-115", serieId: "nb01", name: "Pikachu ", number: "115/115", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 0.5, stock: 0, image: "/cartes/nb01/115.webp", },

//NB02
{ id: "nb02-001", serieId: "nb02", name: "Feuillajou", number: "001/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/1.webp", },
{ id: "nb02-002", serieId: "nb02", name: "Feuiloutan", number: "002/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/2.webp", },
{ id: "nb02-003", serieId: "nb02", name: "Larveyette", number: "003/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/3.webp", },
{ id: "nb02-004", serieId: "nb02", name: "Larveyette", number: "004/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/4.webp", },
{ id: "nb02-005", serieId: "nb02", name: "Couverdure", number: "005/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/5.webp", },
{ id: "nb02-006", serieId: "nb02", name: "Couverdure", number: "006/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/6.webp", },
{ id: "nb02-007", serieId: "nb02", name: "Manternel", number: "007/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/7.webp", },
{ id: "nb02-008", serieId: "nb02", name: "Manternel", number: "008/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/8.webp", },
{ id: "nb02-009", serieId: "nb02", name: "Doudouvet", number: "009/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/9.webp", },
{ id: "nb02-010", serieId: "nb02", name: "Doudouvet", number: "010/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/10.webp", },
{ id: "nb02-011", serieId: "nb02", name: "Farfaduvet", number: "011/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/11.webp", },
{ id: "nb02-012", serieId: "nb02", name: "Farfaduvet", number: "012/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/12.webp", },
{ id: "nb02-013", serieId: "nb02", name: "Chlorobule", number: "013/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/13.webp", },
{ id: "nb02-014", serieId: "nb02", name: "Fragilady", number: "014/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/14.webp", },
{ id: "nb02-015", serieId: "nb02", name: "Vivaldaim", number: "015/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/15.webp", },
{ id: "nb02-016", serieId: "nb02", name: "Haydaim", number: "016/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/16.webp", },
{ id: "nb02-017", serieId: "nb02", name: "Viridium", number: "017/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/17.webp", },
{ id: "nb02-018", serieId: "nb02", name: "Flamajou", number: "018/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/18.webp", },
{ id: "nb02-019", serieId: "nb02", name: "Flamoutan", number: "019/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/19.webp", },
{ id: "nb02-020", serieId: "nb02", name: "Darumarond", number: "020/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/20.webp", },
{ id: "nb02-021", serieId: "nb02", name: "Darumacho", number: "021/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/21.webp", },
{ id: "nb02-022", serieId: "nb02", name: "Flotajou", number: "022/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/22.webp", },
{ id: "nb02-023", serieId: "nb02", name: "Flotoutan", number: "023/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/23.webp", },
{ id: "nb02-024", serieId: "nb02", name: "Bargantua", number: "024/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/24.webp", },
{ id: "nb02-025", serieId: "nb02", name: "Bargantua", number: "025/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/25.webp", },
{ id: "nb02-026", serieId: "nb02", name: "Couaneton", number: "026/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/26.webp", },
{ id: "nb02-027", serieId: "nb02", name: "Lakmécygne", number: "027/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/27.webp", },
{ id: "nb02-028", serieId: "nb02", name: "Polarhume", number: "028/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/28.webp", },
{ id: "nb02-029", serieId: "nb02", name: "Polarhume", number: "029/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/29.webp", },
{ id: "nb02-030", serieId: "nb02", name: "Polagriffe", number: "030/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/30.webp", },
{ id: "nb02-031", serieId: "nb02", name: "Polagriffe", number: "031/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/31.webp", },
{ id: "nb02-032", serieId: "nb02", name: "Emolga", number: "032/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/32.webp", },
{ id: "nb02-033", serieId: "nb02", name: "Statitik", number: "033/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/33.webp", },
{ id: "nb02-034", serieId: "nb02", name: "Mygavolt", number: "034/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/34.webp", },
{ id: "nb02-035", serieId: "nb02", name: "Fulguris", number: "035/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/35.webp", },
{ id: "nb02-036", serieId: "nb02", name: "Chovsourir", number: "036/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/36.webp", },
{ id: "nb02-037", serieId: "nb02", name: "Rhinolove", number: "037/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/37.webp", },
{ id: "nb02-038", serieId: "nb02", name: "Venipatte", number: "038/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/38.webp", },
{ id: "nb02-039", serieId: "nb02", name: "Scobolide", number: "039/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/39.webp", },
{ id: "nb02-040", serieId: "nb02", name: "Brutapode", number: "040/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/40.webp", },
{ id: "nb02-041", serieId: "nb02", name: "Cryptéro", number: "041/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/41.webp", },
{ id: "nb02-042", serieId: "nb02", name: "Cryptéro", number: "042/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/42.webp", },
{ id: "nb02-043", serieId: "nb02", name: "Scrutella", number: "043/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/43.webp", },
{ id: "nb02-044", serieId: "nb02", name: "Scrutella", number: "044/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/44.webp", },
{ id: "nb02-045", serieId: "nb02", name: "Mesmérella", number: "045/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/45.webp", },
{ id: "nb02-046", serieId: "nb02", name: "Mesmérella", number: "046/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/46.webp", },
{ id: "nb02-047", serieId: "nb02", name: "Sidérella", number: "047/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/47.webp", },
{ id: "nb02-048", serieId: "nb02", name: "Sidérella", number: "048/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/48.webp", },
{ id: "nb02-049", serieId: "nb02", name: "Nodulithe", number: "049/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/49.webp", },
{ id: "nb02-050", serieId: "nb02", name: "Nodulithe", number: "050/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/50.webp", },
{ id: "nb02-051", serieId: "nb02", name: "Géolithe", number: "051/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/51.webp", },
{ id: "nb02-052", serieId: "nb02", name: "Géolithe", number: "052/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/52.webp", },
{ id: "nb02-053", serieId: "nb02", name: "Gigalithe", number: "053/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/53.webp", },
{ id: "nb02-054", serieId: "nb02", name: "Rototaupe", number: "054/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/54.webp", },
{ id: "nb02-055", serieId: "nb02", name: "Rototaupe", number: "055/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/55.webp", },
{ id: "nb02-056", serieId: "nb02", name: "Minotaupe", number: "056/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/56.webp", },
{ id: "nb02-057", serieId: "nb02", name: "Minotaupe", number: "057/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/57.webp", },
{ id: "nb02-058", serieId: "nb02", name: "Judokrak", number: "058/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/58.webp", },
{ id: "nb02-059", serieId: "nb02", name: "Karaclée", number: "059/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/59.webp", },
{ id: "nb02-060", serieId: "nb02", name: "Mascaïman", number: "060/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/60.webp", },
{ id: "nb02-061", serieId: "nb02", name: "Escroco", number: "061/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/61.webp", },
{ id: "nb02-062", serieId: "nb02", name: "Crocorible", number: "062/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/62.webp", },
{ id: "nb02-063", serieId: "nb02", name: "Terrakium", number: "063/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/63.webp", },
{ id: "nb02-064", serieId: "nb02", name: "Chacripan", number: "064/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/64.webp", },
{ id: "nb02-065", serieId: "nb02", name: "Léopardus", number: "065/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/65.webp", },
{ id: "nb02-066", serieId: "nb02", name: "Zorua", number: "066/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/66.webp", },
{ id: "nb02-067", serieId: "nb02", name: "Zoroark", number: "067/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/67.webp", },
{ id: "nb02-068", serieId: "nb02", name: "Vostourno", number: "068/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/68.webp", },
{ id: "nb02-069", serieId: "nb02", name: "Vaututrice", number: "069/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/69.webp", },
{ id: "nb02-070", serieId: "nb02", name: "Grindur", number: "070/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/70.webp", },
{ id: "nb02-071", serieId: "nb02", name: "Grindur", number: "071/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/71.webp", },
{ id: "nb02-072", serieId: "nb02", name: "Noacier", number: "072/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/72.webp", },
{ id: "nb02-073", serieId: "nb02", name: "Noacier", number: "073/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/73.webp", },
{ id: "nb02-074", serieId: "nb02", name: "Tic", number: "074/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/74.webp", },
{ id: "nb02-075", serieId: "nb02", name: "Clic", number: "075/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/75.webp", },
{ id: "nb02-076", serieId: "nb02", name: "Cliticlic", number: "076/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/76.webp", },
{ id: "nb02-077", serieId: "nb02", name: "Cobaltium", number: "077/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/77.webp", },
{ id: "nb02-078", serieId: "nb02", name: "Ratentif", number: "078/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/78.webp", },
{ id: "nb02-079", serieId: "nb02", name: "Miradar", number: "079/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/79.webp", },
{ id: "nb02-080", serieId: "nb02", name: "Poichigeon", number: "080/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/80.webp", },
{ id: "nb02-081", serieId: "nb02", name: "Colombeau", number: "081/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/81.webp", },
{ id: "nb02-082", serieId: "nb02", name: "Déflaisan", number: "082/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/82.webp", },
{ id: "nb02-083", serieId: "nb02", name: "Nanméouïe", number: "083/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/83.webp", },
{ id: "nb02-084", serieId: "nb02", name: "Chinchidou", number: "084/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/84.webp", },
{ id: "nb02-085", serieId: "nb02", name: "Pashmilla", number: "085/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/85.webp", },
{ id: "nb02-086", serieId: "nb02", name: "Furaiglon", number: "086/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/86.webp", },
{ id: "nb02-087", serieId: "nb02", name: "Furaiglon", number: "087/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/87.webp", },
{ id: "nb02-088", serieId: "nb02", name: "Gueriaigle", number: "088/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/88.webp", },
{ id: "nb02-089", serieId: "nb02", name: "Boréas", number: "089/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/89.webp", },
{ id: "nb02-090", serieId: "nb02", name: "Bianca", number: "090/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/90.webp", },
{ id: "nb02-091", serieId: "nb02", name: "Tcheren", number: "091/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/91.webp", },
{ id: "nb02-092", serieId: "nb02", name: "Maillet Écrasant", number: "092/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/92.webp", },
{ id: "nb02-093", serieId: "nb02", name: "Super Ball", number: "093/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/93.webp", },
{ id: "nb02-094", serieId: "nb02", name: "Potion Max", number: "094/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/94.webp", },
{ id: "nb02-095", serieId: "nb02", name: "Attrape-Pokémon", number: "095/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/95.webp", },
{ id: "nb02-096", serieId: "nb02", name: "Recyclage", number: "096/98", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/96.webp", },
{ id: "nb02-097", serieId: "nb02", name: "Fulguris", number: "097/98", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/97.webp", },
{ id: "nb02-098", serieId: "nb02", name: "Boréas", number: "098/98", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb02/98.webp", },

//NB03
{ id: "nb03-001", serieId: "nb03", name: "Larveyette", number: "001/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/1.webp", },
{ id: "nb03-002", serieId: "nb03", name: "Couverdure", number: "002/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/2.webp", },
{ id: "nb03-003", serieId: "nb03", name: "Manternel", number: "003/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/3.webp", },
{ id: "nb03-004", serieId: "nb03", name: "Chlorobule", number: "004/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/4.webp", },
{ id: "nb03-005", serieId: "nb03", name: "Fragilady", number: "005/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/5.webp", },
{ id: "nb03-006", serieId: "nb03", name: "Crabicoque", number: "006/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/6.webp", },
{ id: "nb03-007", serieId: "nb03", name: "Crabaraque", number: "007/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/7.webp", },
{ id: "nb03-008", serieId: "nb03", name: "Carabing", number: "008/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/8.webp", },
{ id: "nb03-009", serieId: "nb03", name: "Trompignon", number: "009/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/9.webp", },
{ id: "nb03-010", serieId: "nb03", name: "Gaulet", number: "010/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/10.webp", },
{ id: "nb03-011", serieId: "nb03", name: "Escargaume", number: "011/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/11.webp", },
{ id: "nb03-012", serieId: "nb03", name: "Limaspeed", number: "012/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/12.webp", },
{ id: "nb03-013", serieId: "nb03", name: "Viridium", number: "013/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/13.webp", },
{ id: "nb03-014", serieId: "nb03", name: "Victini", number: "014/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/14.webp", },
{ id: "nb03-015", serieId: "nb03", name: "Victini", number: "015/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/15.webp", },
{ id: "nb03-016", serieId: "nb03", name: "Flamajou", number: "016/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/16.webp", },
{ id: "nb03-017", serieId: "nb03", name: "Flamoutan", number: "017/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/17.webp", },
{ id: "nb03-018", serieId: "nb03", name: "Aflamanoir", number: "018/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/18.webp", },
{ id: "nb03-019", serieId: "nb03", name: "Pyronille", number: "019/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/19.webp", },
{ id: "nb03-020", serieId: "nb03", name: "Pyronille", number: "020/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/20.webp", },
{ id: "nb03-021", serieId: "nb03", name: "Pyrax", number: "021/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/21.webp", },
{ id: "nb03-022", serieId: "nb03", name: "Tritonde", number: "022/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/22.webp", },
{ id: "nb03-023", serieId: "nb03", name: "Batracné", number: "023/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/23.webp", },
{ id: "nb03-024", serieId: "nb03", name: "Crapustule", number: "024/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/24.webp", },
{ id: "nb03-025", serieId: "nb03", name: "Carapagos", number: "025/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/25.webp", },
{ id: "nb03-026", serieId: "nb03", name: "Mégapagos", number: "026/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/26.webp", },
{ id: "nb03-027", serieId: "nb03", name: "Sorbébé", number: "027/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/27.webp", },
{ id: "nb03-028", serieId: "nb03", name: "Sorboul", number: "028/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/28.webp", },
{ id: "nb03-029", serieId: "nb03", name: "Sorbouboul", number: "029/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/29.webp", },
{ id: "nb03-030", serieId: "nb03", name: "Viskuse", number: "030/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/30.webp", },
{ id: "nb03-031", serieId: "nb03", name: "Moyade", number: "031/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/31.webp", },
{ id: "nb03-032", serieId: "nb03", name: "Hexagel", number: "032/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/32.webp", },
{ id: "nb03-033", serieId: "nb03", name: "Hexagel", number: "033/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/33.webp", },
{ id: "nb03-034", serieId: "nb03", name: "Kyurem", number: "034/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/34.webp", },
{ id: "nb03-035", serieId: "nb03", name: "Zébibron", number: "035/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/35.webp", },
{ id: "nb03-036", serieId: "nb03", name: "Zéblitz", number: "036/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/36.webp", },
{ id: "nb03-037", serieId: "nb03", name: "Emolga", number: "037/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/37.webp", },
{ id: "nb03-038", serieId: "nb03", name: "Anchwatt", number: "038/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/38.webp", },
{ id: "nb03-039", serieId: "nb03", name: "Anchwatt", number: "039/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/39.webp", },
{ id: "nb03-040", serieId: "nb03", name: "Lampéroie", number: "040/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/40.webp", },
{ id: "nb03-041", serieId: "nb03", name: "Ohmassacre", number: "041/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/41.webp", },
{ id: "nb03-042", serieId: "nb03", name: "Limonde", number: "042/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/42.webp", },
{ id: "nb03-043", serieId: "nb03", name: "Victini", number: "043/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/43.webp", },
{ id: "nb03-044", serieId: "nb03", name: "Tutafeh", number: "044/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/44.webp", },
{ id: "nb03-045", serieId: "nb03", name: "Tutafeh", number: "045/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/45.webp", },
{ id: "nb03-046", serieId: "nb03", name: "Tutankafer", number: "046/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/46.webp", },
{ id: "nb03-047", serieId: "nb03", name: "Tutankafer", number: "047/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/47.webp", },
{ id: "nb03-048", serieId: "nb03", name: "Miamiasme", number: "048/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/48.webp", },
{ id: "nb03-049", serieId: "nb03", name: "Miasmax", number: "049/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/49.webp", },
{ id: "nb03-050", serieId: "nb03", name: "Nucléos", number: "050/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/50.webp", },
{ id: "nb03-051", serieId: "nb03", name: "Méios", number: "051/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/51.webp", },
{ id: "nb03-052", serieId: "nb03", name: "Symbios", number: "052/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/52.webp", },
{ id: "nb03-053", serieId: "nb03", name: "Symbios", number: "053/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/53.webp", },
{ id: "nb03-054", serieId: "nb03", name: "Lewsor", number: "054/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/54.webp", },
{ id: "nb03-055", serieId: "nb03", name: "Lewsor", number: "055/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/55.webp", },
{ id: "nb03-056", serieId: "nb03", name: "Neitram", number: "056/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/56.webp", },
{ id: "nb03-057", serieId: "nb03", name: "Funécire", number: "057/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/57.webp", },
{ id: "nb03-058", serieId: "nb03", name: "Funécire", number: "058/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/58.webp", },
{ id: "nb03-059", serieId: "nb03", name: "Mélancolux", number: "059/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/59.webp", },
{ id: "nb03-060", serieId: "nb03", name: "Lugulabre", number: "060/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/60.webp", },
{ id: "nb03-061", serieId: "nb03", name: "Gigalithe", number: "061/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/61.webp", },
{ id: "nb03-062", serieId: "nb03", name: "Charpenti", number: "062/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/62.webp", },
{ id: "nb03-063", serieId: "nb03", name: "Ouvrifier", number: "063/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/63.webp", },
{ id: "nb03-064", serieId: "nb03", name: "Bétochef", number: "064/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/64.webp", },
{ id: "nb03-065", serieId: "nb03", name: "Bétochef", number: "065/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/65.webp", },
{ id: "nb03-066", serieId: "nb03", name: "Arkéapti", number: "066/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/66.webp", },
{ id: "nb03-067", serieId: "nb03", name: "Aéroptéryx", number: "067/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/67.webp", },
{ id: "nb03-068", serieId: "nb03", name: "Limonde", number: "068/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/68.webp", },
{ id: "nb03-069", serieId: "nb03", name: "Kungfouine", number: "069/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/69.webp", },
{ id: "nb03-070", serieId: "nb03", name: "Shaofouine", number: "070/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/70.webp", },
{ id: "nb03-071", serieId: "nb03", name: "Gringolem", number: "071/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/71.webp", },
{ id: "nb03-072", serieId: "nb03", name: "Golemastoc", number: "072/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/72.webp", },
{ id: "nb03-073", serieId: "nb03", name: "Terrakium", number: "073/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/73.webp", },
{ id: "nb03-074", serieId: "nb03", name: "Démétéros", number: "074/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/74.webp", },
{ id: "nb03-075", serieId: "nb03", name: "Scalpion", number: "075/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/75.webp", },
{ id: "nb03-076", serieId: "nb03", name: "Scalproie", number: "076/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/76.webp", },
{ id: "nb03-077", serieId: "nb03", name: "Solochi", number: "077/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/77.webp", },
{ id: "nb03-078", serieId: "nb03", name: "Diamat", number: "078/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/78.webp", },
{ id: "nb03-079", serieId: "nb03", name: "Trioxhydre", number: "079/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/79.webp", },
{ id: "nb03-080", serieId: "nb03", name: "Lançargot", number: "080/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/80.webp", },
{ id: "nb03-081", serieId: "nb03", name: "Scalpion", number: "081/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/81.webp", },
{ id: "nb03-082", serieId: "nb03", name: "Scalproie", number: "082/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/82.webp", },
{ id: "nb03-083", serieId: "nb03", name: "Fermite", number: "083/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/83.webp", },
{ id: "nb03-084", serieId: "nb03", name: "Cobaltium", number: "084/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/84.webp", },
{ id: "nb03-085", serieId: "nb03", name: "Nanméouïe", number: "085/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/85.webp", },
{ id: "nb03-086", serieId: "nb03", name: "Coupenotte", number: "086/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/86.webp", },
{ id: "nb03-087", serieId: "nb03", name: "Incisache", number: "087/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/87.webp", },
{ id: "nb03-088", serieId: "nb03", name: "Tranchodon", number: "088/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/88.webp", },
{ id: "nb03-089", serieId: "nb03", name: "Drakkarmin", number: "089/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/89.webp", },
{ id: "nb03-090", serieId: "nb03", name: "Fossile Plaque", number: "090/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/90.webp", },
{ id: "nb03-091", serieId: "nb03", name: "Évoluroc", number: "091/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/91.webp", },
{ id: "nb03-092", serieId: "nb03", name: "N", number: "092/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/92.webp", },
{ id: "nb03-093", serieId: "nb03", name: "Fossile Plume", number: "093/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/93.webp", },
{ id: "nb03-094", serieId: "nb03", name: "Casque Brut", number: "094/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/94.webp", },
{ id: "nb03-095", serieId: "nb03", name: "Méga Canne", number: "095/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/95.webp", },
{ id: "nb03-096", serieId: "nb03", name: "Vokit", number: "096/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/96.webp", },
{ id: "nb03-097", serieId: "nb03", name: "Viridium", number: "097/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/97.webp", },
{ id: "nb03-098", serieId: "nb03", name: "Victini", number: "098/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/98.webp", },
{ id: "nb03-099", serieId: "nb03", name: "Terrakium", number: "099/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/99.webp", },
{ id: "nb03-100", serieId: "nb03", name: "Cobaltium", number: "100/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/100.webp", },
{ id: "nb03-101", serieId: "nb03", name: "N", number: "101/101", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/101.webp", },
{ id: "nb03-102", serieId: "nb03", name: "Miaouss", number: "102/101", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/nb03/102.webp", },


  
] as unknown as Card[]);
