import type { Card } from "../../catalog";

// Noir et Blanc
export const NOIR_ET_BLANC_CARDS = ([
{ id: "prbw-001", serieId: "prbw", name: "Vipélierre", number: "BW01", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/1.webp", },
{ id: "prbw-002", serieId: "prbw", name: "Gruikui", number: "BW02", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/2.webp", },
{ id: "prbw-003", serieId: "prbw", name: "Moustillon", number: "BW03", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/3.webp", },
{ id: "prbw-004", serieId: "prbw", name: "Reshiram", number: "BW004", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/4.webp", },
{ id: "prbw-005", serieId: "prbw", name: "Zekrom", number: "BW005", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/5.webp", },
{ id: "prbw-006", serieId: "prbw", name: "Vipélierre", number: "BW06", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/6.webp", },
{ id: "prbw-007", serieId: "prbw", name: "Gruikui", number: "BW07", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/7.webp", },
{ id: "prbw-008", serieId: "prbw", name: "Moustillon", number: "BW08", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/8.webp", },
{ id: "prbw-009", serieId: "prbw", name: "Zoroark", number: "BW09", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/9.webp", },
{ id: "prbw-010", serieId: "prbw", name: "Coupenotte", number: "BW10", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/10.webp", },
{ id: "prbw-011", serieId: "prbw", name: "Feuillajou", number: "BW11", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/11.webp", },
{ id: "prbw-012", serieId: "prbw", name: "Zorua", number: "BW12", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/12.webp", },
{ id: "prbw-013", serieId: "prbw", name: "Chinchidou", number: "BW13", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/13.webp", },
{ id: "prbw-014", serieId: "prbw", name: "Feuillajou", number: "BW14", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/14.webp", },
{ id: "prbw-015", serieId: "prbw", name: "Poichigeon", number: "BW15", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/15.webp", },
{ id: "prbw-016", serieId: "prbw", name: "Coupenotte", number: "BW16", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/16.webp", },
{ id: "prbw-017", serieId: "prbw", name: "Couaneton", number: "BW17", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/17.webp", },
{ id: "prbw-018", serieId: "prbw", name: "Darumarond", number: "BW18", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/18.webp", },
{ id: "prbw-019", serieId: "prbw", name: "Zoroark", number: "BW19", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/19.webp", },
{ id: "prbw-020", serieId: "prbw", name: "Majaspic", number: "BW20", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/20.webp", },
{ id: "prbw-021", serieId: "prbw", name: "Roitiflam", number: "BW21", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/21.webp", },
{ id: "prbw-022", serieId: "prbw", name: "Clamiral", number: "BW22", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/22.webp", },
{ id: "prbw-023", serieId: "prbw", name: "Reshiram", number: "BW23", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/23.webp", },
{ id: "prbw-024", serieId: "prbw", name: "Zekrom", number: "BW24", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/24.webp", },
{ id: "prbw-025", serieId: "prbw", name: "Baggiguane", number: "BW25", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/25.webp", },
{ id: "prbw-026", serieId: "prbw", name: "Coupenotte", number: "BW26", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/26.webp", },
{ id: "prbw-027", serieId: "prbw", name: "Funécire", number: "BW27", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/27.webp", },
{ id: "prbw-028", serieId: "prbw", name: "Plage Tropicale", number: "BW28", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/28.webp", },
{ id: "prbw-029", serieId: "prbw", name: "Coupe Victoire", number: "BW29", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/29.webp", },
{ id: "prbw-030", serieId: "prbw", name: "Coupe Victoire", number: "BW30", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/30.webp", },
{ id: "prbw-031", serieId: "prbw", name: "Coupe Victoire", number: "BW31", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/31.webp", },
{ id: "prbw-032", serieId: "prbw", name: "Victini", number: "BW32", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/32.webp", },
{ id: "prbw-033", serieId: "prbw", name: "Riolu", number: "BW33", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/33.webp", },
{ id: "prbw-034", serieId: "prbw", name: "Luxio", number: "BW34", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/34.webp", },
{ id: "prbw-035", serieId: "prbw", name: "Miaouss", number: "BW35", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/35.webp", },
{ id: "prbw-036", serieId: "prbw", name: "Reshiram-EX", number: "BW36", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/36.webp", },
{ id: "prbw-037", serieId: "prbw", name: "Kyurem-EX", number: "BW37", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/37.webp", },
{ id: "prbw-038", serieId: "prbw", name: "Zekrom-EX", number: "BW38", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/38.webp", },
{ id: "prbw-039", serieId: "prbw", name: "Ville Combat", number: "BW39", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/39.webp", },
{ id: "prbw-040", serieId: "prbw", name: "Pyrax", number: "BW40", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/40.webp", },
{ id: "prbw-041", serieId: "prbw", name: "Fulguris", number: "BW41", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/41.webp", },
{ id: "prbw-042", serieId: "prbw", name: "Boréas", number: "BW42", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/42.webp", },
{ id: "prbw-043", serieId: "prbw", name: "Démétéros", number: "BW43", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/43.webp", },
{ id: "prbw-044", serieId: "prbw", name: "Kyurem", number: "BW44", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/44.webp", },
{ id: "prbw-045", serieId: "prbw", name: "Mewtwo-EX", number: "BW45", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/45.webp", },
{ id: "prbw-046", serieId: "prbw", name: "Darkrai-EX", number: "BW46", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/46.webp", },
{ id: "prbw-047", serieId: "prbw", name: "Rayquaza-EX", number: "BW47", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/47.webp", },
{ id: "prbw-048", serieId: "prbw", name: "Altaria", number: "BW48", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/48.webp", },
{ id: "prbw-049", serieId: "prbw", name: "Fragilady", number: "BW49", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/49.webp", },
{ id: "prbw-050", serieId: "prbw", name: "Plage Tropicale", number: "BW50", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/50.webp", },
{ id: "prbw-051", serieId: "prbw", name: "Nostenfer", number: "BW51", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/51.webp", },
{ id: "prbw-052", serieId: "prbw", name: "Ponchiot", number: "BW52", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/52.webp", },
{ id: "prbw-053", serieId: "prbw", name: "Libégon", number: "BW53", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/53.webp", },
{ id: "prbw-054", serieId: "prbw", name: "Pikachu", number: "BW54", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/54.webp", },
{ id: "prbw-055", serieId: "prbw", name: "Lewsor", number: "BW55", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/55.webp", },
{ id: "prbw-056", serieId: "prbw", name: "Pingoléon", number: "BW56", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/56.webp", },
{ id: "prbw-057", serieId: "prbw", name: "Tranchodon", number: "BW57", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/57.webp", },
{ id: "prbw-058", serieId: "prbw", name: "Kyurem Noir", number: "BW58", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/58.webp", },
{ id: "prbw-059", serieId: "prbw", name: "Kyurem Blanc", number: "BW59", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/59.webp", },
{ id: "prbw-060", serieId: "prbw", name: "Keldeo", number: "BW60", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/60.webp", },
{ id: "prbw-061", serieId: "prbw", name: "Keldeo-EX", number: "BW61", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/61.webp", },
{ id: "prbw-062", serieId: "prbw", name: "Kyurem Noir-EX", number: "BW62", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/62.webp", },
{ id: "prbw-063", serieId: "prbw", name: "Kyurem Blanc-EX", number: "BW63", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/63.webp", },
{ id: "prbw-064", serieId: "prbw", name: "Grodrive", number: "BW64", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/64.webp", },
{ id: "prbw-065", serieId: "prbw", name: "Rondoudou", number: "BW65", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/65.webp", },
{ id: "prbw-066", serieId: "prbw", name: "Feunard", number: "BW66", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/66.webp", },
{ id: "prbw-067", serieId: "prbw", name: "Pharamp", number: "BW67", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/67.webp", },
{ id: "prbw-068", serieId: "prbw", name: "Meloetta", number: "BW68", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/68.webp", },
{ id: "prbw-069", serieId: "prbw", name: "Meloetta", number: "BW69", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/69.webp", },
{ id: "prbw-070", serieId: "prbw", name: "Viridium", number: "BW70", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/70.webp", },
{ id: "prbw-071", serieId: "prbw", name: "Terrakium", number: "BW71", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/71.webp", },
{ id: "prbw-072", serieId: "prbw", name: "Cobaltium", number: "BW72", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/72.webp", },
{ id: "prbw-073", serieId: "prbw", name: "Darkrai", number: "BW73", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/73.webp", },
{ id: "prbw-074", serieId: "prbw", name: "Giratina", number: "BW74", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/74.webp", },
{ id: "prbw-075", serieId: "prbw", name: "Métalosse", number: "BW75", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/75.webp", },
{ id: "prbw-076", serieId: "prbw", name: "Électrode", number: "BW76", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/76.webp", },
{ id: "prbw-077", serieId: "prbw", name: "Pikachu", number: "BW77", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/77.webp", },
{ id: "prbw-078", serieId: "prbw", name: "Raichu", number: "BW78", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/78.webp", },
{ id: "prbw-079", serieId: "prbw", name: "Démétéros", number: "BW79", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/79.webp", },
{ id: "prbw-080", serieId: "prbw", name: "Drakkarmin", number: "BW80", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/80.webp", },
{ id: "prbw-081", serieId: "prbw", name: "Fulguris-EX", number: "BW81", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/81.webp", },
{ id: "prbw-082", serieId: "prbw", name: "Deoxys-EX", number: "BW82", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/82.webp", },
{ id: "prbw-083", serieId: "prbw", name: "Lugia-EX", number: "BW83", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/83.webp", },
{ id: "prbw-084", serieId: "prbw", name: "Porygon-Z", number: "BW84", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/84.webp", },
{ id: "prbw-085", serieId: "prbw", name: "Lucario", number: "BW85", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/85.webp", },
{ id: "prbw-086", serieId: "prbw", name: "Genesect", number: "BW86", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/86.webp", },
{ id: "prbw-087", serieId: "prbw", name: "Phyllali", number: "BW87", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/87.webp", },
{ id: "prbw-088", serieId: "prbw", name: "Pyroli", number: "BW88", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/88.webp", },
{ id: "prbw-089", serieId: "prbw", name: "Aquali", number: "BW89", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/89.webp", },
{ id: "prbw-090", serieId: "prbw", name: "Givrali", number: "BW90", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/90.webp", },
{ id: "prbw-091", serieId: "prbw", name: "Voltali", number: "BW91", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/91.webp", },
{ id: "prbw-092", serieId: "prbw", name: "Mentali", number: "BW92", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/92.webp", },
{ id: "prbw-093", serieId: "prbw", name: "Noctali", number: "BW93", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/93.webp", },
{ id: "prbw-094", serieId: "prbw", name: "Évoli", number: "BW94", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/94.webp", },
{ id: "prbw-095", serieId: "prbw", name: "Festival des Champions", number: "BW95", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/95.webp", },
{ id: "prbw-096", serieId: "prbw", name: "Boréas-EX", number: "BW96", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/96.webp", },
{ id: "prbw-097", serieId: "prbw", name: "Évoli", number: "BW97", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/97.webp", },
{ id: "prbw-098", serieId: "prbw", name: "Mew", number: "BW98", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/98.webp", },
{ id: "prbw-099", serieId: "prbw", name: "Genesect", number: "BW99", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/99.webp", },
{ id: "prbw-100", serieId: "prbw", name: "N", number: "BW100", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/100.webp", },
{ id: "prbw-101", serieId: "prbw", name: "Genesect", number: "BW101", rarity: "Promo", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/prbw/101.webp", },






  
] as unknown as Card[]);
