import type { Card } from "../../catalog";

// xy - 1664 cards
export const PLATINE_CARDS = ([


// PT01 - Platine
{ id: "pt01-001", serieId: "PT01", name: "Pharamp", number: "001/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/1.webp", },
{ id: "pt01-002", serieId: "PT01", name: "Tortank", number: "002/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/2.webp", },
{ id: "pt01-003", serieId: "PT01", name: "Brasegali", number: "003/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/3.webp", },
{ id: "pt01-004", serieId: "PT01", name: "Delcatty", number: "004/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/4.webp", },
{ id: "pt01-005", serieId: "PT01", name: "Dialga", number: "005/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/5.webp", },
{ id: "pt01-006", serieId: "PT01", name: "Dialga", number: "006/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/6.webp", },
{ id: "pt01-007", serieId: "PT01", name: "Dialga G", number: "007/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/7.webp", },
{ id: "pt01-008", serieId: "PT01", name: "Gardevoir", number: "008/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/8.webp", },
{ id: "pt01-009", serieId: "PT01", name: "Giratina", number: "009/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/9.webp", },
{ id: "pt01-010", serieId: "PT01", name: "Giratina", number: "010/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/10.webp", },
{ id: "pt01-011", serieId: "PT01", name: "Élecsprint", number: "011/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/11.webp", },
{ id: "pt01-012", serieId: "PT01", name: "Palkia G", number: "012/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/12.webp", },
{ id: "pt01-013", serieId: "PT01", name: "Charkos", number: "013/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/13.webp", },
{ id: "pt01-014", serieId: "PT01", name: "Shaymin", number: "014/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/14.webp", },
{ id: "pt01-015", serieId: "PT01", name: "Shaymin", number: "015/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/15.webp", },
{ id: "pt01-016", serieId: "PT01", name: "Monaflemit", number: "016/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/16.webp", },
{ id: "pt01-017", serieId: "PT01", name: "Dimoret G", number: "017/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/17.webp", },
{ id: "pt01-018", serieId: "PT01", name: "Altaria", number: "018/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/18.webp", },
{ id: "pt01-019", serieId: "PT01", name: "Branette", number: "019/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/19.webp", },
{ id: "pt01-020", serieId: "PT01", name: "Bastiodon", number: "020/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/20.webp", },
{ id: "pt01-021", serieId: "PT01", name: "Charmillon", number: "021/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/21.webp", },
{ id: "pt01-022", serieId: "PT01", name: "Leuphorie", number: "022/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/22.webp", },
{ id: "pt01-023", serieId: "PT01", name: "Dialga", number: "023/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/23.webp", },
{ id: "pt01-024", serieId: "PT01", name: "Triopikeur", number: "024/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/24.webp", },
{ id: "pt01-025", serieId: "PT01", name: "Papinox", number: "025/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/25.webp", },
{ id: "pt01-026", serieId: "PT01", name: "Pingoléon", number: "026/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/26.webp", },
{ id: "pt01-027", serieId: "PT01", name: "Giratina", number: "027/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/27.webp", },
{ id: "pt01-028", serieId: "PT01", name: "Giratina", number: "028/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/28.webp", },
{ id: "pt01-029", serieId: "PT01", name: "Akwakwak", number: "029/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/29.webp", },
{ id: "pt01-030", serieId: "PT01", name: "Leviator G", number: "030/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/30.webp", },
{ id: "pt01-031", serieId: "PT01", name: "Simiabraz", number: "031/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/31.webp", },
{ id: "pt01-032", serieId: "PT01", name: "Mélokrik", number: "032/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/32.webp", },
{ id: "pt01-033", serieId: "PT01", name: "Coudlangue", number: "033/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/33.webp", },
{ id: "pt01-034", serieId: "PT01", name: "Ludicolo", number: "034/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/34.webp", },
{ id: "pt01-035", serieId: "PT01", name: "Lovdisc", number: "035/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/35.webp", },
{ id: "pt01-036", serieId: "PT01", name: "Feunard", number: "036/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/36.webp", },
{ id: "pt01-037", serieId: "PT01", name: "Palkia", number: "037/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/37.webp", },
{ id: "pt01-038", serieId: "PT01", name: "Shaymin", number: "038/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/38.webp", },
{ id: "pt01-039", serieId: "PT01", name: "Torterra", number: "039/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/39.webp", },
{ id: "pt01-040", serieId: "PT01", name: "Coatox G", number: "040/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/40.webp", },
{ id: "pt01-041", serieId: "PT01", name: "Archéodong G", number: "041/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/41.webp", },
{ id: "pt01-042", serieId: "PT01", name: "Cacturne", number: "042/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/42.webp", },
{ id: "pt01-043", serieId: "PT01", name: "Vortente", number: "043/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/43.webp", },
{ id: "pt01-044", serieId: "PT01", name: "Blindalys", number: "044/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/44.webp", },
{ id: "pt01-045", serieId: "PT01", name: "Galifeu", number: "045/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/45.webp", },
{ id: "pt01-046", serieId: "PT01", name: "Kranidos", number: "046/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/46.webp", },
{ id: "pt01-047", serieId: "PT01", name: "Nostenfer G", number: "047/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/47.webp", },
{ id: "pt01-048", serieId: "PT01", name: "Lainergie", number: "048/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/48.webp", },
{ id: "pt01-049", serieId: "PT01", name: "Boskara", number: "049/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/49.webp", },
{ id: "pt01-050", serieId: "PT01", name: "Demolosse G", number: "050/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/50.webp", },
{ id: "pt01-051", serieId: "PT01", name: "Kirlia", number: "051/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/51.webp", },
{ id: "pt01-052", serieId: "PT01", name: "Lombre", number: "052/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/52.webp", },
{ id: "pt01-053", serieId: "PT01", name: "Lucario", number: "053/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/53.webp", },
{ id: "pt01-054", serieId: "PT01", name: "Grahyena", number: "054/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/54.webp", },
{ id: "pt01-055", serieId: "PT01", name: "Magirêve", number: "055/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/55.webp", },
{ id: "pt01-056", serieId: "PT01", name: "Chimpenfeu", number: "056/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/56.webp", },
{ id: "pt01-057", serieId: "PT01", name: "Grotadmorv", number: "057/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/57.webp", },
{ id: "pt01-058", serieId: "PT01", name: "Octillery", number: "058/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/58.webp", },
{ id: "pt01-059", serieId: "PT01", name: "Prinplouf", number: "059/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/59.webp", },
{ id: "pt01-060", serieId: "PT01", name: "Tarinorme", number: "060/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/60.webp", },
{ id: "pt01-061", serieId: "PT01", name: "Seviper", number: "061/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/61.webp", },
{ id: "pt01-062", serieId: "PT01", name: "Dinoclier", number: "062/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/62.webp", },
{ id: "pt01-063", serieId: "PT01", name: "Armulys", number: "063/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/63.webp", },
{ id: "pt01-064", serieId: "PT01", name: "Vigoroth", number: "064/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/64.webp", },
{ id: "pt01-065", serieId: "PT01", name: "Carabaffe", number: "065/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/65.webp", },
{ id: "pt01-066", serieId: "PT01", name: "Mangriff", number: "066/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/66.webp", },
{ id: "pt01-067", serieId: "PT01", name: "Cacnea", number: "067/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/67.webp", },
{ id: "pt01-068", serieId: "PT01", name: "Vortente", number: "068/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/68.webp", },
{ id: "pt01-069", serieId: "PT01", name: "Leveinard", number: "069/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/69.webp", },
{ id: "pt01-070", serieId: "PT01", name: "Ouisticram", number: "070/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/70.webp", },
{ id: "pt01-071", serieId: "PT01", name: "Apitrini", number: "071/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/71.webp", },
{ id: "pt01-072", serieId: "PT01", name: "Taupiqueur", number: "072/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/72.webp", },
{ id: "pt01-073", serieId: "PT01", name: "Insolourdo", number: "073/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/73.webp", },
{ id: "pt01-074", serieId: "PT01", name: "Dynavolt", number: "074/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/74.webp", },
{ id: "pt01-075", serieId: "PT01", name: "Tadmorv", number: "075/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/75.webp", },
{ id: "pt01-076", serieId: "PT01", name: "Ptiravi", number: "076/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/76.webp", },
{ id: "pt01-077", serieId: "PT01", name: "Corboss G", number: "077/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/77.webp", },
{ id: "pt01-078", serieId: "PT01", name: "Crikzik", number: "078/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/78.webp", },
{ id: "pt01-079", serieId: "PT01", name: "Lokhlass", number: "079/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/79.webp", },
{ id: "pt01-080", serieId: "PT01", name: "Excelangue", number: "080/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/80.webp", },
{ id: "pt01-081", serieId: "PT01", name: "Nénupiot", number: "081/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/81.webp", },
{ id: "pt01-082", serieId: "PT01", name: "Wattouat", number: "082/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/82.webp", },
{ id: "pt01-083", serieId: "PT01", name: "Feuforêve", number: "083/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/83.webp", },
{ id: "pt01-084", serieId: "PT01", name: "Tarinor", number: "084/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/84.webp", },
{ id: "pt01-085", serieId: "PT01", name: "Tiplouf", number: "085/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/85.webp", },
{ id: "pt01-086", serieId: "PT01", name: "Medhyena", number: "086/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/86.webp", },
{ id: "pt01-087", serieId: "PT01", name: "Psykokwak", number: "087/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/87.webp", },
{ id: "pt01-088", serieId: "PT01", name: "Chaffreux G", number: "088/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/88.webp", },
{ id: "pt01-089", serieId: "PT01", name: "Tarsal", number: "089/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/89.webp", },
{ id: "pt01-090", serieId: "PT01", name: "Remoraid", number: "090/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/90.webp", },
{ id: "pt01-091", serieId: "PT01", name: "Riolu", number: "091/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/91.webp", },
{ id: "pt01-092", serieId: "PT01", name: "Polychombr", number: "092/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/92.webp", },
{ id: "pt01-093", serieId: "PT01", name: "Skitty", number: "093/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/93.webp", },
{ id: "pt01-094", serieId: "PT01", name: "Moufflair G", number: "094/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/94.webp", },
{ id: "pt01-095", serieId: "PT01", name: "Parecool", number: "095/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/95.webp", },
{ id: "pt01-096", serieId: "PT01", name: "Carapuce", number: "096/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/96.webp", },
{ id: "pt01-097", serieId: "PT01", name: "Tylton", number: "097/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/97.webp", },
{ id: "pt01-098", serieId: "PT01", name: "Tauros", number: "098/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/98.webp", },
{ id: "pt01-099", serieId: "PT01", name: "Poussifeu", number: "099/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/99.webp", },
{ id: "pt01-100", serieId: "PT01", name: "Chartor", number: "100/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/100.webp", },
{ id: "pt01-101", serieId: "PT01", name: "Tortipouss", number: "101/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/101.webp", },
{ id: "pt01-102", serieId: "PT01", name: "Goupix", number: "102/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/102.webp", },
{ id: "pt01-103", serieId: "PT01", name: "Chenipotte", number: "103/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/103.webp", },
{ id: "pt01-104", serieId: "PT01", name: "Espace-Temps brisé", number: "104/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/104.webp", },
{ id: "pt01-105", serieId: "PT01", name: "Le complot d'Hélio", number: "105/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/105.webp", },
{ id: "pt01-106", serieId: "PT01", name: "QG Galaxie", number: "106/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/106.webp", },
{ id: "pt01-107", serieId: "PT01", name: "Niveau Max", number: "107/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/107.webp", },
{ id: "pt01-108", serieId: "PT01", name: "Herbe sauveuse", number: "108/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/108.webp", },
{ id: "pt01-109", serieId: "PT01", name: "L'enquête de Beladonis", number: "109/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/109.webp", },
{ id: "pt01-110", serieId: "PT01", name: "Baie de mémoire", number: "110/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/110.webp", },
{ id: "pt01-111", serieId: "PT01", name: "Vallée miasme", number: "111/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/111.webp", },
{ id: "pt01-112", serieId: "PT01", name: "PlusPower", number: "112/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/112.webp", },
{ id: "pt01-113", serieId: "PT01", name: "Poké Ball", number: "113/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/113.webp", },
{ id: "pt01-114", serieId: "PT01", name: "Pokédex HANDY910is", number: "114/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/114.webp", },
{ id: "pt01-115", serieId: "PT01", name: "Rescousse Pokémon", number: "115/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/115.webp", },
{ id: "pt01-116", serieId: "PT01", name: "Gain d'Énergie Invention G-101 de Team Galaxie", number: "116/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/116.webp", },
{ id: "pt01-117", serieId: "PT01", name: "Spray Puissant Invention G-103 de Team Galaxie", number: "117/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/117.webp", },
{ id: "pt01-118", serieId: "PT01", name: "Poké-Tour Invention G-105 de Team Galaxie", number: "118/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/118.webp", },
{ id: "pt01-119", serieId: "PT01", name: "Fossile armure", number: "119/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/119.webp", },
{ id: "pt01-120", serieId: "PT01", name: "Fossile crâne", number: "120/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/120.webp", },
{ id: "pt01-121", serieId: "PT01", name: "Énergie Multicolore", number: "121/127", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/121.webp", },
{ id: "pt01-122", serieId: "PT01", name: "Dialga G", number: "122/127", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/122.webp", },
{ id: "pt01-123", serieId: "PT01", name: "Drascore", number: "123/127", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/123.webp", },
{ id: "pt01-124", serieId: "PT01", name: "Giratina", number: "124/127", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/124.webp", },
{ id: "pt01-125", serieId: "PT01", name: "Palkia G", number: "125/127", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/125.webp", },
{ id: "pt01-126", serieId: "PT01", name: "Shaymin", number: "126/127", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/126.webp", },
{ id: "pt01-127", serieId: "PT01", name: "Shaymin", number: "127/127", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/127.webp", },
{ id: "pt01-128", serieId: "PT01", name: "Elektek", number: "128/127", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/128.webp", },
{ id: "pt01-129", serieId: "PT01", name: "Tygnon", number: "129/127", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/129.webp", },
{ id: "pt01-130", serieId: "PT01", name: "Insécateur", number: "130/127", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/130.webp", },
{ id: "pt01-sh4", serieId: "PT01", name: "Nénupiot", number: "SH4", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/sh4.webp", },
{ id: "pt01-sh5", serieId: "PT01", name: "Tylton", number: "SH5", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/sh5.webp", },
{ id: "pt01-sh6", serieId: "PT01", name: "Goupix", number: "SH6", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT01/sh6.webp", },

// PT02 - Rivaux Émergeants
{ id: "pt02-001", serieId: "PT02", name: "Arcanin", number: "001/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/1.webp", },
{ id: "pt02-002", serieId: "PT02", name: "Bastiodon", number: "002/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/2.webp", },
{ id: "pt02-003", serieId: "PT02", name: "Darkrai", number: "003/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/3.webp", },
{ id: "pt02-004", serieId: "PT02", name: "Mustéflott", number: "004/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/4.webp", },
{ id: "pt02-005", serieId: "PT02", name: "Libégon", number: "005/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/5.webp", },
{ id: "pt02-006", serieId: "PT02", name: "Momartik", number: "006/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/6.webp", },
{ id: "pt02-007", serieId: "PT02", name: "Jirachi", number: "007/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/7.webp", },
{ id: "pt02-008", serieId: "PT02", name: "Lucario", number: "008/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/8.webp", },
{ id: "pt02-009", serieId: "PT02", name: "Luxray", number: "009/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/9.webp", },
{ id: "pt02-010", serieId: "PT02", name: "Magirêve", number: "010/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/10.webp", },
{ id: "pt02-011", serieId: "PT02", name: "Charkos", number: "011/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/11.webp", },
{ id: "pt02-012", serieId: "PT02", name: "Roserade", number: "012/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/12.webp", },
{ id: "pt02-013", serieId: "PT02", name: "Tengalice", number: "013/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/13.webp", },
{ id: "pt02-014", serieId: "PT02", name: "Galeking", number: "014/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/14.webp", },
{ id: "pt02-015", serieId: "PT02", name: "Dardargnan", number: "015/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/15.webp", },
{ id: "pt02-016", serieId: "PT02", name: "Archéodong", number: "016/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/16.webp", },
{ id: "pt02-017", serieId: "PT02", name: "Drascore", number: "017/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/17.webp", },
{ id: "pt02-018", serieId: "PT02", name: "Mentali", number: "018/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/18.webp", },
{ id: "pt02-019", serieId: "PT02", name: "Pyroli", number: "019/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/19.webp", },
{ id: "pt02-020", serieId: "PT02", name: "Gallame", number: "020/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/20.webp", },
{ id: "pt02-021", serieId: "PT02", name: "Tritosor Mer Orient", number: "021/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/21.webp", },
{ id: "pt02-022", serieId: "PT02", name: "Tritosor Mer Occident", number: "022/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/22.webp", },
{ id: "pt02-023", serieId: "PT02", name: "Grolem", number: "023/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/23.webp", },
{ id: "pt02-024", serieId: "PT02", name: "Scarhino", number: "024/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/24.webp", },
{ id: "pt02-025", serieId: "PT02", name: "Hippodocus", number: "025/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/25.webp", },
{ id: "pt02-026", serieId: "PT02", name: "Voltali", number: "026/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/26.webp", },
{ id: "pt02-027", serieId: "PT02", name: "Mammochon", number: "027/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/27.webp", },
{ id: "pt02-028", serieId: "PT02", name: "M. Mime", number: "028/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/28.webp", },
{ id: "pt02-029", serieId: "PT02", name: "Nidoking", number: "029/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/29.webp", },
{ id: "pt02-030", serieId: "PT02", name: "Nidoqueen", number: "030/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/30.webp", },
{ id: "pt02-031", serieId: "PT02", name: "Raichu", number: "031/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/31.webp", },
{ id: "pt02-032", serieId: "PT02", name: "Rhinastoc", number: "032/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/32.webp", },
{ id: "pt02-033", serieId: "PT02", name: "Ronflex", number: "033/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/33.webp", },
{ id: "pt02-034", serieId: "PT02", name: "Aquali", number: "034/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/34.webp", },
{ id: "pt02-035", serieId: "PT02", name: "Apireine", number: "035/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/35.webp", },
{ id: "pt02-036", serieId: "PT02", name: "Kaimorse", number: "036/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/36.webp", },
{ id: "pt02-037", serieId: "PT02", name: "Yanmega", number: "037/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/37.webp", },
{ id: "pt02-038", serieId: "PT02", name: "Alakazam", number: "038/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/38.webp", },
{ id: "pt02-039", serieId: "PT02", name: "Electrode", number: "039/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/39.webp", },
{ id: "pt02-040", serieId: "PT02", name: "Ectoplasma", number: "040/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/40.webp", },
{ id: "pt02-041", serieId: "PT02", name: "Givrali", number: "041/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/41.webp", },
{ id: "pt02-042", serieId: "PT02", name: "Hippodocus", number: "042/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/42.webp", },
{ id: "pt02-043", serieId: "PT02", name: "Simiabraz", number: "043/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/43.webp", },
{ id: "pt02-044", serieId: "PT02", name: "Galegon", number: "044/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/44.webp", },
{ id: "pt02-045", serieId: "PT02", name: "Phyllali", number: "045/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/45.webp", },
{ id: "pt02-046", serieId: "PT02", name: "Mackogneur", number: "046/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/46.webp", },
{ id: "pt02-047", serieId: "PT02", name: "Galopa", number: "047/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/47.webp", },
{ id: "pt02-048", serieId: "PT02", name: "Cizayox", number: "048/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/48.webp", },
{ id: "pt02-049", serieId: "PT02", name: "Sharpedo", number: "049/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/49.webp", },
{ id: "pt02-050", serieId: "PT02", name: "Staross", number: "050/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/50.webp", },
{ id: "pt02-051", serieId: "PT02", name: "Steelix", number: "051/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/51.webp", },
{ id: "pt02-052", serieId: "PT02", name: "Tropius", number: "052/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/52.webp", },
{ id: "pt02-053", serieId: "PT02", name: "Vibraninf", number: "053/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/53.webp", },
{ id: "pt02-054", serieId: "PT02", name: "Barbicha", number: "054/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/54.webp", },
{ id: "pt02-055", serieId: "PT02", name: "Ptera", number: "055/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/55.webp", },
{ id: "pt02-056", serieId: "PT02", name: "Capidextre", number: "056/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/56.webp", },
{ id: "pt02-057", serieId: "PT02", name: "Galekid", number: "057/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/57.webp", },
{ id: "pt02-058", serieId: "PT02", name: "Carvanha", number: "058/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/58.webp", },
{ id: "pt02-059", serieId: "PT02", name: "Evoli", number: "059/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/59.webp", },
{ id: "pt02-060", serieId: "PT02", name: "Pyroli", number: "060/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/60.webp", },
{ id: "pt02-061", serieId: "PT02", name: "Foretress", number: "061/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/61.webp", },
{ id: "pt02-062", serieId: "PT02", name: "Scorvol", number: "062/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/62.webp", },
{ id: "pt02-063", serieId: "PT02", name: "Caninos", number: "063/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/63.webp", },
{ id: "pt02-064", serieId: "PT02", name: "Hippopotas", number: "064/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/64.webp", },
{ id: "pt02-065", serieId: "PT02", name: "Démolosse", number: "065/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/65.webp", },
{ id: "pt02-066", serieId: "PT02", name: "Coconfort", number: "066/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/66.webp", },
{ id: "pt02-067", serieId: "PT02", name: "Kecleon", number: "067/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/67.webp", },
{ id: "pt02-068", serieId: "PT02", name: "Smogo", number: "068/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/68.webp", },
{ id: "pt02-069", serieId: "PT02", name: "Goinfrex", number: "069/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/69.webp", },
{ id: "pt02-070", serieId: "PT02", name: "Goinfrex", number: "070/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/70.webp", },
{ id: "pt02-071", serieId: "PT02", name: "Nidoran♀", number: "071/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/71.webp", },
{ id: "pt02-072", serieId: "PT02", name: "Nidoran♂", number: "072/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/72.webp", },
{ id: "pt02-073", serieId: "PT02", name: "Nidorina", number: "073/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/73.webp", },
{ id: "pt02-074", serieId: "PT02", name: "Nidorino", number: "074/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/74.webp", },
{ id: "pt02-075", serieId: "PT02", name: "Pifeuil", number: "075/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/75.webp", },
{ id: "pt02-076", serieId: "PT02", name: "Maraiste", number: "076/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/76.webp", },
{ id: "pt02-077", serieId: "PT02", name: "Phogleur", number: "077/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/77.webp", },
{ id: "pt02-078", serieId: "PT02", name: "Grainipiot", number: "078/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/78.webp", },
{ id: "pt02-079", serieId: "PT02", name: "Sancoki Mer Orient", number: "079/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/79.webp", },
{ id: "pt02-080", serieId: "PT02", name: "Sancoki Mer Occident", number: "080/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/80.webp", },
{ id: "pt02-081", serieId: "PT02", name: "Ronflex", number: "081/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/81.webp", },
{ id: "pt02-082", serieId: "PT02", name: "Obalie", number: "082/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/82.webp", },
{ id: "pt02-083", serieId: "PT02", name: "Stari", number: "083/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/83.webp", },
{ id: "pt02-084", serieId: "PT02", name: "Kraknoix", number: "084/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/84.webp", },
{ id: "pt02-085", serieId: "PT02", name: "Tortipouss", number: "085/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/85.webp", },
{ id: "pt02-086", serieId: "PT02", name: "Aspicot", number: "086/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/86.webp", },
{ id: "pt02-087", serieId: "PT02", name: "Smogogo", number: "087/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/87.webp", },
{ id: "pt02-088", serieId: "PT02", name: "La collection d'Aaron", number: "088/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/88.webp", },
{ id: "pt02-089", serieId: "PT02", name: "La recherche d'Amelle", number: "089/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/89.webp", },
{ id: "pt02-090", serieId: "PT02", name: "La chaleur de Terry", number: "090/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/90.webp", },
{ id: "pt02-091", serieId: "PT02", name: "La volonté d'Adrien", number: "091/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/91.webp", },
{ id: "pt02-092", serieId: "PT02", name: "La mission de Lucio", number: "092/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/92.webp", },
{ id: "pt02-093", serieId: "PT02", name: "La salle de concours Pokémon", number: "093/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/93.webp", },
{ id: "pt02-094", serieId: "PT02", name: "Le Gymnase de Rivamar", number: "094/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/94.webp", },
{ id: "pt02-095", serieId: "PT02", name: "Machine Technique Invention G-107 de Team Galaxie", number: "095/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/95.webp", },
{ id: "pt02-096", serieId: "PT02", name: "Radar SP Invention G-109 de Team Galaxie", number: "096/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/96.webp", },
{ id: "pt02-097", serieId: "PT02", name: "Expédition souterraine", number: "097/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/97.webp", },
{ id: "pt02-098", serieId: "PT02", name: "La philosophie de Tanguy", number: "098/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/98.webp", },
{ id: "pt02-099", serieId: "PT02", name: "Énergie Obscurité", number: "099/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/99.webp", },
{ id: "pt02-100", serieId: "PT02", name: "Énergie Métal", number: "100/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/100.webp", },
{ id: "pt02-101", serieId: "PT02", name: "Énergie SP", number: "101/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/101.webp", },
{ id: "pt02-102", serieId: "PT02", name: "Énergie Sup", number: "102/111", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/102.webp", },
{ id: "pt02-103", serieId: "PT02", name: "Alakazam", number: "103/111", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/103.webp", },
{ id: "pt02-104", serieId: "PT02", name: "Mustéflott", number: "104/111", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/104.webp", },
{ id: "pt02-105", serieId: "PT02", name: "Libégon", number: "105/111", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/105.webp", },
{ id: "pt02-106", serieId: "PT02", name: "Gallame", number: "106/111", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/106.webp", },
{ id: "pt02-107", serieId: "PT02", name: "Hippodocus", number: "107/111", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/107.webp", },
{ id: "pt02-108", serieId: "PT02", name: "Simiabraz", number: "108/111", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/108.webp", },
{ id: "pt02-109", serieId: "PT02", name: "Luxray", number: "109/111", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/109.webp", },
{ id: "pt02-110", serieId: "PT02", name: "Magirêve", number: "110/111", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/110.webp", },
{ id: "pt02-111", serieId: "PT02", name: "Ronflex", number: "111/111", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/111.webp", },
{ id: "pt02-112", serieId: "PT02", name: "Pikachu", number: "112/111", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/112.webp", },
{ id: "pt02-113", serieId: "PT02", name: "Pikachu volant", number: "113/111", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/113.webp", },
{ id: "pt02-114", serieId: "PT02", name: "Pikachu surfeur", number: "114/111", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/114.webp", },
{ id: "pt02-rt1", serieId: "PT02", name: "Motisma Hélice", number: "RT1", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/rt1.webp", },
{ id: "pt02-rt2", serieId: "PT02", name: "Motisma Froid", number: "RT2", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/rt2.webp", },
{ id: "pt02-rt3", serieId: "PT02", name: "Motisma Chaleur", number: "RT3", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/rt3.webp", },
{ id: "pt02-rt4", serieId: "PT02", name: "Motisma Tonte", number: "RT4", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/rt4.webp", },
{ id: "pt02-rt5", serieId: "PT02", name: "Motisma Lavage", number: "RT5", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/rt5.webp", },
{ id: "pt02-rt6", serieId: "PT02", name: "Le choix de Pluton", number: "RT6", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT02/rt6.webp", },

// PT03 - Vainqueurs Suprêmes
{ id: "pt03-001", serieId: "PT03", name: "Absol", number: "001/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/1.webp", },
{ id: "pt03-002", serieId: "PT03", name: "Brasegali", number: "002/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/2.webp", },
{ id: "pt03-003", serieId: "PT03", name: "Grodrive", number: "003/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/3.webp", },
{ id: "pt03-004", serieId: "PT03", name: "Elekable", number: "004/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/4.webp", },
{ id: "pt03-005", serieId: "PT03", name: "Carchacrok", number: "005/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/5.webp", },
{ id: "pt03-006", serieId: "PT03", name: "Maganon", number: "006/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/6.webp", },
{ id: "pt03-007", serieId: "PT03", name: "Metalosse", number: "007/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/7.webp", },
{ id: "pt03-008", serieId: "PT03", name: "Rayquaza", number: "008/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/8.webp", },
{ id: "pt03-009", serieId: "PT03", name: "Regigigas", number: "009/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/9.webp", },
{ id: "pt03-010", serieId: "PT03", name: "Rhinastoc", number: "010/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/10.webp", },
{ id: "pt03-011", serieId: "PT03", name: "Etouraptor", number: "011/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/11.webp", },
{ id: "pt03-012", serieId: "PT03", name: "Laggron", number: "012/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/12.webp", },
{ id: "pt03-013", serieId: "PT03", name: "Florizarre", number: "013/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/13.webp", },
{ id: "pt03-014", serieId: "PT03", name: "Yanmega", number: "014/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/14.webp", },
{ id: "pt03-015", serieId: "PT03", name: "Arcanin", number: "015/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/15.webp", },
{ id: "pt03-016", serieId: "PT03", name: "Artikodin", number: "016/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/16.webp", },
{ id: "pt03-017", serieId: "PT03", name: "Papilusion", number: "017/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/17.webp", },
{ id: "pt03-018", serieId: "PT03", name: "Camerupt", number: "018/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/18.webp", },
{ id: "pt03-019", serieId: "PT03", name: "Camerupt", number: "019/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/19.webp", },
{ id: "pt03-020", serieId: "PT03", name: "Dracaufeu", number: "020/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/20.webp", },
{ id: "pt03-021", serieId: "PT03", name: "Éoko", number: "021/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/21.webp", },
{ id: "pt03-022", serieId: "PT03", name: "Kaorine", number: "022/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/22.webp", },
{ id: "pt03-023", serieId: "PT03", name: "Colhomard", number: "023/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/23.webp", },
{ id: "pt03-024", serieId: "PT03", name: "Lamantine", number: "024/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/24.webp", },
{ id: "pt03-025", serieId: "PT03", name: "Dodrio", number: "025/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/25.webp", },
{ id: "pt03-026", serieId: "PT03", name: "Noctunoir", number: "026/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/26.webp", },
{ id: "pt03-027", serieId: "PT03", name: "Pingoléon", number: "027/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/27.webp", },
{ id: "pt03-028", serieId: "PT03", name: "Brouhabam", number: "028/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/28.webp", },
{ id: "pt03-029", serieId: "PT03", name: "Corboss", number: "029/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/29.webp", },
{ id: "pt03-030", serieId: "PT03", name: "Coudlangue", number: "030/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/30.webp", },
{ id: "pt03-031", serieId: "PT03", name: "Lucario", number: "031/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/31.webp", },
{ id: "pt03-032", serieId: "PT03", name: "Seleroc", number: "032/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/32.webp", },
{ id: "pt03-033", serieId: "PT03", name: "Mysdibule", number: "033/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/33.webp", },
{ id: "pt03-034", serieId: "PT03", name: "Charmina", number: "034/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/34.webp", },
{ id: "pt03-035", serieId: "PT03", name: "Milobellus", number: "035/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/35.webp", },
{ id: "pt03-036", serieId: "PT03", name: "Sulfura", number: "036/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/36.webp", },
{ id: "pt03-037", serieId: "PT03", name: "M. Mime", number: "037/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/37.webp", },
{ id: "pt03-038", serieId: "PT03", name: "Parasect", number: "038/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/38.webp", },
{ id: "pt03-039", serieId: "PT03", name: "Colossinge", number: "039/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/39.webp", },
{ id: "pt03-040", serieId: "PT03", name: "Roserade", number: "040/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/40.webp", },
{ id: "pt03-041", serieId: "PT03", name: "Tenefix", number: "041/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/41.webp", },
{ id: "pt03-042", serieId: "PT03", name: "Sablaireau", number: "042/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/42.webp", },
{ id: "pt03-043", serieId: "PT03", name: "Poissoroy", number: "043/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/43.webp", },
{ id: "pt03-044", serieId: "PT03", name: "Munja", number: "044/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/44.webp", },
{ id: "pt03-045", serieId: "PT03", name: "Solaroc", number: "045/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/45.webp", },
{ id: "pt03-046", serieId: "PT03", name: "Spinda", number: "046/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/46.webp", },
{ id: "pt03-047", serieId: "PT03", name: "Wailord", number: "047/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/47.webp", },
{ id: "pt03-048", serieId: "PT03", name: "Electhor", number: "048/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/48.webp", },
{ id: "pt03-049", serieId: "PT03", name: "Altaria", number: "049/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/49.webp", },
{ id: "pt03-050", serieId: "PT03", name: "Arcanin", number: "050/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/50.webp", },
{ id: "pt03-051", serieId: "PT03", name: "Castorno", number: "051/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/51.webp", },
{ id: "pt03-052", serieId: "PT03", name: "Chapignon", number: "052/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/52.webp", },
{ id: "pt03-053", serieId: "PT03", name: "Vortente", number: "053/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/53.webp", },
{ id: "pt03-054", serieId: "PT03", name: "Pijako", number: "054/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/54.webp", },
{ id: "pt03-055", serieId: "PT03", name: "Ceriflor", number: "055/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/55.webp", },
{ id: "pt03-056", serieId: "PT03", name: "Dracolosse", number: "056/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/56.webp", },
{ id: "pt03-057", serieId: "PT03", name: "Grodrive", number: "057/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/57.webp", },
{ id: "pt03-058", serieId: "PT03", name: "Mustéflott", number: "058/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/58.webp", },
{ id: "pt03-059", serieId: "PT03", name: "Carmache", number: "059/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/59.webp", },
{ id: "pt03-060", serieId: "PT03", name: "Carchacrok", number: "060/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/60.webp", },
{ id: "pt03-061", serieId: "PT03", name: "Hippopotas", number: "061/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/61.webp", },
{ id: "pt03-062", serieId: "PT03", name: "Herbizarre", number: "062/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/62.webp", },
{ id: "pt03-063", serieId: "PT03", name: "Lockpin", number: "063/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/63.webp", },
{ id: "pt03-064", serieId: "PT03", name: "Ramboum", number: "064/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/64.webp", },
{ id: "pt03-065", serieId: "PT03", name: "Magmar", number: "065/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/65.webp", },
{ id: "pt03-066", serieId: "PT03", name: "Elecsprint", number: "066/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/66.webp", },
{ id: "pt03-067", serieId: "PT03", name: "Flobio", number: "067/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/67.webp", },
{ id: "pt03-068", serieId: "PT03", name: "Maskadra", number: "068/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/68.webp", },
{ id: "pt03-069", serieId: "PT03", name: "Metang", number: "069/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/69.webp", },
{ id: "pt03-070", serieId: "PT03", name: "Milobellus", number: "070/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/70.webp", },
{ id: "pt03-071", serieId: "PT03", name: "Negapi", number: "071/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/71.webp", },
{ id: "pt03-072", serieId: "PT03", name: "Cornèbre", number: "072/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/72.webp", },
{ id: "pt03-073", serieId: "PT03", name: "Ninjask", number: "073/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/73.webp", },
{ id: "pt03-074", serieId: "PT03", name: "Chamallot", number: "074/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/74.webp", },
{ id: "pt03-075", serieId: "PT03", name: "Scarabrute", number: "075/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/75.webp", },
{ id: "pt03-076", serieId: "PT03", name: "Posipi", number: "076/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/76.webp", },
{ id: "pt03-077", serieId: "PT03", name: "Raichu", number: "077/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/77.webp", },
{ id: "pt03-078", serieId: "PT03", name: "Rattatac", number: "078/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/78.webp", },
{ id: "pt03-079", serieId: "PT03", name: "Relicanth", number: "079/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/79.webp", },
{ id: "pt03-080", serieId: "PT03", name: "Rhinoféros", number: "080/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/80.webp", },
{ id: "pt03-081", serieId: "PT03", name: "Roserade", number: "081/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/81.webp", },
{ id: "pt03-082", serieId: "PT03", name: "Motisma", number: "082/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/82.webp", },
{ id: "pt03-083", serieId: "PT03", name: "Airmure", number: "083/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/83.webp", },
{ id: "pt03-084", serieId: "PT03", name: "Spiritomb", number: "084/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/84.webp", },
{ id: "pt03-085", serieId: "PT03", name: "Etourvol", number: "085/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/85.webp", },
{ id: "pt03-086", serieId: "PT03", name: "Togekiss", number: "086/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/86.webp", },
{ id: "pt03-087", serieId: "PT03", name: "Wailmer", number: "087/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/87.webp", },
{ id: "pt03-088", serieId: "PT03", name: "Yanma", number: "088/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/88.webp", },
{ id: "pt03-089", serieId: "PT03", name: "Balbuto", number: "089/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/89.webp", },
{ id: "pt03-090", serieId: "PT03", name: "Terhal", number: "090/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/90.webp", },
{ id: "pt03-091", serieId: "PT03", name: "Keunotor", number: "091/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/91.webp", },
{ id: "pt03-092", serieId: "PT03", name: "Mustébouée", number: "092/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/92.webp", },
{ id: "pt03-093", serieId: "PT03", name: "Bulbizarre", number: "093/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/93.webp", },
{ id: "pt03-094", serieId: "PT03", name: "Laporeille", number: "094/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/94.webp", },
{ id: "pt03-095", serieId: "PT03", name: "Pijako", number: "095/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/95.webp", },
{ id: "pt03-096", serieId: "PT03", name: "Ceribou", number: "096/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/96.webp", },
{ id: "pt03-097", serieId: "PT03", name: "Ouisticram", number: "097/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/97.webp", },
{ id: "pt03-098", serieId: "PT03", name: "Korillon", number: "098/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/98.webp", },
{ id: "pt03-099", serieId: "PT03", name: "Apitrini", number: "099/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/99.webp", },
{ id: "pt03-100", serieId: "PT03", name: "Écrapince", number: "100/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/100.webp", },
{ id: "pt03-101", serieId: "PT03", name: "Cradopaud", number: "101/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/101.webp", },
{ id: "pt03-102", serieId: "PT03", name: "Doduo", number: "102/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/102.webp", },
{ id: "pt03-103", serieId: "PT03", name: "Baudrive", number: "103/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/103.webp", },
{ id: "pt03-104", serieId: "PT03", name: "Barpau", number: "104/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/104.webp", },
{ id: "pt03-105", serieId: "PT03", name: "Racaillou", number: "105/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/105.webp", },
{ id: "pt03-106", serieId: "PT03", name: "Griknot", number: "106/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/106.webp", },
{ id: "pt03-107", serieId: "PT03", name: "Poissirène", number: "107/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/107.webp", },
{ id: "pt03-108", serieId: "PT03", name: "Caninos", number: "108/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/108.webp", },
{ id: "pt03-109", serieId: "PT03", name: "Crikzik", number: "109/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/109.webp", },
{ id: "pt03-110", serieId: "PT03", name: "Magicarpe", number: "110/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/110.webp", },
{ id: "pt03-111", serieId: "PT03", name: "Magneti", number: "111/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/111.webp", },
{ id: "pt03-112", serieId: "PT03", name: "Férosinge", number: "112/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/112.webp", },
{ id: "pt03-113", serieId: "PT03", name: "Meditikka", number: "113/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/113.webp", },
{ id: "pt03-114", serieId: "PT03", name: "Miaouss", number: "114/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/114.webp", },
{ id: "pt03-115", serieId: "PT03", name: "Mime Jr.", number: "115/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/115.webp", },
{ id: "pt03-116", serieId: "PT03", name: "Gobou", number: "116/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/116.webp", },
{ id: "pt03-117", serieId: "PT03", name: "Ningale", number: "117/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/117.webp", },
{ id: "pt03-118", serieId: "PT03", name: "Pachirisu", number: "118/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/118.webp", },
{ id: "pt03-119", serieId: "PT03", name: "Paras", number: "119/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/119.webp", },
{ id: "pt03-120", serieId: "PT03", name: "Pikachu", number: "120/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/120.webp", },
{ id: "pt03-121", serieId: "PT03", name: "Tiplouf", number: "121/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/121.webp", },
{ id: "pt03-122", serieId: "PT03", name: "Rhinocorne", number: "122/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/122.webp", },
{ id: "pt03-123", serieId: "PT03", name: "Roselia", number: "123/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/123.webp", },
{ id: "pt03-124", serieId: "PT03", name: "Sabelette", number: "124/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/124.webp", },
{ id: "pt03-125", serieId: "PT03", name: "Otaria", number: "125/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/125.webp", },
{ id: "pt03-126", serieId: "PT03", name: "Lixy", number: "126/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/126.webp", },
{ id: "pt03-127", serieId: "PT03", name: "Balignon", number: "127/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/127.webp", },
{ id: "pt03-128", serieId: "PT03", name: "Rapion", number: "128/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/128.webp", },
{ id: "pt03-129", serieId: "PT03", name: "Etourmi", number: "129/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/129.webp", },
{ id: "pt03-130", serieId: "PT03", name: "Arakdo", number: "130/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/130.webp", },
{ id: "pt03-131", serieId: "PT03", name: "Tortipouss", number: "131/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/131.webp", },
{ id: "pt03-132", serieId: "PT03", name: "Chuchmur", number: "132/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/132.webp", },
{ id: "pt03-133", serieId: "PT03", name: "Nosferapti", number: "133/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/133.webp", },
{ id: "pt03-134", serieId: "PT03", name: "Tour de Combat", number: "134/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/134.webp", },
{ id: "pt03-135", serieId: "PT03", name: "Salle de Maître", number: "135/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/135.webp", },
{ id: "pt03-136", serieId: "PT03", name: "Les conseils de Cynthia", number: "136/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/136.webp", },
{ id: "pt03-137", serieId: "PT03", name: "L’initiative d’Hélio", number: "137/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/137.webp", },
{ id: "pt03-138", serieId: "PT03", name: "Télétransporteur nocturne", number: "138/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/138.webp", },
{ id: "pt03-139", serieId: "PT03", name: "La contribution de Koner", number: "139/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/139.webp", },
{ id: "pt03-140", serieId: "PT03", name: "Cherche VS", number: "140/147", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/140.webp", },
{ id: "pt03-141", serieId: "PT03", name: "Absol LV.X", number: "141/147", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/141.webp", },
{ id: "pt03-142", serieId: "PT03", name: "Brasegali LV.X", number: "142/147", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/142.webp", },
{ id: "pt03-143", serieId: "PT03", name: "Dracaufeu LV.X", number: "143/147", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/143.webp", },
{ id: "pt03-144", serieId: "PT03", name: "Elekable LV.X", number: "144/147", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/144.webp", },
{ id: "pt03-145", serieId: "PT03", name: "Carchacrok LV.X", number: "145/147", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/145.webp", },
{ id: "pt03-146", serieId: "PT03", name: "Rayquaza LV.X", number: "146/147", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/146.webp", },
{ id: "pt03-147", serieId: "PT03", name: "Etouraptor LV.X", number: "147/147", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/147.webp", },
{ id: "pt03-sh7", serieId: "PT03", name: "Milobellus", number: "SH7", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/sh7.webp", },
{ id: "pt03-sh8", serieId: "PT03", name: "Relicanth", number: "SH8", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/sh8.webp", },
{ id: "pt03-sh9", serieId: "PT03", name: "Yanma", number: "SH9", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/sh9.webp", },
{ id: "pt03-ar1", serieId: "PT03", name: "Arceus", number: "AR1", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/ar1.webp", },
{ id: "pt03-ar2", serieId: "PT03", name: "Arceus", number: "AR2", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/ar2.webp", },
{ id: "pt03-ar3", serieId: "PT03", name: "Arceus", number: "AR3", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/ar3.webp", },
{ id: "pt03-ar4", serieId: "PT03", name: "Arceus", number: "AR4", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/ar4.webp", },
{ id: "pt03-ar5", serieId: "PT03", name: "Arceus", number: "AR5", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/ar5.webp", },
{ id: "pt03-ar6", serieId: "PT03", name: "Arceus", number: "AR6", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/ar6.webp", },
{ id: "pt03-ar7", serieId: "PT03", name: "Arceus", number: "AR7", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/ar7.webp", },
{ id: "pt03-ar8", serieId: "PT03", name: "Arceus", number: "AR8", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/ar8.webp", },
{ id: "pt03-ar9", serieId: "PT03", name: "Arceus", number: "AR9", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT03/ar9.webp", },

// PT04 - Arceus
{ id: "pt04-001", serieId: "PT04", name: "Dracaufeu", number: "001/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/1.webp", },
{ id: "pt04-002", serieId: "PT04", name: "Momartik", number: "002/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/2.webp", },
{ id: "pt04-003", serieId: "PT04", name: "Heatran", number: "003/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/3.webp", },
{ id: "pt04-004", serieId: "PT04", name: "Kabutops", number: "004/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/4.webp", },
{ id: "pt04-005", serieId: "PT04", name: "Luxray", number: "005/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/5.webp", },
{ id: "pt04-006", serieId: "PT04", name: "Papilord", number: "006/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/6.webp", },
{ id: "pt04-007", serieId: "PT04", name: "Tarinorme", number: "007/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/7.webp", },
{ id: "pt04-008", serieId: "PT04", name: "Drattak", number: "008/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/8.webp", },
{ id: "pt04-009", serieId: "PT04", name: "Avaltout", number: "009/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/9.webp", },
{ id: "pt04-010", serieId: "PT04", name: "Bouldeneu", number: "010/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/10.webp", },
{ id: "pt04-011", serieId: "PT04", name: "Coatox", number: "011/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/11.webp", },
{ id: "pt04-012", serieId: "PT04", name: "Électhor G", number: "012/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/12.webp", },
{ id: "pt04-013", serieId: "PT04", name: "Ptéra", number: "013/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/13.webp", },
{ id: "pt04-014", serieId: "PT04", name: "Archéodong", number: "014/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/14.webp", },
{ id: "pt04-015", serieId: "PT04", name: "Ceriflor", number: "015/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/15.webp", },
{ id: "pt04-016", serieId: "PT04", name: "Ectoplasma", number: "016/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/16.webp", },
{ id: "pt04-017", serieId: "PT04", name: "Ectoplasma", number: "017/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/17.webp", },
{ id: "pt04-018", serieId: "PT04", name: "Oniglali", number: "018/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/18.webp", },
{ id: "pt04-019", serieId: "PT04", name: "Grolem", number: "019/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/19.webp", },
{ id: "pt04-020", serieId: "PT04", name: "Hariyama", number: "020/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/20.webp", },
{ id: "pt04-021", serieId: "PT04", name: "Lockpin", number: "021/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/21.webp", },
{ id: "pt04-022", serieId: "PT04", name: "Élecsprint", number: "022/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/22.webp", },
{ id: "pt04-023", serieId: "PT04", name: "Amonistar", number: "023/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/23.webp", },
{ id: "pt04-024", serieId: "PT04", name: "Bekipan", number: "024/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/24.webp", },
{ id: "pt04-025", serieId: "PT04", name: "Pichu", number: "025/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/25.webp", },
{ id: "pt04-026", serieId: "PT04", name: "Porygon-Z G", number: "026/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/26.webp", },
{ id: "pt04-027", serieId: "PT04", name: "Raichu", number: "027/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/27.webp", },
{ id: "pt04-028", serieId: "PT04", name: "Galopa", number: "028/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/28.webp", },
{ id: "pt04-029", serieId: "PT04", name: "Rattatac", number: "029/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/29.webp", },
{ id: "pt04-030", serieId: "PT04", name: "Jungko", number: "030/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/30.webp", },
{ id: "pt04-031", serieId: "PT04", name: "Jungko", number: "031/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/31.webp", },
{ id: "pt04-032", serieId: "PT04", name: "Spiritomb", number: "032/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/32.webp", },
{ id: "pt04-033", serieId: "PT04", name: "Archéodong", number: "033/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/33.webp", },
{ id: "pt04-034", serieId: "PT04", name: "Archéomire", number: "034/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/34.webp", },
{ id: "pt04-035", serieId: "PT04", name: "Reptincel", number: "035/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/35.webp", },
{ id: "pt04-036", serieId: "PT04", name: "Fantominus", number: "036/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/36.webp", },
{ id: "pt04-037", serieId: "PT04", name: "Gravalanch", number: "037/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/37.webp", },
{ id: "pt04-038", serieId: "PT04", name: "Massko", number: "038/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/38.webp", },
{ id: "pt04-039", serieId: "PT04", name: "Massko", number: "039/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/39.webp", },
{ id: "pt04-040", serieId: "PT04", name: "Gloupti", number: "040/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/40.webp", },
{ id: "pt04-041", serieId: "PT04", name: "Spectrum", number: "041/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/41.webp", },
{ id: "pt04-042", serieId: "PT04", name: "Spectrum", number: "042/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/42.webp", },
{ id: "pt04-043", serieId: "PT04", name: "Luxio", number: "043/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/43.webp", },
{ id: "pt04-044", serieId: "PT04", name: "Élecsprint", number: "044/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/44.webp", },
{ id: "pt04-045", serieId: "PT04", name: "Bekipan", number: "045/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/45.webp", },
{ id: "pt04-046", serieId: "PT04", name: "Ponyta", number: "046/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/46.webp", },
{ id: "pt04-047", serieId: "PT04", name: "Galopa", number: "047/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/47.webp", },
{ id: "pt04-048", serieId: "PT04", name: "Drackhaus", number: "048/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/48.webp", },
{ id: "pt04-049", serieId: "PT04", name: "Cheniselle Cape Plante", number: "049/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/49.webp", },
{ id: "pt04-050", serieId: "PT04", name: "Cheniselle Cape Sable", number: "050/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/50.webp", },
{ id: "pt04-051", serieId: "PT04", name: "Cheniselle Cape Déchet", number: "051/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/51.webp", },
{ id: "pt04-052", serieId: "PT04", name: "Draby", number: "052/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/52.webp", },
{ id: "pt04-053", serieId: "PT04", name: "Dardargnan G", number: "053/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/53.webp", },
{ id: "pt04-054", serieId: "PT04", name: "Archéomire", number: "054/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/54.webp", },
{ id: "pt04-055", serieId: "PT04", name: "Laporeille", number: "055/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/55.webp", },
{ id: "pt04-056", serieId: "PT04", name: "Cheniti Cape Plante", number: "056/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/56.webp", },
{ id: "pt04-057", serieId: "PT04", name: "Cheniti Cape Sable", number: "057/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/57.webp", },
{ id: "pt04-058", serieId: "PT04", name: "Cheniti Cape Déchet", number: "058/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/58.webp", },
{ id: "pt04-059", serieId: "PT04", name: "Salamèche", number: "059/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/59.webp", },
{ id: "pt04-060", serieId: "PT04", name: "Ceribou", number: "060/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/60.webp", },
{ id: "pt04-061", serieId: "PT04", name: "Cradopaud", number: "061/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/61.webp", },
{ id: "pt04-062", serieId: "PT04", name: "Dynavolt", number: "062/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/62.webp", },
{ id: "pt04-063", serieId: "PT04", name: "Dynavolt", number: "063/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/63.webp", },
{ id: "pt04-064", serieId: "PT04", name: "Fantominus", number: "064/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/64.webp", },
{ id: "pt04-065", serieId: "PT04", name: "Racaillou", number: "065/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/65.webp", },
{ id: "pt04-066", serieId: "PT04", name: "Gloupti", number: "066/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/66.webp", },
{ id: "pt04-067", serieId: "PT04", name: "Kabuto", number: "067/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/67.webp", },
{ id: "pt04-068", serieId: "PT04", name: "Makuhita", number: "068/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/68.webp", },
{ id: "pt04-069", serieId: "PT04", name: "Tarinor", number: "069/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/69.webp", },
{ id: "pt04-070", serieId: "PT04", name: "Amonita", number: "070/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/70.webp", },
{ id: "pt04-071", serieId: "PT04", name: "Pikachu", number: "071/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/71.webp", },
{ id: "pt04-072", serieId: "PT04", name: "Ponyta", number: "072/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/72.webp", },
{ id: "pt04-073", serieId: "PT04", name: "Rattata", number: "073/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/73.webp", },
{ id: "pt04-074", serieId: "PT04", name: "Lixy", number: "074/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/74.webp", },
{ id: "pt04-075", serieId: "PT04", name: "Stalgamin", number: "075/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/75.webp", },
{ id: "pt04-076", serieId: "PT04", name: "Saquedeneu", number: "076/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/76.webp", },
{ id: "pt04-077", serieId: "PT04", name: "Saquedeneu", number: "077/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/77.webp", },
{ id: "pt04-078", serieId: "PT04", name: "Arcko", number: "078/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/78.webp", },
{ id: "pt04-079", serieId: "PT04", name: "Arcko", number: "079/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/79.webp", },
{ id: "pt04-080", serieId: "PT04", name: "Goélise", number: "080/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/80.webp", },
{ id: "pt04-081", serieId: "PT04", name: "Goélise", number: "081/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/81.webp", },
{ id: "pt04-082", serieId: "PT04", name: "Portail de Début", number: "082/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/82.webp", },
{ id: "pt04-083", serieId: "PT04", name: "Bouclier Banc", number: "083/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/83.webp", },
{ id: "pt04-084", serieId: "PT04", name: "Pièce Tampon", number: "084/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/84.webp", },
{ id: "pt04-085", serieId: "PT04", name: "Vendeuse du Centre Commercial", number: "085/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/85.webp", },
{ id: "pt04-086", serieId: "PT04", name: "Restauration d'Énergie", number: "086/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/86.webp", },
{ id: "pt04-087", serieId: "PT04", name: "Ceinture Expert", number: "087/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/87.webp", },
{ id: "pt04-088", serieId: "PT04", name: "Œuf Chance", number: "088/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/88.webp", },
{ id: "pt04-089", serieId: "PT04", name: "Vieil Ambre", number: "089/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/89.webp", },
{ id: "pt04-090", serieId: "PT04", name: "Visite du Prof. Chen", number: "090/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/90.webp", },
{ id: "pt04-091", serieId: "PT04", name: "Zone Ultime", number: "091/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/91.webp", },
{ id: "pt04-092", serieId: "PT04", name: "Fossile Dôme", number: "092/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/92.webp", },
{ id: "pt04-093", serieId: "PT04", name: "Fossile Nautile", number: "093/99", rarity: "Reverse", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/93.webp", },
{ id: "pt04-094", serieId: "PT04", name: "Arceus LV.X", number: "094/99", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/94.webp", },
{ id: "pt04-095", serieId: "PT04", name: "Arceus LV.X", number: "095/99", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/95.webp", },
{ id: "pt04-096", serieId: "PT04", name: "Arceus LV.X", number: "096/99", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/96.webp", },
{ id: "pt04-097", serieId: "PT04", name: "Ectoplasma LV.X", number: "097/99", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/97.webp", },
{ id: "pt04-098", serieId: "PT04", name: "Drattak LV.X", number: "098/99", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/98.webp", },
{ id: "pt04-099", serieId: "PT04", name: "Bouldeneu LV.X", number: "099/99", rarity: "Ultra rare", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/99.webp", },
{ id: "pt04-ar1", serieId: "PT04", name: "Arceus", number: "AR1", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/ar1.webp", },
{ id: "pt04-ar2", serieId: "PT04", name: "Arceus", number: "AR2", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/ar2.webp", },
{ id: "pt04-ar3", serieId: "PT04", name: "Arceus", number: "AR3", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/ar3.webp", },
{ id: "pt04-ar4", serieId: "PT04", name: "Arceus", number: "AR4", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/ar4.webp", },
{ id: "pt04-ar5", serieId: "PT04", name: "Arceus", number: "AR5", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/ar5.webp", },
{ id: "pt04-ar6", serieId: "PT04", name: "Arceus", number: "AR6", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/ar6.webp", },
{ id: "pt04-ar7", serieId: "PT04", name: "Arceus", number: "AR7", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/ar7.webp", },
{ id: "pt04-ar8", serieId: "PT04", name: "Arceus", number: "AR8", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/ar8.webp", },
{ id: "pt04-ar9", serieId: "PT04", name: "Arceus", number: "AR9", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/ar9.webp", },
{ id: "pt04-sh10", serieId: "PT04", name: "Draby", number: "SH10", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/sh10.webp", },
{ id: "pt04-sh11", serieId: "PT04", name: "Ponyta", number: "SH11", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/sh11.webp", },
{ id: "pt04-sh12", serieId: "PT04", name: "Lixy", number: "SH12", rarity: "Secrete", condition: "Near Mint", language: "FR", price: 1, stock: 0, image: "/cartes/PT04/sh12.webp", },
] as unknown as Card[]);
